<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="enumFilterBool">
    <xs:restriction base="xs:string">
      <xs:enumeration value="AND"/>
      <xs:enumeration value="OR"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="enumTrueFalse">
    <xs:restriction base="xs:string">
      <xs:enumeration value="0"/>
      <xs:enumeration value="1"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="enumFilterDateDow">
    <xs:restriction base="xs:string">
      <xs:enumeration value="SUN"/>
      <xs:enumeration value="MON"/>
      <xs:enumeration value="TUE"/>
      <xs:enumeration value="WED"/>
      <xs:enumeration value="THU"/>
      <xs:enumeration value="FRI"/>
      <xs:enumeration value="SAT"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="enumFilterDatePeriod">
    <xs:restriction base="xs:string">
      <xs:enumeration value="MONTHLY"/>
      <xs:enumeration value="WEEKLY"/>
      <xs:enumeration value="YEARLY"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="IFilter" abstract="true">
    <xs:attribute name="bool" type="enumFilterBool" use="required" />
    <xs:attribute name="not" type="enumTrueFalse" use="required" />
    <xs:attribute name="hidden" type="enumTrueFalse" use="optional" />
  </xs:complexType>

  <xs:element name="FilterDate">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="IFilter">
          <xs:attribute name="period" type="enumFilterDatePeriod" use="required" />
          <xs:attribute name="dow" type="enumFilterDateDow" use="optional" />
          <xs:attribute name="day" type="xs:unsignedByte" use="optional" />
          <xs:attribute name="month" type="xs:unsignedByte" use="optional" />
          <xs:attribute name="year" type="xs:unsignedShort" use="optional" />
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>

</xs:schema>
