// Copyright (c) 2005-2017 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "filematchschema.h"

// EnumFilterBool
// 

EnumFilterBool::
EnumFilterBool (Value v)
: ::xml_schema::String (_xsd_EnumFilterBool_literals_[v])
{
}

EnumFilterBool::
EnumFilterBool (const char* v)
: ::xml_schema::String (v)
{
}

EnumFilterBool::
EnumFilterBool (const ::std::string& v)
: ::xml_schema::String (v)
{
}

EnumFilterBool::
EnumFilterBool (const ::xml_schema::String& v)
: ::xml_schema::String (v)
{
}

EnumFilterBool::
EnumFilterBool (const EnumFilterBool& v,
                ::xml_schema::Flags f,
                ::xml_schema::Container* c)
: ::xml_schema::String (v, f, c)
{
}

EnumFilterBool& EnumFilterBool::
operator= (Value v)
{
  static_cast< ::xml_schema::String& > (*this) = 
  ::xml_schema::String (_xsd_EnumFilterBool_literals_[v]);

  return *this;
}


// EnumTrueFalse
// 

EnumTrueFalse::
EnumTrueFalse (Value v)
: ::xml_schema::String (_xsd_EnumTrueFalse_literals_[v])
{
}

EnumTrueFalse::
EnumTrueFalse (const char* v)
: ::xml_schema::String (v)
{
}

EnumTrueFalse::
EnumTrueFalse (const ::std::string& v)
: ::xml_schema::String (v)
{
}

EnumTrueFalse::
EnumTrueFalse (const ::xml_schema::String& v)
: ::xml_schema::String (v)
{
}

EnumTrueFalse::
EnumTrueFalse (const EnumTrueFalse& v,
               ::xml_schema::Flags f,
               ::xml_schema::Container* c)
: ::xml_schema::String (v, f, c)
{
}

EnumTrueFalse& EnumTrueFalse::
operator= (Value v)
{
  static_cast< ::xml_schema::String& > (*this) = 
  ::xml_schema::String (_xsd_EnumTrueFalse_literals_[v]);

  return *this;
}


// EnumFilterFileType
// 

EnumFilterFileType::
EnumFilterFileType (Value v)
: ::xml_schema::String (_xsd_EnumFilterFileType_literals_[v])
{
}

EnumFilterFileType::
EnumFilterFileType (const char* v)
: ::xml_schema::String (v)
{
}

EnumFilterFileType::
EnumFilterFileType (const ::std::string& v)
: ::xml_schema::String (v)
{
}

EnumFilterFileType::
EnumFilterFileType (const ::xml_schema::String& v)
: ::xml_schema::String (v)
{
}

EnumFilterFileType::
EnumFilterFileType (const EnumFilterFileType& v,
                    ::xml_schema::Flags f,
                    ::xml_schema::Container* c)
: ::xml_schema::String (v, f, c)
{
}

EnumFilterFileType& EnumFilterFileType::
operator= (Value v)
{
  static_cast< ::xml_schema::String& > (*this) = 
  ::xml_schema::String (_xsd_EnumFilterFileType_literals_[v]);

  return *this;
}


// IFilter
// 

const IFilter::BoolType& IFilter::
bool_ () const
{
  return this->bool__.get ();
}

IFilter::BoolType& IFilter::
bool_ ()
{
  return this->bool__.get ();
}

void IFilter::
bool_ (const BoolType& x)
{
  this->bool__.set (x);
}

void IFilter::
bool_ (::std::unique_ptr< BoolType > x)
{
  this->bool__.set (std::move (x));
}

const IFilter::NotType& IFilter::
not_ () const
{
  return this->not__.get ();
}

IFilter::NotType& IFilter::
not_ ()
{
  return this->not__.get ();
}

void IFilter::
not_ (const NotType& x)
{
  this->not__.set (x);
}

void IFilter::
not_ (::std::unique_ptr< NotType > x)
{
  this->not__.set (std::move (x));
}

const IFilter::HiddenOptional& IFilter::
hidden () const
{
  return this->hidden_;
}

IFilter::HiddenOptional& IFilter::
hidden ()
{
  return this->hidden_;
}

void IFilter::
hidden (const HiddenType& x)
{
  this->hidden_.set (x);
}

void IFilter::
hidden (const HiddenOptional& x)
{
  this->hidden_ = x;
}

void IFilter::
hidden (::std::unique_ptr< HiddenType > x)
{
  this->hidden_.set (std::move (x));
}


// FilterFile
// 

const FilterFile::GteType& FilterFile::
gte () const
{
  return this->gte_.get ();
}

FilterFile::GteType& FilterFile::
gte ()
{
  return this->gte_.get ();
}

void FilterFile::
gte (const GteType& x)
{
  this->gte_.set (x);
}

void FilterFile::
gte (::std::unique_ptr< GteType > x)
{
  this->gte_.set (std::move (x));
}

const FilterFile::GteType& FilterFile::
gte_default_value ()
{
  return gte_default_value_;
}

const FilterFile::LteType& FilterFile::
lte () const
{
  return this->lte_.get ();
}

FilterFile::LteType& FilterFile::
lte ()
{
  return this->lte_.get ();
}

void FilterFile::
lte (const LteType& x)
{
  this->lte_.set (x);
}

void FilterFile::
lte (::std::unique_ptr< LteType > x)
{
  this->lte_.set (std::move (x));
}

const FilterFile::LteType& FilterFile::
lte_default_value ()
{
  return lte_default_value_;
}

const FilterFile::MinOptional& FilterFile::
min () const
{
  return this->min_;
}

FilterFile::MinOptional& FilterFile::
min ()
{
  return this->min_;
}

void FilterFile::
min (const MinType& x)
{
  this->min_.set (x);
}

void FilterFile::
min (const MinOptional& x)
{
  this->min_ = x;
}

void FilterFile::
min (::std::unique_ptr< MinType > x)
{
  this->min_.set (std::move (x));
}

const FilterFile::MaxOptional& FilterFile::
max () const
{
  return this->max_;
}

FilterFile::MaxOptional& FilterFile::
max ()
{
  return this->max_;
}

void FilterFile::
max (const MaxType& x)
{
  this->max_.set (x);
}

void FilterFile::
max (const MaxOptional& x)
{
  this->max_ = x;
}

void FilterFile::
max (::std::unique_ptr< MaxType > x)
{
  this->max_.set (std::move (x));
}

const FilterFile::PathType& FilterFile::
path () const
{
  return this->path_.get ();
}

FilterFile::PathType& FilterFile::
path ()
{
  return this->path_.get ();
}

void FilterFile::
path (const PathType& x)
{
  this->path_.set (x);
}

void FilterFile::
path (::std::unique_ptr< PathType > x)
{
  this->path_.set (std::move (x));
}

const FilterFile::TypeType& FilterFile::
type () const
{
  return this->type_.get ();
}

FilterFile::TypeType& FilterFile::
type ()
{
  return this->type_.get ();
}

void FilterFile::
type (const TypeType& x)
{
  this->type_.set (x);
}

void FilterFile::
type (::std::unique_ptr< TypeType > x)
{
  this->type_.set (std::move (x));
}

const FilterFile::TypeType& FilterFile::
type_default_value ()
{
  return type_default_value_;
}

const FilterFile::FolderType& FilterFile::
folder () const
{
  return this->folder_.get ();
}

FilterFile::FolderType& FilterFile::
folder ()
{
  return this->folder_.get ();
}

void FilterFile::
folder (const FolderType& x)
{
  this->folder_.set (x);
}

void FilterFile::
folder (::std::unique_ptr< FolderType > x)
{
  this->folder_.set (std::move (x));
}

const FilterFile::FolderType& FilterFile::
folder_default_value ()
{
  return folder_default_value_;
}


#include <xsd/cxx/xml/dom/wildcard-source.hxx>

#include <xsd/cxx/xml/dom/parsing-source.hxx>

#include <xsd/cxx/tree/type-factory-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_factory_plate< 0, char >
  type_factory_plate_init;
}

// EnumFilterBool
//

EnumFilterBool::
EnumFilterBool (const ::xercesc::DOMElement& e,
                ::xml_schema::Flags f,
                ::xml_schema::Container* c)
: ::xml_schema::String (e, f, c)
{
  _xsd_EnumFilterBool_convert ();
}

EnumFilterBool::
EnumFilterBool (const ::xercesc::DOMAttr& a,
                ::xml_schema::Flags f,
                ::xml_schema::Container* c)
: ::xml_schema::String (a, f, c)
{
  _xsd_EnumFilterBool_convert ();
}

EnumFilterBool::
EnumFilterBool (const ::std::string& s,
                const ::xercesc::DOMElement* e,
                ::xml_schema::Flags f,
                ::xml_schema::Container* c)
: ::xml_schema::String (s, e, f, c)
{
  _xsd_EnumFilterBool_convert ();
}

EnumFilterBool* EnumFilterBool::
_clone (::xml_schema::Flags f,
        ::xml_schema::Container* c) const
{
  return new class EnumFilterBool (*this, f, c);
}

EnumFilterBool::Value EnumFilterBool::
_xsd_EnumFilterBool_convert () const
{
  ::xsd::cxx::tree::enum_comparator< char > c (_xsd_EnumFilterBool_literals_);
  const Value* i (::std::lower_bound (
                    _xsd_EnumFilterBool_indexes_,
                    _xsd_EnumFilterBool_indexes_ + 2,
                    *this,
                    c));

  if (i == _xsd_EnumFilterBool_indexes_ + 2 || _xsd_EnumFilterBool_literals_[*i] != *this)
  {
    throw ::xsd::cxx::tree::unexpected_enumerator < char > (*this);
  }

  return *i;
}

const char* const EnumFilterBool::
_xsd_EnumFilterBool_literals_[2] =
{
  "AND",
  "OR"
};

const EnumFilterBool::Value EnumFilterBool::
_xsd_EnumFilterBool_indexes_[2] =
{
  ::EnumFilterBool::AND,
  ::EnumFilterBool::OR
};

static
const ::xsd::cxx::tree::type_factory_initializer< 0, char, EnumFilterBool >
_xsd_EnumFilterBool_type_factory_init (
  "enumFilterBool",
  "");

// EnumTrueFalse
//

EnumTrueFalse::
EnumTrueFalse (const ::xercesc::DOMElement& e,
               ::xml_schema::Flags f,
               ::xml_schema::Container* c)
: ::xml_schema::String (e, f, c)
{
  _xsd_EnumTrueFalse_convert ();
}

EnumTrueFalse::
EnumTrueFalse (const ::xercesc::DOMAttr& a,
               ::xml_schema::Flags f,
               ::xml_schema::Container* c)
: ::xml_schema::String (a, f, c)
{
  _xsd_EnumTrueFalse_convert ();
}

EnumTrueFalse::
EnumTrueFalse (const ::std::string& s,
               const ::xercesc::DOMElement* e,
               ::xml_schema::Flags f,
               ::xml_schema::Container* c)
: ::xml_schema::String (s, e, f, c)
{
  _xsd_EnumTrueFalse_convert ();
}

EnumTrueFalse* EnumTrueFalse::
_clone (::xml_schema::Flags f,
        ::xml_schema::Container* c) const
{
  return new class EnumTrueFalse (*this, f, c);
}

EnumTrueFalse::Value EnumTrueFalse::
_xsd_EnumTrueFalse_convert () const
{
  ::xsd::cxx::tree::enum_comparator< char > c (_xsd_EnumTrueFalse_literals_);
  const Value* i (::std::lower_bound (
                    _xsd_EnumTrueFalse_indexes_,
                    _xsd_EnumTrueFalse_indexes_ + 2,
                    *this,
                    c));

  if (i == _xsd_EnumTrueFalse_indexes_ + 2 || _xsd_EnumTrueFalse_literals_[*i] != *this)
  {
    throw ::xsd::cxx::tree::unexpected_enumerator < char > (*this);
  }

  return *i;
}

const char* const EnumTrueFalse::
_xsd_EnumTrueFalse_literals_[2] =
{
  "0",
  "1"
};

const EnumTrueFalse::Value EnumTrueFalse::
_xsd_EnumTrueFalse_indexes_[2] =
{
  ::EnumTrueFalse::cxx_0,
  ::EnumTrueFalse::cxx_1
};

static
const ::xsd::cxx::tree::type_factory_initializer< 0, char, EnumTrueFalse >
_xsd_EnumTrueFalse_type_factory_init (
  "enumTrueFalse",
  "");

// EnumFilterFileType
//

EnumFilterFileType::
EnumFilterFileType (const ::xercesc::DOMElement& e,
                    ::xml_schema::Flags f,
                    ::xml_schema::Container* c)
: ::xml_schema::String (e, f, c)
{
  _xsd_EnumFilterFileType_convert ();
}

EnumFilterFileType::
EnumFilterFileType (const ::xercesc::DOMAttr& a,
                    ::xml_schema::Flags f,
                    ::xml_schema::Container* c)
: ::xml_schema::String (a, f, c)
{
  _xsd_EnumFilterFileType_convert ();
}

EnumFilterFileType::
EnumFilterFileType (const ::std::string& s,
                    const ::xercesc::DOMElement* e,
                    ::xml_schema::Flags f,
                    ::xml_schema::Container* c)
: ::xml_schema::String (s, e, f, c)
{
  _xsd_EnumFilterFileType_convert ();
}

EnumFilterFileType* EnumFilterFileType::
_clone (::xml_schema::Flags f,
        ::xml_schema::Container* c) const
{
  return new class EnumFilterFileType (*this, f, c);
}

EnumFilterFileType::Value EnumFilterFileType::
_xsd_EnumFilterFileType_convert () const
{
  ::xsd::cxx::tree::enum_comparator< char > c (_xsd_EnumFilterFileType_literals_);
  const Value* i (::std::lower_bound (
                    _xsd_EnumFilterFileType_indexes_,
                    _xsd_EnumFilterFileType_indexes_ + 2,
                    *this,
                    c));

  if (i == _xsd_EnumFilterFileType_indexes_ + 2 || _xsd_EnumFilterFileType_literals_[*i] != *this)
  {
    throw ::xsd::cxx::tree::unexpected_enumerator < char > (*this);
  }

  return *i;
}

const char* const EnumFilterFileType::
_xsd_EnumFilterFileType_literals_[2] =
{
  "EXISTS",
  "VERSION"
};

const EnumFilterFileType::Value EnumFilterFileType::
_xsd_EnumFilterFileType_indexes_[2] =
{
  ::EnumFilterFileType::EXISTS,
  ::EnumFilterFileType::VERSION
};

static
const ::xsd::cxx::tree::type_factory_initializer< 0, char, EnumFilterFileType >
_xsd_EnumFilterFileType_type_factory_init (
  "enumFilterFileType",
  "");

// IFilter
//

IFilter::
IFilter (const BoolType& bool_,
         const NotType& not_)
: ::xml_schema::Type (),
  bool__ (bool_, this),
  not__ (not_, this),
  hidden_ (this)
{
}

IFilter::
IFilter (const IFilter& x,
         ::xml_schema::Flags f,
         ::xml_schema::Container* c)
: ::xml_schema::Type (x, f, c),
  bool__ (x.bool__, f, this),
  not__ (x.not__, f, this),
  hidden_ (x.hidden_, f, this)
{
}

IFilter::
IFilter (const ::xercesc::DOMElement& e,
         ::xml_schema::Flags f,
         ::xml_schema::Container* c)
: ::xml_schema::Type (e, f | ::xml_schema::Flags::base, c),
  bool__ (this),
  not__ (this),
  hidden_ (this)
{
  if ((f & ::xml_schema::Flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, false, false, true);
    this->parse (p, f);
  }
}

void IFilter::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::Flags f)
{
  while (p.more_attributes ())
  {
    const ::xercesc::DOMAttr& i (p.next_attribute ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    if (n.name () == "bool" && n.namespace_ ().empty ())
    {
      this->bool__.set (BoolTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "not" && n.namespace_ ().empty ())
    {
      this->not__.set (NotTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "hidden" && n.namespace_ ().empty ())
    {
      this->hidden_.set (HiddenTraits::create (i, f, this));
      continue;
    }
  }

  if (!bool__.present ())
  {
    throw ::xsd::cxx::tree::expected_attribute< char > (
      "bool",
      "");
  }

  if (!not__.present ())
  {
    throw ::xsd::cxx::tree::expected_attribute< char > (
      "not",
      "");
  }
}

IFilter& IFilter::
operator= (const IFilter& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::Type& > (*this) = x;
    this->bool__ = x.bool__;
    this->not__ = x.not__;
    this->hidden_ = x.hidden_;
  }

  return *this;
}

IFilter::
~IFilter ()
{
}

// FilterFile
//

const FilterFile::GteType FilterFile::gte_default_value_ (
  "0");

const FilterFile::LteType FilterFile::lte_default_value_ (
  "0");

const FilterFile::TypeType FilterFile::type_default_value_ (
  "EXISTS");

const FilterFile::FolderType FilterFile::folder_default_value_ (
  "0");

FilterFile::
FilterFile (const BoolType& bool_,
            const NotType& not_,
            const PathType& path)
: ::IFilter (bool_,
             not_),
  gte_ (gte_default_value (), this),
  lte_ (lte_default_value (), this),
  min_ (this),
  max_ (this),
  path_ (path, this),
  type_ (type_default_value (), this),
  folder_ (folder_default_value (), this)
{
}

FilterFile::
FilterFile (const FilterFile& x,
            ::xml_schema::Flags f,
            ::xml_schema::Container* c)
: ::IFilter (x, f, c),
  gte_ (x.gte_, f, this),
  lte_ (x.lte_, f, this),
  min_ (x.min_, f, this),
  max_ (x.max_, f, this),
  path_ (x.path_, f, this),
  type_ (x.type_, f, this),
  folder_ (x.folder_, f, this)
{
}

FilterFile::
FilterFile (const ::xercesc::DOMElement& e,
            ::xml_schema::Flags f,
            ::xml_schema::Container* c)
: ::IFilter (e, f | ::xml_schema::Flags::base, c),
  gte_ (this),
  lte_ (this),
  min_ (this),
  max_ (this),
  path_ (this),
  type_ (this),
  folder_ (this)
{
  if ((f & ::xml_schema::Flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, false, false, true);
    this->parse (p, f);
  }
}

void FilterFile::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::Flags f)
{
  this->::IFilter::parse (p, f);

  p.reset_attributes ();

  while (p.more_attributes ())
  {
    const ::xercesc::DOMAttr& i (p.next_attribute ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    if (n.name () == "gte" && n.namespace_ ().empty ())
    {
      this->gte_.set (GteTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "lte" && n.namespace_ ().empty ())
    {
      this->lte_.set (LteTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "min" && n.namespace_ ().empty ())
    {
      this->min_.set (MinTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "max" && n.namespace_ ().empty ())
    {
      this->max_.set (MaxTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "path" && n.namespace_ ().empty ())
    {
      this->path_.set (PathTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "type" && n.namespace_ ().empty ())
    {
      this->type_.set (TypeTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "folder" && n.namespace_ ().empty ())
    {
      this->folder_.set (FolderTraits::create (i, f, this));
      continue;
    }
  }

  if (!gte_.present ())
  {
    this->gte_.set (gte_default_value ());
  }

  if (!lte_.present ())
  {
    this->lte_.set (lte_default_value ());
  }

  if (!path_.present ())
  {
    throw ::xsd::cxx::tree::expected_attribute< char > (
      "path",
      "");
  }

  if (!type_.present ())
  {
    this->type_.set (type_default_value ());
  }

  if (!folder_.present ())
  {
    this->folder_.set (folder_default_value ());
  }
}

FilterFile* FilterFile::
_clone (::xml_schema::Flags f,
        ::xml_schema::Container* c) const
{
  return new class FilterFile (*this, f, c);
}

FilterFile& FilterFile::
operator= (const FilterFile& x)
{
  if (this != &x)
  {
    static_cast< ::IFilter& > (*this) = x;
    this->gte_ = x.gte_;
    this->lte_ = x.lte_;
    this->min_ = x.min_;
    this->max_ = x.max_;
    this->path_ = x.path_;
    this->type_ = x.type_;
    this->folder_ = x.folder_;
  }

  return *this;
}

FilterFile::
~FilterFile ()
{
}

#include <ostream>

#include <xsd/cxx/tree/std-ostream-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::std_ostream_plate< 0, char >
  std_ostream_plate_init;
}

::std::ostream&
operator<< (::std::ostream& o, EnumFilterBool::Value i)
{
  return o << EnumFilterBool::_xsd_EnumFilterBool_literals_[i];
}

::std::ostream&
operator<< (::std::ostream& o, const EnumFilterBool& i)
{
  return o << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::std_ostream_initializer< 0, char, EnumFilterBool >
_xsd_EnumFilterBool_std_ostream_init;

::std::ostream&
operator<< (::std::ostream& o, EnumTrueFalse::Value i)
{
  return o << EnumTrueFalse::_xsd_EnumTrueFalse_literals_[i];
}

::std::ostream&
operator<< (::std::ostream& o, const EnumTrueFalse& i)
{
  return o << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::std_ostream_initializer< 0, char, EnumTrueFalse >
_xsd_EnumTrueFalse_std_ostream_init;

::std::ostream&
operator<< (::std::ostream& o, EnumFilterFileType::Value i)
{
  return o << EnumFilterFileType::_xsd_EnumFilterFileType_literals_[i];
}

::std::ostream&
operator<< (::std::ostream& o, const EnumFilterFileType& i)
{
  return o << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::std_ostream_initializer< 0, char, EnumFilterFileType >
_xsd_EnumFilterFileType_std_ostream_init;

::std::ostream&
operator<< (::std::ostream& o, const IFilter& i)
{
  o << ::std::endl << "bool: " << i.bool_ ();
  o << ::std::endl << "not: " << i.not_ ();
  if (i.hidden ())
  {
    o << ::std::endl << "hidden: " << *i.hidden ();
  }

  return o;
}

::std::ostream&
operator<< (::std::ostream& o, const FilterFile& i)
{
  o << static_cast< const ::IFilter& > (i);

  o << ::std::endl << "gte: " << i.gte ();
  o << ::std::endl << "lte: " << i.lte ();
  if (i.min ())
  {
    o << ::std::endl << "min: " << *i.min ();
  }

  if (i.max ())
  {
    o << ::std::endl << "max: " << *i.max ();
  }

  o << ::std::endl << "path: " << i.path ();
  o << ::std::endl << "type: " << i.type ();
  o << ::std::endl << "folder: " << i.folder ();
  return o;
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

::std::unique_ptr< ::FilterFile >
FilterFile_ (const ::std::string& u,
             ::xml_schema::Flags f,
             const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  return ::std::unique_ptr< ::FilterFile > (
    ::FilterFile_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::FilterFile >
FilterFile_ (const ::std::string& u,
             ::xml_schema::ErrorHandler& h,
             ::xml_schema::Flags f,
             const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::FilterFile > (
    ::FilterFile_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::FilterFile >
FilterFile_ (const ::std::string& u,
             ::xercesc::DOMErrorHandler& h,
             ::xml_schema::Flags f,
             const ::xml_schema::Properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::FilterFile > (
    ::FilterFile_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::FilterFile >
FilterFile_ (::std::istream& is,
             ::xml_schema::Flags f,
             const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::FilterFile_ (isrc, f, p);
}

::std::unique_ptr< ::FilterFile >
FilterFile_ (::std::istream& is,
             ::xml_schema::ErrorHandler& h,
             ::xml_schema::Flags f,
             const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::FilterFile_ (isrc, h, f, p);
}

::std::unique_ptr< ::FilterFile >
FilterFile_ (::std::istream& is,
             ::xercesc::DOMErrorHandler& h,
             ::xml_schema::Flags f,
             const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::FilterFile_ (isrc, h, f, p);
}

::std::unique_ptr< ::FilterFile >
FilterFile_ (::std::istream& is,
             const ::std::string& sid,
             ::xml_schema::Flags f,
             const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::FilterFile_ (isrc, f, p);
}

::std::unique_ptr< ::FilterFile >
FilterFile_ (::std::istream& is,
             const ::std::string& sid,
             ::xml_schema::ErrorHandler& h,
             ::xml_schema::Flags f,
             const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::FilterFile_ (isrc, h, f, p);
}

::std::unique_ptr< ::FilterFile >
FilterFile_ (::std::istream& is,
             const ::std::string& sid,
             ::xercesc::DOMErrorHandler& h,
             ::xml_schema::Flags f,
             const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::FilterFile_ (isrc, h, f, p);
}

::std::unique_ptr< ::FilterFile >
FilterFile_ (::xercesc::InputSource& i,
             ::xml_schema::Flags f,
             const ::xml_schema::Properties& p)
{
  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  return ::std::unique_ptr< ::FilterFile > (
    ::FilterFile_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::FilterFile >
FilterFile_ (::xercesc::InputSource& i,
             ::xml_schema::ErrorHandler& h,
             ::xml_schema::Flags f,
             const ::xml_schema::Properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::FilterFile > (
    ::FilterFile_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::FilterFile >
FilterFile_ (::xercesc::InputSource& i,
             ::xercesc::DOMErrorHandler& h,
             ::xml_schema::Flags f,
             const ::xml_schema::Properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::FilterFile > (
    ::FilterFile_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::FilterFile >
FilterFile_ (const ::xercesc::DOMDocument& doc,
             ::xml_schema::Flags f,
             const ::xml_schema::Properties& p)
{
  if (f & ::xml_schema::Flags::keep_dom)
  {
    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      static_cast< ::xercesc::DOMDocument* > (doc.cloneNode (true)));

    return ::std::unique_ptr< ::FilterFile > (
      ::FilterFile_ (
        std::move (d), f | ::xml_schema::Flags::own_dom, p));
  }

  const ::xercesc::DOMElement& e (*doc.getDocumentElement ());
  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (n.name () == "FilterFile" &&
      n.namespace_ () == "")
  {
    ::std::unique_ptr< ::FilterFile > r (
      ::xsd::cxx::tree::traits< ::FilterFile, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "FilterFile",
    "");
}

::std::unique_ptr< ::FilterFile >
FilterFile_ (::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d,
             ::xml_schema::Flags f,
             const ::xml_schema::Properties&)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > c (
    ((f & ::xml_schema::Flags::keep_dom) &&
     !(f & ::xml_schema::Flags::own_dom))
    ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
    : 0);

  ::xercesc::DOMDocument& doc (c.get () ? *c : *d);
  const ::xercesc::DOMElement& e (*doc.getDocumentElement ());

  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (f & ::xml_schema::Flags::keep_dom)
    doc.setUserData (::xml_schema::dom::tree_node_key,
                     (c.get () ? &c : &d),
                     0);

  if (n.name () == "FilterFile" &&
      n.namespace_ () == "")
  {
    ::std::unique_ptr< ::FilterFile > r (
      ::xsd::cxx::tree::traits< ::FilterFile, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "FilterFile",
    "");
}

#include <ostream>
#include <xsd/cxx/tree/error-handler.hxx>
#include <xsd/cxx/xml/dom/serialization-source.hxx>

#include <xsd/cxx/tree/type-serializer-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_serializer_plate< 0, char >
  type_serializer_plate_init;
}

void
operator<< (::xercesc::DOMElement& e, const EnumFilterBool& i)
{
  e << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xercesc::DOMAttr& a, const EnumFilterBool& i)
{
  a << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xml_schema::ListStream& l,
            const EnumFilterBool& i)
{
  l << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::type_serializer_initializer< 0, char, EnumFilterBool >
_xsd_EnumFilterBool_type_serializer_init (
  "enumFilterBool",
  "");


void
operator<< (::xercesc::DOMElement& e, const EnumTrueFalse& i)
{
  e << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xercesc::DOMAttr& a, const EnumTrueFalse& i)
{
  a << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xml_schema::ListStream& l,
            const EnumTrueFalse& i)
{
  l << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::type_serializer_initializer< 0, char, EnumTrueFalse >
_xsd_EnumTrueFalse_type_serializer_init (
  "enumTrueFalse",
  "");


void
operator<< (::xercesc::DOMElement& e, const EnumFilterFileType& i)
{
  e << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xercesc::DOMAttr& a, const EnumFilterFileType& i)
{
  a << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xml_schema::ListStream& l,
            const EnumFilterFileType& i)
{
  l << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::type_serializer_initializer< 0, char, EnumFilterFileType >
_xsd_EnumFilterFileType_type_serializer_init (
  "enumFilterFileType",
  "");


void
operator<< (::xercesc::DOMElement& e, const IFilter& i)
{
  e << static_cast< const ::xml_schema::Type& > (i);

  // bool
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "bool",
        e));

    a << i.bool_ ();
  }

  // not
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "not",
        e));

    a << i.not_ ();
  }

  // hidden
  //
  if (i.hidden ())
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "hidden",
        e));

    a << *i.hidden ();
  }
}

void
FilterFile_ (::std::ostream& o,
             const ::FilterFile& s,
             const ::xml_schema::NamespaceInfomap& m,
             const ::std::string& e,
             ::xml_schema::Flags f)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0);

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::FilterFile_ (s, m, f));

  ::xsd::cxx::tree::error_handler< char > h;

  ::xsd::cxx::xml::dom::ostream_format_target t (o);
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
  }
}

void
FilterFile_ (::std::ostream& o,
             const ::FilterFile& s,
             ::xml_schema::ErrorHandler& h,
             const ::xml_schema::NamespaceInfomap& m,
             const ::std::string& e,
             ::xml_schema::Flags f)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0);

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::FilterFile_ (s, m, f));
  ::xsd::cxx::xml::dom::ostream_format_target t (o);
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
FilterFile_ (::std::ostream& o,
             const ::FilterFile& s,
             ::xercesc::DOMErrorHandler& h,
             const ::xml_schema::NamespaceInfomap& m,
             const ::std::string& e,
             ::xml_schema::Flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::FilterFile_ (s, m, f));
  ::xsd::cxx::xml::dom::ostream_format_target t (o);
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
FilterFile_ (::xercesc::XMLFormatTarget& t,
             const ::FilterFile& s,
             const ::xml_schema::NamespaceInfomap& m,
             const ::std::string& e,
             ::xml_schema::Flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::FilterFile_ (s, m, f));

  ::xsd::cxx::tree::error_handler< char > h;

  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
  }
}

void
FilterFile_ (::xercesc::XMLFormatTarget& t,
             const ::FilterFile& s,
             ::xml_schema::ErrorHandler& h,
             const ::xml_schema::NamespaceInfomap& m,
             const ::std::string& e,
             ::xml_schema::Flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::FilterFile_ (s, m, f));
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
FilterFile_ (::xercesc::XMLFormatTarget& t,
             const ::FilterFile& s,
             ::xercesc::DOMErrorHandler& h,
             const ::xml_schema::NamespaceInfomap& m,
             const ::std::string& e,
             ::xml_schema::Flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::FilterFile_ (s, m, f));
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
FilterFile_ (::xercesc::DOMDocument& d,
             const ::FilterFile& s,
             ::xml_schema::Flags)
{
  ::xercesc::DOMElement& e (*d.getDocumentElement ());
  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (n.name () == "FilterFile" &&
      n.namespace_ () == "")
  {
    e << s;
  }
  else
  {
    throw ::xsd::cxx::tree::unexpected_element < char > (
      n.name (),
      n.namespace_ (),
      "FilterFile",
      "");
  }
}

::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument >
FilterFile_ (const ::FilterFile& s,
             const ::xml_schema::NamespaceInfomap& m,
             ::xml_schema::Flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::serialize< char > (
      "FilterFile",
      "",
      m, f));

  ::FilterFile_ (*d, s, f);
  return d;
}

void
operator<< (::xercesc::DOMElement& e, const FilterFile& i)
{
  e << static_cast< const ::IFilter& > (i);

  // gte
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "gte",
        e));

    a << i.gte ();
  }

  // lte
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "lte",
        e));

    a << i.lte ();
  }

  // min
  //
  if (i.min ())
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "min",
        e));

    a << *i.min ();
  }

  // max
  //
  if (i.max ())
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "max",
        e));

    a << *i.max ();
  }

  // path
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "path",
        e));

    a << i.path ();
  }

  // type
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "type",
        e));

    a << i.type ();
  }

  // folder
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "folder",
        e));

    a << i.folder ();
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

