// Copyright (c) 2005-2017 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "msischema.h"

// EnumFilterBool
// 

EnumFilterBool::
EnumFilterBool (Value v)
: ::xml_schema::String (_xsd_EnumFilterBool_literals_[v])
{
}

EnumFilterBool::
EnumFilterBool (const char* v)
: ::xml_schema::String (v)
{
}

EnumFilterBool::
EnumFilterBool (const ::std::string& v)
: ::xml_schema::String (v)
{
}

EnumFilterBool::
EnumFilterBool (const ::xml_schema::String& v)
: ::xml_schema::String (v)
{
}

EnumFilterBool::
EnumFilterBool (const EnumFilterBool& v,
                ::xml_schema::Flags f,
                ::xml_schema::Container* c)
: ::xml_schema::String (v, f, c)
{
}

EnumFilterBool& EnumFilterBool::
operator= (Value v)
{
  static_cast< ::xml_schema::String& > (*this) = 
  ::xml_schema::String (_xsd_EnumFilterBool_literals_[v]);

  return *this;
}


// EnumTrueFalse
// 

EnumTrueFalse::
EnumTrueFalse (Value v)
: ::xml_schema::String (_xsd_EnumTrueFalse_literals_[v])
{
}

EnumTrueFalse::
EnumTrueFalse (const char* v)
: ::xml_schema::String (v)
{
}

EnumTrueFalse::
EnumTrueFalse (const ::std::string& v)
: ::xml_schema::String (v)
{
}

EnumTrueFalse::
EnumTrueFalse (const ::xml_schema::String& v)
: ::xml_schema::String (v)
{
}

EnumTrueFalse::
EnumTrueFalse (const EnumTrueFalse& v,
               ::xml_schema::Flags f,
               ::xml_schema::Container* c)
: ::xml_schema::String (v, f, c)
{
}

EnumTrueFalse& EnumTrueFalse::
operator= (Value v)
{
  static_cast< ::xml_schema::String& > (*this) = 
  ::xml_schema::String (_xsd_EnumTrueFalse_literals_[v]);

  return *this;
}


// EnumFilterMsiType
// 

EnumFilterMsiType::
EnumFilterMsiType (Value v)
: ::xml_schema::String (_xsd_EnumFilterMsiType_literals_[v])
{
}

EnumFilterMsiType::
EnumFilterMsiType (const char* v)
: ::xml_schema::String (v)
{
}

EnumFilterMsiType::
EnumFilterMsiType (const ::std::string& v)
: ::xml_schema::String (v)
{
}

EnumFilterMsiType::
EnumFilterMsiType (const ::xml_schema::String& v)
: ::xml_schema::String (v)
{
}

EnumFilterMsiType::
EnumFilterMsiType (const EnumFilterMsiType& v,
                   ::xml_schema::Flags f,
                   ::xml_schema::Container* c)
: ::xml_schema::String (v, f, c)
{
}

EnumFilterMsiType& EnumFilterMsiType::
operator= (Value v)
{
  static_cast< ::xml_schema::String& > (*this) = 
  ::xml_schema::String (_xsd_EnumFilterMsiType_literals_[v]);

  return *this;
}


// EnumFilterMsiSubType
// 

EnumFilterMsiSubType::
EnumFilterMsiSubType (Value v)
: ::xml_schema::String (_xsd_EnumFilterMsiSubType_literals_[v])
{
}

EnumFilterMsiSubType::
EnumFilterMsiSubType (const char* v)
: ::xml_schema::String (v)
{
}

EnumFilterMsiSubType::
EnumFilterMsiSubType (const ::std::string& v)
: ::xml_schema::String (v)
{
}

EnumFilterMsiSubType::
EnumFilterMsiSubType (const ::xml_schema::String& v)
: ::xml_schema::String (v)
{
}

EnumFilterMsiSubType::
EnumFilterMsiSubType (const EnumFilterMsiSubType& v,
                      ::xml_schema::Flags f,
                      ::xml_schema::Container* c)
: ::xml_schema::String (v, f, c)
{
}

EnumFilterMsiSubType& EnumFilterMsiSubType::
operator= (Value v)
{
  static_cast< ::xml_schema::String& > (*this) = 
  ::xml_schema::String (_xsd_EnumFilterMsiSubType_literals_[v]);

  return *this;
}


// IFilter
// 

const IFilter::BoolType& IFilter::
bool_ () const
{
  return this->bool__.get ();
}

IFilter::BoolType& IFilter::
bool_ ()
{
  return this->bool__.get ();
}

void IFilter::
bool_ (const BoolType& x)
{
  this->bool__.set (x);
}

void IFilter::
bool_ (::std::unique_ptr< BoolType > x)
{
  this->bool__.set (std::move (x));
}

const IFilter::NotType& IFilter::
not_ () const
{
  return this->not__.get ();
}

IFilter::NotType& IFilter::
not_ ()
{
  return this->not__.get ();
}

void IFilter::
not_ (const NotType& x)
{
  this->not__.set (x);
}

void IFilter::
not_ (::std::unique_ptr< NotType > x)
{
  this->not__.set (std::move (x));
}

const IFilter::HiddenOptional& IFilter::
hidden () const
{
  return this->hidden_;
}

IFilter::HiddenOptional& IFilter::
hidden ()
{
  return this->hidden_;
}

void IFilter::
hidden (const HiddenType& x)
{
  this->hidden_.set (x);
}

void IFilter::
hidden (const HiddenOptional& x)
{
  this->hidden_ = x;
}

void IFilter::
hidden (::std::unique_ptr< HiddenType > x)
{
  this->hidden_.set (std::move (x));
}


// FilterMsi
// 

const FilterMsi::TypeType& FilterMsi::
type () const
{
  return this->type_.get ();
}

FilterMsi::TypeType& FilterMsi::
type ()
{
  return this->type_.get ();
}

void FilterMsi::
type (const TypeType& x)
{
  this->type_.set (x);
}

void FilterMsi::
type (::std::unique_ptr< TypeType > x)
{
  this->type_.set (std::move (x));
}

const FilterMsi::SubtypeType& FilterMsi::
subtype () const
{
  return this->subtype_.get ();
}

FilterMsi::SubtypeType& FilterMsi::
subtype ()
{
  return this->subtype_.get ();
}

void FilterMsi::
subtype (const SubtypeType& x)
{
  this->subtype_.set (x);
}

void FilterMsi::
subtype (::std::unique_ptr< SubtypeType > x)
{
  this->subtype_.set (std::move (x));
}

const FilterMsi::CodeOptional& FilterMsi::
code () const
{
  return this->code_;
}

FilterMsi::CodeOptional& FilterMsi::
code ()
{
  return this->code_;
}

void FilterMsi::
code (const CodeType& x)
{
  this->code_.set (x);
}

void FilterMsi::
code (const CodeOptional& x)
{
  this->code_ = x;
}

void FilterMsi::
code (::std::unique_ptr< CodeType > x)
{
  this->code_.set (std::move (x));
}

const FilterMsi::ItemOptional& FilterMsi::
item () const
{
  return this->item_;
}

FilterMsi::ItemOptional& FilterMsi::
item ()
{
  return this->item_;
}

void FilterMsi::
item (const ItemType& x)
{
  this->item_.set (x);
}

void FilterMsi::
item (const ItemOptional& x)
{
  this->item_ = x;
}

void FilterMsi::
item (::std::unique_ptr< ItemType > x)
{
  this->item_.set (std::move (x));
}

const FilterMsi::ValueOptional& FilterMsi::
value () const
{
  return this->value_;
}

FilterMsi::ValueOptional& FilterMsi::
value ()
{
  return this->value_;
}

void FilterMsi::
value (const ValueType& x)
{
  this->value_.set (x);
}

void FilterMsi::
value (const ValueOptional& x)
{
  this->value_ = x;
}

void FilterMsi::
value (::std::unique_ptr< ValueType > x)
{
  this->value_.set (std::move (x));
}

const FilterMsi::MinOptional& FilterMsi::
min () const
{
  return this->min_;
}

FilterMsi::MinOptional& FilterMsi::
min ()
{
  return this->min_;
}

void FilterMsi::
min (const MinType& x)
{
  this->min_.set (x);
}

void FilterMsi::
min (const MinOptional& x)
{
  this->min_ = x;
}

void FilterMsi::
min (::std::unique_ptr< MinType > x)
{
  this->min_.set (std::move (x));
}

const FilterMsi::MaxOptional& FilterMsi::
max () const
{
  return this->max_;
}

FilterMsi::MaxOptional& FilterMsi::
max ()
{
  return this->max_;
}

void FilterMsi::
max (const MaxType& x)
{
  this->max_.set (x);
}

void FilterMsi::
max (const MaxOptional& x)
{
  this->max_ = x;
}

void FilterMsi::
max (::std::unique_ptr< MaxType > x)
{
  this->max_.set (std::move (x));
}

const FilterMsi::GteType& FilterMsi::
gte () const
{
  return this->gte_.get ();
}

FilterMsi::GteType& FilterMsi::
gte ()
{
  return this->gte_.get ();
}

void FilterMsi::
gte (const GteType& x)
{
  this->gte_.set (x);
}

void FilterMsi::
gte (::std::unique_ptr< GteType > x)
{
  this->gte_.set (std::move (x));
}

const FilterMsi::GteType& FilterMsi::
gte_default_value ()
{
  return gte_default_value_;
}

const FilterMsi::LteType& FilterMsi::
lte () const
{
  return this->lte_.get ();
}

FilterMsi::LteType& FilterMsi::
lte ()
{
  return this->lte_.get ();
}

void FilterMsi::
lte (const LteType& x)
{
  this->lte_.set (x);
}

void FilterMsi::
lte (::std::unique_ptr< LteType > x)
{
  this->lte_.set (std::move (x));
}

const FilterMsi::LteType& FilterMsi::
lte_default_value ()
{
  return lte_default_value_;
}


#include <xsd/cxx/xml/dom/wildcard-source.hxx>

#include <xsd/cxx/xml/dom/parsing-source.hxx>

#include <xsd/cxx/tree/type-factory-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_factory_plate< 0, char >
  type_factory_plate_init;
}

// EnumFilterBool
//

EnumFilterBool::
EnumFilterBool (const ::xercesc::DOMElement& e,
                ::xml_schema::Flags f,
                ::xml_schema::Container* c)
: ::xml_schema::String (e, f, c)
{
  _xsd_EnumFilterBool_convert ();
}

EnumFilterBool::
EnumFilterBool (const ::xercesc::DOMAttr& a,
                ::xml_schema::Flags f,
                ::xml_schema::Container* c)
: ::xml_schema::String (a, f, c)
{
  _xsd_EnumFilterBool_convert ();
}

EnumFilterBool::
EnumFilterBool (const ::std::string& s,
                const ::xercesc::DOMElement* e,
                ::xml_schema::Flags f,
                ::xml_schema::Container* c)
: ::xml_schema::String (s, e, f, c)
{
  _xsd_EnumFilterBool_convert ();
}

EnumFilterBool* EnumFilterBool::
_clone (::xml_schema::Flags f,
        ::xml_schema::Container* c) const
{
  return new class EnumFilterBool (*this, f, c);
}

EnumFilterBool::Value EnumFilterBool::
_xsd_EnumFilterBool_convert () const
{
  ::xsd::cxx::tree::enum_comparator< char > c (_xsd_EnumFilterBool_literals_);
  const Value* i (::std::lower_bound (
                    _xsd_EnumFilterBool_indexes_,
                    _xsd_EnumFilterBool_indexes_ + 2,
                    *this,
                    c));

  if (i == _xsd_EnumFilterBool_indexes_ + 2 || _xsd_EnumFilterBool_literals_[*i] != *this)
  {
    throw ::xsd::cxx::tree::unexpected_enumerator < char > (*this);
  }

  return *i;
}

const char* const EnumFilterBool::
_xsd_EnumFilterBool_literals_[2] =
{
  "AND",
  "OR"
};

const EnumFilterBool::Value EnumFilterBool::
_xsd_EnumFilterBool_indexes_[2] =
{
  ::EnumFilterBool::AND,
  ::EnumFilterBool::OR
};

static
const ::xsd::cxx::tree::type_factory_initializer< 0, char, EnumFilterBool >
_xsd_EnumFilterBool_type_factory_init (
  "enumFilterBool",
  "");

// EnumTrueFalse
//

EnumTrueFalse::
EnumTrueFalse (const ::xercesc::DOMElement& e,
               ::xml_schema::Flags f,
               ::xml_schema::Container* c)
: ::xml_schema::String (e, f, c)
{
  _xsd_EnumTrueFalse_convert ();
}

EnumTrueFalse::
EnumTrueFalse (const ::xercesc::DOMAttr& a,
               ::xml_schema::Flags f,
               ::xml_schema::Container* c)
: ::xml_schema::String (a, f, c)
{
  _xsd_EnumTrueFalse_convert ();
}

EnumTrueFalse::
EnumTrueFalse (const ::std::string& s,
               const ::xercesc::DOMElement* e,
               ::xml_schema::Flags f,
               ::xml_schema::Container* c)
: ::xml_schema::String (s, e, f, c)
{
  _xsd_EnumTrueFalse_convert ();
}

EnumTrueFalse* EnumTrueFalse::
_clone (::xml_schema::Flags f,
        ::xml_schema::Container* c) const
{
  return new class EnumTrueFalse (*this, f, c);
}

EnumTrueFalse::Value EnumTrueFalse::
_xsd_EnumTrueFalse_convert () const
{
  ::xsd::cxx::tree::enum_comparator< char > c (_xsd_EnumTrueFalse_literals_);
  const Value* i (::std::lower_bound (
                    _xsd_EnumTrueFalse_indexes_,
                    _xsd_EnumTrueFalse_indexes_ + 2,
                    *this,
                    c));

  if (i == _xsd_EnumTrueFalse_indexes_ + 2 || _xsd_EnumTrueFalse_literals_[*i] != *this)
  {
    throw ::xsd::cxx::tree::unexpected_enumerator < char > (*this);
  }

  return *i;
}

const char* const EnumTrueFalse::
_xsd_EnumTrueFalse_literals_[2] =
{
  "0",
  "1"
};

const EnumTrueFalse::Value EnumTrueFalse::
_xsd_EnumTrueFalse_indexes_[2] =
{
  ::EnumTrueFalse::cxx_0,
  ::EnumTrueFalse::cxx_1
};

static
const ::xsd::cxx::tree::type_factory_initializer< 0, char, EnumTrueFalse >
_xsd_EnumTrueFalse_type_factory_init (
  "enumTrueFalse",
  "");

// EnumFilterMsiType
//

EnumFilterMsiType::
EnumFilterMsiType (const ::xercesc::DOMElement& e,
                   ::xml_schema::Flags f,
                   ::xml_schema::Container* c)
: ::xml_schema::String (e, f, c)
{
  _xsd_EnumFilterMsiType_convert ();
}

EnumFilterMsiType::
EnumFilterMsiType (const ::xercesc::DOMAttr& a,
                   ::xml_schema::Flags f,
                   ::xml_schema::Container* c)
: ::xml_schema::String (a, f, c)
{
  _xsd_EnumFilterMsiType_convert ();
}

EnumFilterMsiType::
EnumFilterMsiType (const ::std::string& s,
                   const ::xercesc::DOMElement* e,
                   ::xml_schema::Flags f,
                   ::xml_schema::Container* c)
: ::xml_schema::String (s, e, f, c)
{
  _xsd_EnumFilterMsiType_convert ();
}

EnumFilterMsiType* EnumFilterMsiType::
_clone (::xml_schema::Flags f,
        ::xml_schema::Container* c) const
{
  return new class EnumFilterMsiType (*this, f, c);
}

EnumFilterMsiType::Value EnumFilterMsiType::
_xsd_EnumFilterMsiType_convert () const
{
  ::xsd::cxx::tree::enum_comparator< char > c (_xsd_EnumFilterMsiType_literals_);
  const Value* i (::std::lower_bound (
                    _xsd_EnumFilterMsiType_indexes_,
                    _xsd_EnumFilterMsiType_indexes_ + 3,
                    *this,
                    c));

  if (i == _xsd_EnumFilterMsiType_indexes_ + 3 || _xsd_EnumFilterMsiType_literals_[*i] != *this)
  {
    throw ::xsd::cxx::tree::unexpected_enumerator < char > (*this);
  }

  return *i;
}

const char* const EnumFilterMsiType::
_xsd_EnumFilterMsiType_literals_[3] =
{
  "PRODUCT",
  "PATCH",
  "FILECOMPONENT"
};

const EnumFilterMsiType::Value EnumFilterMsiType::
_xsd_EnumFilterMsiType_indexes_[3] =
{
  ::EnumFilterMsiType::FILECOMPONENT,
  ::EnumFilterMsiType::PATCH,
  ::EnumFilterMsiType::PRODUCT
};

static
const ::xsd::cxx::tree::type_factory_initializer< 0, char, EnumFilterMsiType >
_xsd_EnumFilterMsiType_type_factory_init (
  "enumFilterMsiType",
  "");

// EnumFilterMsiSubType
//

EnumFilterMsiSubType::
EnumFilterMsiSubType (const ::xercesc::DOMElement& e,
                      ::xml_schema::Flags f,
                      ::xml_schema::Container* c)
: ::xml_schema::String (e, f, c)
{
  _xsd_EnumFilterMsiSubType_convert ();
}

EnumFilterMsiSubType::
EnumFilterMsiSubType (const ::xercesc::DOMAttr& a,
                      ::xml_schema::Flags f,
                      ::xml_schema::Container* c)
: ::xml_schema::String (a, f, c)
{
  _xsd_EnumFilterMsiSubType_convert ();
}

EnumFilterMsiSubType::
EnumFilterMsiSubType (const ::std::string& s,
                      const ::xercesc::DOMElement* e,
                      ::xml_schema::Flags f,
                      ::xml_schema::Container* c)
: ::xml_schema::String (s, e, f, c)
{
  _xsd_EnumFilterMsiSubType_convert ();
}

EnumFilterMsiSubType* EnumFilterMsiSubType::
_clone (::xml_schema::Flags f,
        ::xml_schema::Container* c) const
{
  return new class EnumFilterMsiSubType (*this, f, c);
}

EnumFilterMsiSubType::Value EnumFilterMsiSubType::
_xsd_EnumFilterMsiSubType_convert () const
{
  ::xsd::cxx::tree::enum_comparator< char > c (_xsd_EnumFilterMsiSubType_literals_);
  const Value* i (::std::lower_bound (
                    _xsd_EnumFilterMsiSubType_indexes_,
                    _xsd_EnumFilterMsiSubType_indexes_ + 6,
                    *this,
                    c));

  if (i == _xsd_EnumFilterMsiSubType_indexes_ + 6 || _xsd_EnumFilterMsiSubType_literals_[*i] != *this)
  {
    throw ::xsd::cxx::tree::unexpected_enumerator < char > (*this);
  }

  return *i;
}

const char* const EnumFilterMsiSubType::
_xsd_EnumFilterMsiSubType_literals_[6] =
{
  "EXISTS",
  "VERSION",
  "GET_PROPERTY",
  "GET_INFORMATION",
  "MATCH_PROPERTY",
  "MATCH_INFORMATION"
};

const EnumFilterMsiSubType::Value EnumFilterMsiSubType::
_xsd_EnumFilterMsiSubType_indexes_[6] =
{
  ::EnumFilterMsiSubType::EXISTS,
  ::EnumFilterMsiSubType::GET_INFORMATION,
  ::EnumFilterMsiSubType::GET_PROPERTY,
  ::EnumFilterMsiSubType::MATCH_INFORMATION,
  ::EnumFilterMsiSubType::MATCH_PROPERTY,
  ::EnumFilterMsiSubType::VERSION
};

static
const ::xsd::cxx::tree::type_factory_initializer< 0, char, EnumFilterMsiSubType >
_xsd_EnumFilterMsiSubType_type_factory_init (
  "enumFilterMsiSubType",
  "");

// IFilter
//

IFilter::
IFilter (const BoolType& bool_,
         const NotType& not_)
: ::xml_schema::Type (),
  bool__ (bool_, this),
  not__ (not_, this),
  hidden_ (this)
{
}

IFilter::
IFilter (const IFilter& x,
         ::xml_schema::Flags f,
         ::xml_schema::Container* c)
: ::xml_schema::Type (x, f, c),
  bool__ (x.bool__, f, this),
  not__ (x.not__, f, this),
  hidden_ (x.hidden_, f, this)
{
}

IFilter::
IFilter (const ::xercesc::DOMElement& e,
         ::xml_schema::Flags f,
         ::xml_schema::Container* c)
: ::xml_schema::Type (e, f | ::xml_schema::Flags::base, c),
  bool__ (this),
  not__ (this),
  hidden_ (this)
{
  if ((f & ::xml_schema::Flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, false, false, true);
    this->parse (p, f);
  }
}

void IFilter::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::Flags f)
{
  while (p.more_attributes ())
  {
    const ::xercesc::DOMAttr& i (p.next_attribute ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    if (n.name () == "bool" && n.namespace_ ().empty ())
    {
      this->bool__.set (BoolTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "not" && n.namespace_ ().empty ())
    {
      this->not__.set (NotTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "hidden" && n.namespace_ ().empty ())
    {
      this->hidden_.set (HiddenTraits::create (i, f, this));
      continue;
    }
  }

  if (!bool__.present ())
  {
    throw ::xsd::cxx::tree::expected_attribute< char > (
      "bool",
      "");
  }

  if (!not__.present ())
  {
    throw ::xsd::cxx::tree::expected_attribute< char > (
      "not",
      "");
  }
}

IFilter& IFilter::
operator= (const IFilter& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::Type& > (*this) = x;
    this->bool__ = x.bool__;
    this->not__ = x.not__;
    this->hidden_ = x.hidden_;
  }

  return *this;
}

IFilter::
~IFilter ()
{
}

// FilterMsi
//

const FilterMsi::GteType FilterMsi::gte_default_value_ (
  "0");

const FilterMsi::LteType FilterMsi::lte_default_value_ (
  "0");

FilterMsi::
FilterMsi (const BoolType& bool_,
           const NotType& not_,
           const TypeType& type,
           const SubtypeType& subtype)
: ::IFilter (bool_,
             not_),
  type_ (type, this),
  subtype_ (subtype, this),
  code_ (this),
  item_ (this),
  value_ (this),
  min_ (this),
  max_ (this),
  gte_ (gte_default_value (), this),
  lte_ (lte_default_value (), this)
{
}

FilterMsi::
FilterMsi (const FilterMsi& x,
           ::xml_schema::Flags f,
           ::xml_schema::Container* c)
: ::IFilter (x, f, c),
  type_ (x.type_, f, this),
  subtype_ (x.subtype_, f, this),
  code_ (x.code_, f, this),
  item_ (x.item_, f, this),
  value_ (x.value_, f, this),
  min_ (x.min_, f, this),
  max_ (x.max_, f, this),
  gte_ (x.gte_, f, this),
  lte_ (x.lte_, f, this)
{
}

FilterMsi::
FilterMsi (const ::xercesc::DOMElement& e,
           ::xml_schema::Flags f,
           ::xml_schema::Container* c)
: ::IFilter (e, f | ::xml_schema::Flags::base, c),
  type_ (this),
  subtype_ (this),
  code_ (this),
  item_ (this),
  value_ (this),
  min_ (this),
  max_ (this),
  gte_ (this),
  lte_ (this)
{
  if ((f & ::xml_schema::Flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, false, false, true);
    this->parse (p, f);
  }
}

void FilterMsi::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::Flags f)
{
  this->::IFilter::parse (p, f);

  p.reset_attributes ();

  while (p.more_attributes ())
  {
    const ::xercesc::DOMAttr& i (p.next_attribute ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    if (n.name () == "type" && n.namespace_ ().empty ())
    {
      this->type_.set (TypeTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "subtype" && n.namespace_ ().empty ())
    {
      this->subtype_.set (SubtypeTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "code" && n.namespace_ ().empty ())
    {
      this->code_.set (CodeTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "item" && n.namespace_ ().empty ())
    {
      this->item_.set (ItemTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "value" && n.namespace_ ().empty ())
    {
      this->value_.set (ValueTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "min" && n.namespace_ ().empty ())
    {
      this->min_.set (MinTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "max" && n.namespace_ ().empty ())
    {
      this->max_.set (MaxTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "gte" && n.namespace_ ().empty ())
    {
      this->gte_.set (GteTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "lte" && n.namespace_ ().empty ())
    {
      this->lte_.set (LteTraits::create (i, f, this));
      continue;
    }
  }

  if (!type_.present ())
  {
    throw ::xsd::cxx::tree::expected_attribute< char > (
      "type",
      "");
  }

  if (!subtype_.present ())
  {
    throw ::xsd::cxx::tree::expected_attribute< char > (
      "subtype",
      "");
  }

  if (!gte_.present ())
  {
    this->gte_.set (gte_default_value ());
  }

  if (!lte_.present ())
  {
    this->lte_.set (lte_default_value ());
  }
}

FilterMsi* FilterMsi::
_clone (::xml_schema::Flags f,
        ::xml_schema::Container* c) const
{
  return new class FilterMsi (*this, f, c);
}

FilterMsi& FilterMsi::
operator= (const FilterMsi& x)
{
  if (this != &x)
  {
    static_cast< ::IFilter& > (*this) = x;
    this->type_ = x.type_;
    this->subtype_ = x.subtype_;
    this->code_ = x.code_;
    this->item_ = x.item_;
    this->value_ = x.value_;
    this->min_ = x.min_;
    this->max_ = x.max_;
    this->gte_ = x.gte_;
    this->lte_ = x.lte_;
  }

  return *this;
}

FilterMsi::
~FilterMsi ()
{
}

#include <ostream>

#include <xsd/cxx/tree/std-ostream-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::std_ostream_plate< 0, char >
  std_ostream_plate_init;
}

::std::ostream&
operator<< (::std::ostream& o, EnumFilterBool::Value i)
{
  return o << EnumFilterBool::_xsd_EnumFilterBool_literals_[i];
}

::std::ostream&
operator<< (::std::ostream& o, const EnumFilterBool& i)
{
  return o << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::std_ostream_initializer< 0, char, EnumFilterBool >
_xsd_EnumFilterBool_std_ostream_init;

::std::ostream&
operator<< (::std::ostream& o, EnumTrueFalse::Value i)
{
  return o << EnumTrueFalse::_xsd_EnumTrueFalse_literals_[i];
}

::std::ostream&
operator<< (::std::ostream& o, const EnumTrueFalse& i)
{
  return o << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::std_ostream_initializer< 0, char, EnumTrueFalse >
_xsd_EnumTrueFalse_std_ostream_init;

::std::ostream&
operator<< (::std::ostream& o, EnumFilterMsiType::Value i)
{
  return o << EnumFilterMsiType::_xsd_EnumFilterMsiType_literals_[i];
}

::std::ostream&
operator<< (::std::ostream& o, const EnumFilterMsiType& i)
{
  return o << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::std_ostream_initializer< 0, char, EnumFilterMsiType >
_xsd_EnumFilterMsiType_std_ostream_init;

::std::ostream&
operator<< (::std::ostream& o, EnumFilterMsiSubType::Value i)
{
  return o << EnumFilterMsiSubType::_xsd_EnumFilterMsiSubType_literals_[i];
}

::std::ostream&
operator<< (::std::ostream& o, const EnumFilterMsiSubType& i)
{
  return o << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::std_ostream_initializer< 0, char, EnumFilterMsiSubType >
_xsd_EnumFilterMsiSubType_std_ostream_init;

::std::ostream&
operator<< (::std::ostream& o, const IFilter& i)
{
  o << ::std::endl << "bool: " << i.bool_ ();
  o << ::std::endl << "not: " << i.not_ ();
  if (i.hidden ())
  {
    o << ::std::endl << "hidden: " << *i.hidden ();
  }

  return o;
}

::std::ostream&
operator<< (::std::ostream& o, const FilterMsi& i)
{
  o << static_cast< const ::IFilter& > (i);

  o << ::std::endl << "type: " << i.type ();
  o << ::std::endl << "subtype: " << i.subtype ();
  if (i.code ())
  {
    o << ::std::endl << "code: " << *i.code ();
  }

  if (i.item ())
  {
    o << ::std::endl << "item: " << *i.item ();
  }

  if (i.value ())
  {
    o << ::std::endl << "value: " << *i.value ();
  }

  if (i.min ())
  {
    o << ::std::endl << "min: " << *i.min ();
  }

  if (i.max ())
  {
    o << ::std::endl << "max: " << *i.max ();
  }

  o << ::std::endl << "gte: " << i.gte ();
  o << ::std::endl << "lte: " << i.lte ();
  return o;
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

::std::unique_ptr< ::FilterMsi >
FilterMsi_ (const ::std::string& u,
            ::xml_schema::Flags f,
            const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  return ::std::unique_ptr< ::FilterMsi > (
    ::FilterMsi_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::FilterMsi >
FilterMsi_ (const ::std::string& u,
            ::xml_schema::ErrorHandler& h,
            ::xml_schema::Flags f,
            const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::FilterMsi > (
    ::FilterMsi_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::FilterMsi >
FilterMsi_ (const ::std::string& u,
            ::xercesc::DOMErrorHandler& h,
            ::xml_schema::Flags f,
            const ::xml_schema::Properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::FilterMsi > (
    ::FilterMsi_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::FilterMsi >
FilterMsi_ (::std::istream& is,
            ::xml_schema::Flags f,
            const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::FilterMsi_ (isrc, f, p);
}

::std::unique_ptr< ::FilterMsi >
FilterMsi_ (::std::istream& is,
            ::xml_schema::ErrorHandler& h,
            ::xml_schema::Flags f,
            const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::FilterMsi_ (isrc, h, f, p);
}

::std::unique_ptr< ::FilterMsi >
FilterMsi_ (::std::istream& is,
            ::xercesc::DOMErrorHandler& h,
            ::xml_schema::Flags f,
            const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::FilterMsi_ (isrc, h, f, p);
}

::std::unique_ptr< ::FilterMsi >
FilterMsi_ (::std::istream& is,
            const ::std::string& sid,
            ::xml_schema::Flags f,
            const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::FilterMsi_ (isrc, f, p);
}

::std::unique_ptr< ::FilterMsi >
FilterMsi_ (::std::istream& is,
            const ::std::string& sid,
            ::xml_schema::ErrorHandler& h,
            ::xml_schema::Flags f,
            const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::FilterMsi_ (isrc, h, f, p);
}

::std::unique_ptr< ::FilterMsi >
FilterMsi_ (::std::istream& is,
            const ::std::string& sid,
            ::xercesc::DOMErrorHandler& h,
            ::xml_schema::Flags f,
            const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::FilterMsi_ (isrc, h, f, p);
}

::std::unique_ptr< ::FilterMsi >
FilterMsi_ (::xercesc::InputSource& i,
            ::xml_schema::Flags f,
            const ::xml_schema::Properties& p)
{
  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  return ::std::unique_ptr< ::FilterMsi > (
    ::FilterMsi_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::FilterMsi >
FilterMsi_ (::xercesc::InputSource& i,
            ::xml_schema::ErrorHandler& h,
            ::xml_schema::Flags f,
            const ::xml_schema::Properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::FilterMsi > (
    ::FilterMsi_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::FilterMsi >
FilterMsi_ (::xercesc::InputSource& i,
            ::xercesc::DOMErrorHandler& h,
            ::xml_schema::Flags f,
            const ::xml_schema::Properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::FilterMsi > (
    ::FilterMsi_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::FilterMsi >
FilterMsi_ (const ::xercesc::DOMDocument& doc,
            ::xml_schema::Flags f,
            const ::xml_schema::Properties& p)
{
  if (f & ::xml_schema::Flags::keep_dom)
  {
    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      static_cast< ::xercesc::DOMDocument* > (doc.cloneNode (true)));

    return ::std::unique_ptr< ::FilterMsi > (
      ::FilterMsi_ (
        std::move (d), f | ::xml_schema::Flags::own_dom, p));
  }

  const ::xercesc::DOMElement& e (*doc.getDocumentElement ());
  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (n.name () == "FilterMsi" &&
      n.namespace_ () == "")
  {
    ::std::unique_ptr< ::FilterMsi > r (
      ::xsd::cxx::tree::traits< ::FilterMsi, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "FilterMsi",
    "");
}

::std::unique_ptr< ::FilterMsi >
FilterMsi_ (::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d,
            ::xml_schema::Flags f,
            const ::xml_schema::Properties&)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > c (
    ((f & ::xml_schema::Flags::keep_dom) &&
     !(f & ::xml_schema::Flags::own_dom))
    ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
    : 0);

  ::xercesc::DOMDocument& doc (c.get () ? *c : *d);
  const ::xercesc::DOMElement& e (*doc.getDocumentElement ());

  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (f & ::xml_schema::Flags::keep_dom)
    doc.setUserData (::xml_schema::dom::tree_node_key,
                     (c.get () ? &c : &d),
                     0);

  if (n.name () == "FilterMsi" &&
      n.namespace_ () == "")
  {
    ::std::unique_ptr< ::FilterMsi > r (
      ::xsd::cxx::tree::traits< ::FilterMsi, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "FilterMsi",
    "");
}

#include <ostream>
#include <xsd/cxx/tree/error-handler.hxx>
#include <xsd/cxx/xml/dom/serialization-source.hxx>

#include <xsd/cxx/tree/type-serializer-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_serializer_plate< 0, char >
  type_serializer_plate_init;
}

void
operator<< (::xercesc::DOMElement& e, const EnumFilterBool& i)
{
  e << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xercesc::DOMAttr& a, const EnumFilterBool& i)
{
  a << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xml_schema::ListStream& l,
            const EnumFilterBool& i)
{
  l << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::type_serializer_initializer< 0, char, EnumFilterBool >
_xsd_EnumFilterBool_type_serializer_init (
  "enumFilterBool",
  "");


void
operator<< (::xercesc::DOMElement& e, const EnumTrueFalse& i)
{
  e << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xercesc::DOMAttr& a, const EnumTrueFalse& i)
{
  a << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xml_schema::ListStream& l,
            const EnumTrueFalse& i)
{
  l << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::type_serializer_initializer< 0, char, EnumTrueFalse >
_xsd_EnumTrueFalse_type_serializer_init (
  "enumTrueFalse",
  "");


void
operator<< (::xercesc::DOMElement& e, const EnumFilterMsiType& i)
{
  e << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xercesc::DOMAttr& a, const EnumFilterMsiType& i)
{
  a << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xml_schema::ListStream& l,
            const EnumFilterMsiType& i)
{
  l << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::type_serializer_initializer< 0, char, EnumFilterMsiType >
_xsd_EnumFilterMsiType_type_serializer_init (
  "enumFilterMsiType",
  "");


void
operator<< (::xercesc::DOMElement& e, const EnumFilterMsiSubType& i)
{
  e << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xercesc::DOMAttr& a, const EnumFilterMsiSubType& i)
{
  a << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xml_schema::ListStream& l,
            const EnumFilterMsiSubType& i)
{
  l << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::type_serializer_initializer< 0, char, EnumFilterMsiSubType >
_xsd_EnumFilterMsiSubType_type_serializer_init (
  "enumFilterMsiSubType",
  "");


void
operator<< (::xercesc::DOMElement& e, const IFilter& i)
{
  e << static_cast< const ::xml_schema::Type& > (i);

  // bool
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "bool",
        e));

    a << i.bool_ ();
  }

  // not
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "not",
        e));

    a << i.not_ ();
  }

  // hidden
  //
  if (i.hidden ())
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "hidden",
        e));

    a << *i.hidden ();
  }
}

void
FilterMsi_ (::std::ostream& o,
            const ::FilterMsi& s,
            const ::xml_schema::NamespaceInfomap& m,
            const ::std::string& e,
            ::xml_schema::Flags f)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0);

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::FilterMsi_ (s, m, f));

  ::xsd::cxx::tree::error_handler< char > h;

  ::xsd::cxx::xml::dom::ostream_format_target t (o);
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
  }
}

void
FilterMsi_ (::std::ostream& o,
            const ::FilterMsi& s,
            ::xml_schema::ErrorHandler& h,
            const ::xml_schema::NamespaceInfomap& m,
            const ::std::string& e,
            ::xml_schema::Flags f)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0);

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::FilterMsi_ (s, m, f));
  ::xsd::cxx::xml::dom::ostream_format_target t (o);
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
FilterMsi_ (::std::ostream& o,
            const ::FilterMsi& s,
            ::xercesc::DOMErrorHandler& h,
            const ::xml_schema::NamespaceInfomap& m,
            const ::std::string& e,
            ::xml_schema::Flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::FilterMsi_ (s, m, f));
  ::xsd::cxx::xml::dom::ostream_format_target t (o);
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
FilterMsi_ (::xercesc::XMLFormatTarget& t,
            const ::FilterMsi& s,
            const ::xml_schema::NamespaceInfomap& m,
            const ::std::string& e,
            ::xml_schema::Flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::FilterMsi_ (s, m, f));

  ::xsd::cxx::tree::error_handler< char > h;

  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
  }
}

void
FilterMsi_ (::xercesc::XMLFormatTarget& t,
            const ::FilterMsi& s,
            ::xml_schema::ErrorHandler& h,
            const ::xml_schema::NamespaceInfomap& m,
            const ::std::string& e,
            ::xml_schema::Flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::FilterMsi_ (s, m, f));
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
FilterMsi_ (::xercesc::XMLFormatTarget& t,
            const ::FilterMsi& s,
            ::xercesc::DOMErrorHandler& h,
            const ::xml_schema::NamespaceInfomap& m,
            const ::std::string& e,
            ::xml_schema::Flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::FilterMsi_ (s, m, f));
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
FilterMsi_ (::xercesc::DOMDocument& d,
            const ::FilterMsi& s,
            ::xml_schema::Flags)
{
  ::xercesc::DOMElement& e (*d.getDocumentElement ());
  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (n.name () == "FilterMsi" &&
      n.namespace_ () == "")
  {
    e << s;
  }
  else
  {
    throw ::xsd::cxx::tree::unexpected_element < char > (
      n.name (),
      n.namespace_ (),
      "FilterMsi",
      "");
  }
}

::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument >
FilterMsi_ (const ::FilterMsi& s,
            const ::xml_schema::NamespaceInfomap& m,
            ::xml_schema::Flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::serialize< char > (
      "FilterMsi",
      "",
      m, f));

  ::FilterMsi_ (*d, s, f);
  return d;
}

void
operator<< (::xercesc::DOMElement& e, const FilterMsi& i)
{
  e << static_cast< const ::IFilter& > (i);

  // type
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "type",
        e));

    a << i.type ();
  }

  // subtype
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "subtype",
        e));

    a << i.subtype ();
  }

  // code
  //
  if (i.code ())
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "code",
        e));

    a << *i.code ();
  }

  // item
  //
  if (i.item ())
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "item",
        e));

    a << *i.item ();
  }

  // value
  //
  if (i.value ())
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "value",
        e));

    a << *i.value ();
  }

  // min
  //
  if (i.min ())
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "min",
        e));

    a << *i.min ();
  }

  // max
  //
  if (i.max ())
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "max",
        e));

    a << *i.max ();
  }

  // gte
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "gte",
        e));

    a << i.gte ();
  }

  // lte
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "lte",
        e));

    a << i.lte ();
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

