// Copyright (c) 2005-2017 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "osschema.h"

// EnumFilterBool
// 

EnumFilterBool::
EnumFilterBool (Value v)
: ::xml_schema::String (_xsd_EnumFilterBool_literals_[v])
{
}

EnumFilterBool::
EnumFilterBool (const char* v)
: ::xml_schema::String (v)
{
}

EnumFilterBool::
EnumFilterBool (const ::std::string& v)
: ::xml_schema::String (v)
{
}

EnumFilterBool::
EnumFilterBool (const ::xml_schema::String& v)
: ::xml_schema::String (v)
{
}

EnumFilterBool::
EnumFilterBool (const EnumFilterBool& v,
                ::xml_schema::Flags f,
                ::xml_schema::Container* c)
: ::xml_schema::String (v, f, c)
{
}

EnumFilterBool& EnumFilterBool::
operator= (Value v)
{
  static_cast< ::xml_schema::String& > (*this) = 
  ::xml_schema::String (_xsd_EnumFilterBool_literals_[v]);

  return *this;
}


// EnumTrueFalse
// 

EnumTrueFalse::
EnumTrueFalse (Value v)
: ::xml_schema::String (_xsd_EnumTrueFalse_literals_[v])
{
}

EnumTrueFalse::
EnumTrueFalse (const char* v)
: ::xml_schema::String (v)
{
}

EnumTrueFalse::
EnumTrueFalse (const ::std::string& v)
: ::xml_schema::String (v)
{
}

EnumTrueFalse::
EnumTrueFalse (const ::xml_schema::String& v)
: ::xml_schema::String (v)
{
}

EnumTrueFalse::
EnumTrueFalse (const EnumTrueFalse& v,
               ::xml_schema::Flags f,
               ::xml_schema::Container* c)
: ::xml_schema::String (v, f, c)
{
}

EnumTrueFalse& EnumTrueFalse::
operator= (Value v)
{
  static_cast< ::xml_schema::String& > (*this) = 
  ::xml_schema::String (_xsd_EnumTrueFalse_literals_[v]);

  return *this;
}


// EnumFilterOsClass
// 

EnumFilterOsClass::
EnumFilterOsClass (Value v)
: ::xml_schema::String (_xsd_EnumFilterOsClass_literals_[v])
{
}

EnumFilterOsClass::
EnumFilterOsClass (const char* v)
: ::xml_schema::String (v)
{
}

EnumFilterOsClass::
EnumFilterOsClass (const ::std::string& v)
: ::xml_schema::String (v)
{
}

EnumFilterOsClass::
EnumFilterOsClass (const ::xml_schema::String& v)
: ::xml_schema::String (v)
{
}

EnumFilterOsClass::
EnumFilterOsClass (const EnumFilterOsClass& v,
                   ::xml_schema::Flags f,
                   ::xml_schema::Container* c)
: ::xml_schema::String (v, f, c)
{
}

EnumFilterOsClass& EnumFilterOsClass::
operator= (Value v)
{
  static_cast< ::xml_schema::String& > (*this) = 
  ::xml_schema::String (_xsd_EnumFilterOsClass_literals_[v]);

  return *this;
}


// EnumFilterOsVersion
// 

EnumFilterOsVersion::
EnumFilterOsVersion (Value v)
: ::xml_schema::String (_xsd_EnumFilterOsVersion_literals_[v])
{
}

EnumFilterOsVersion::
EnumFilterOsVersion (const char* v)
: ::xml_schema::String (v)
{
}

EnumFilterOsVersion::
EnumFilterOsVersion (const ::std::string& v)
: ::xml_schema::String (v)
{
}

EnumFilterOsVersion::
EnumFilterOsVersion (const ::xml_schema::String& v)
: ::xml_schema::String (v)
{
}

EnumFilterOsVersion::
EnumFilterOsVersion (const EnumFilterOsVersion& v,
                     ::xml_schema::Flags f,
                     ::xml_schema::Container* c)
: ::xml_schema::String (v, f, c)
{
}

EnumFilterOsVersion& EnumFilterOsVersion::
operator= (Value v)
{
  static_cast< ::xml_schema::String& > (*this) = 
  ::xml_schema::String (_xsd_EnumFilterOsVersion_literals_[v]);

  return *this;
}


// EnumFilterOsType
// 

EnumFilterOsType::
EnumFilterOsType (Value v)
: ::xml_schema::String (_xsd_EnumFilterOsType_literals_[v])
{
}

EnumFilterOsType::
EnumFilterOsType (const char* v)
: ::xml_schema::String (v)
{
}

EnumFilterOsType::
EnumFilterOsType (const ::std::string& v)
: ::xml_schema::String (v)
{
}

EnumFilterOsType::
EnumFilterOsType (const ::xml_schema::String& v)
: ::xml_schema::String (v)
{
}

EnumFilterOsType::
EnumFilterOsType (const EnumFilterOsType& v,
                  ::xml_schema::Flags f,
                  ::xml_schema::Container* c)
: ::xml_schema::String (v, f, c)
{
}

EnumFilterOsType& EnumFilterOsType::
operator= (Value v)
{
  static_cast< ::xml_schema::String& > (*this) = 
  ::xml_schema::String (_xsd_EnumFilterOsType_literals_[v]);

  return *this;
}


// EnumFilterOsEdition
// 

EnumFilterOsEdition::
EnumFilterOsEdition (Value v)
: ::xml_schema::String (_xsd_EnumFilterOsEdition_literals_[v])
{
}

EnumFilterOsEdition::
EnumFilterOsEdition (const char* v)
: ::xml_schema::String (v)
{
}

EnumFilterOsEdition::
EnumFilterOsEdition (const ::std::string& v)
: ::xml_schema::String (v)
{
}

EnumFilterOsEdition::
EnumFilterOsEdition (const ::xml_schema::String& v)
: ::xml_schema::String (v)
{
}

EnumFilterOsEdition::
EnumFilterOsEdition (const EnumFilterOsEdition& v,
                     ::xml_schema::Flags f,
                     ::xml_schema::Container* c)
: ::xml_schema::String (v, f, c)
{
}

EnumFilterOsEdition& EnumFilterOsEdition::
operator= (Value v)
{
  static_cast< ::xml_schema::String& > (*this) = 
  ::xml_schema::String (_xsd_EnumFilterOsEdition_literals_[v]);

  return *this;
}


// EnumFilterOsSp
// 

EnumFilterOsSp::
EnumFilterOsSp (Value v)
: ::xml_schema::String (_xsd_EnumFilterOsSp_literals_[v])
{
}

EnumFilterOsSp::
EnumFilterOsSp (const char* v)
: ::xml_schema::String (v)
{
}

EnumFilterOsSp::
EnumFilterOsSp (const ::std::string& v)
: ::xml_schema::String (v)
{
}

EnumFilterOsSp::
EnumFilterOsSp (const ::xml_schema::String& v)
: ::xml_schema::String (v)
{
}

EnumFilterOsSp::
EnumFilterOsSp (const EnumFilterOsSp& v,
                ::xml_schema::Flags f,
                ::xml_schema::Container* c)
: ::xml_schema::String (v, f, c)
{
}

EnumFilterOsSp& EnumFilterOsSp::
operator= (Value v)
{
  static_cast< ::xml_schema::String& > (*this) = 
  ::xml_schema::String (_xsd_EnumFilterOsSp_literals_[v]);

  return *this;
}


// IFilter
// 

const IFilter::BoolType& IFilter::
bool_ () const
{
  return this->bool__.get ();
}

IFilter::BoolType& IFilter::
bool_ ()
{
  return this->bool__.get ();
}

void IFilter::
bool_ (const BoolType& x)
{
  this->bool__.set (x);
}

void IFilter::
bool_ (::std::unique_ptr< BoolType > x)
{
  this->bool__.set (std::move (x));
}

const IFilter::NotType& IFilter::
not_ () const
{
  return this->not__.get ();
}

IFilter::NotType& IFilter::
not_ ()
{
  return this->not__.get ();
}

void IFilter::
not_ (const NotType& x)
{
  this->not__.set (x);
}

void IFilter::
not_ (::std::unique_ptr< NotType > x)
{
  this->not__.set (std::move (x));
}

const IFilter::HiddenOptional& IFilter::
hidden () const
{
  return this->hidden_;
}

IFilter::HiddenOptional& IFilter::
hidden ()
{
  return this->hidden_;
}

void IFilter::
hidden (const HiddenType& x)
{
  this->hidden_.set (x);
}

void IFilter::
hidden (const HiddenOptional& x)
{
  this->hidden_ = x;
}

void IFilter::
hidden (::std::unique_ptr< HiddenType > x)
{
  this->hidden_.set (std::move (x));
}


// FilterOs
// 

const FilterOs::ClassType& FilterOs::
class_ () const
{
  return this->class__.get ();
}

FilterOs::ClassType& FilterOs::
class_ ()
{
  return this->class__.get ();
}

void FilterOs::
class_ (const ClassType& x)
{
  this->class__.set (x);
}

void FilterOs::
class_ (::std::unique_ptr< ClassType > x)
{
  this->class__.set (std::move (x));
}

const FilterOs::ClassType& FilterOs::
class_default_value ()
{
  return class__default_value_;
}

const FilterOs::VersionType& FilterOs::
version () const
{
  return this->version_.get ();
}

FilterOs::VersionType& FilterOs::
version ()
{
  return this->version_.get ();
}

void FilterOs::
version (const VersionType& x)
{
  this->version_.set (x);
}

void FilterOs::
version (::std::unique_ptr< VersionType > x)
{
  this->version_.set (std::move (x));
}

const FilterOs::VersionType& FilterOs::
version_default_value ()
{
  return version_default_value_;
}

const FilterOs::TypeType& FilterOs::
type () const
{
  return this->type_.get ();
}

FilterOs::TypeType& FilterOs::
type ()
{
  return this->type_.get ();
}

void FilterOs::
type (const TypeType& x)
{
  this->type_.set (x);
}

void FilterOs::
type (::std::unique_ptr< TypeType > x)
{
  this->type_.set (std::move (x));
}

const FilterOs::TypeType& FilterOs::
type_default_value ()
{
  return type_default_value_;
}

const FilterOs::EditionType& FilterOs::
edition () const
{
  return this->edition_.get ();
}

FilterOs::EditionType& FilterOs::
edition ()
{
  return this->edition_.get ();
}

void FilterOs::
edition (const EditionType& x)
{
  this->edition_.set (x);
}

void FilterOs::
edition (::std::unique_ptr< EditionType > x)
{
  this->edition_.set (std::move (x));
}

const FilterOs::EditionType& FilterOs::
edition_default_value ()
{
  return edition_default_value_;
}

const FilterOs::SpType& FilterOs::
sp () const
{
  return this->sp_.get ();
}

FilterOs::SpType& FilterOs::
sp ()
{
  return this->sp_.get ();
}

void FilterOs::
sp (const SpType& x)
{
  this->sp_.set (x);
}

void FilterOs::
sp (::std::unique_ptr< SpType > x)
{
  this->sp_.set (std::move (x));
}

const FilterOs::SpType& FilterOs::
sp_default_value ()
{
  return sp_default_value_;
}


#include <xsd/cxx/xml/dom/wildcard-source.hxx>

#include <xsd/cxx/xml/dom/parsing-source.hxx>

#include <xsd/cxx/tree/type-factory-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_factory_plate< 0, char >
  type_factory_plate_init;
}

// EnumFilterBool
//

EnumFilterBool::
EnumFilterBool (const ::xercesc::DOMElement& e,
                ::xml_schema::Flags f,
                ::xml_schema::Container* c)
: ::xml_schema::String (e, f, c)
{
  _xsd_EnumFilterBool_convert ();
}

EnumFilterBool::
EnumFilterBool (const ::xercesc::DOMAttr& a,
                ::xml_schema::Flags f,
                ::xml_schema::Container* c)
: ::xml_schema::String (a, f, c)
{
  _xsd_EnumFilterBool_convert ();
}

EnumFilterBool::
EnumFilterBool (const ::std::string& s,
                const ::xercesc::DOMElement* e,
                ::xml_schema::Flags f,
                ::xml_schema::Container* c)
: ::xml_schema::String (s, e, f, c)
{
  _xsd_EnumFilterBool_convert ();
}

EnumFilterBool* EnumFilterBool::
_clone (::xml_schema::Flags f,
        ::xml_schema::Container* c) const
{
  return new class EnumFilterBool (*this, f, c);
}

EnumFilterBool::Value EnumFilterBool::
_xsd_EnumFilterBool_convert () const
{
  ::xsd::cxx::tree::enum_comparator< char > c (_xsd_EnumFilterBool_literals_);
  const Value* i (::std::lower_bound (
                    _xsd_EnumFilterBool_indexes_,
                    _xsd_EnumFilterBool_indexes_ + 2,
                    *this,
                    c));

  if (i == _xsd_EnumFilterBool_indexes_ + 2 || _xsd_EnumFilterBool_literals_[*i] != *this)
  {
    throw ::xsd::cxx::tree::unexpected_enumerator < char > (*this);
  }

  return *i;
}

const char* const EnumFilterBool::
_xsd_EnumFilterBool_literals_[2] =
{
  "AND",
  "OR"
};

const EnumFilterBool::Value EnumFilterBool::
_xsd_EnumFilterBool_indexes_[2] =
{
  ::EnumFilterBool::AND,
  ::EnumFilterBool::OR
};

static
const ::xsd::cxx::tree::type_factory_initializer< 0, char, EnumFilterBool >
_xsd_EnumFilterBool_type_factory_init (
  "enumFilterBool",
  "");

// EnumTrueFalse
//

EnumTrueFalse::
EnumTrueFalse (const ::xercesc::DOMElement& e,
               ::xml_schema::Flags f,
               ::xml_schema::Container* c)
: ::xml_schema::String (e, f, c)
{
  _xsd_EnumTrueFalse_convert ();
}

EnumTrueFalse::
EnumTrueFalse (const ::xercesc::DOMAttr& a,
               ::xml_schema::Flags f,
               ::xml_schema::Container* c)
: ::xml_schema::String (a, f, c)
{
  _xsd_EnumTrueFalse_convert ();
}

EnumTrueFalse::
EnumTrueFalse (const ::std::string& s,
               const ::xercesc::DOMElement* e,
               ::xml_schema::Flags f,
               ::xml_schema::Container* c)
: ::xml_schema::String (s, e, f, c)
{
  _xsd_EnumTrueFalse_convert ();
}

EnumTrueFalse* EnumTrueFalse::
_clone (::xml_schema::Flags f,
        ::xml_schema::Container* c) const
{
  return new class EnumTrueFalse (*this, f, c);
}

EnumTrueFalse::Value EnumTrueFalse::
_xsd_EnumTrueFalse_convert () const
{
  ::xsd::cxx::tree::enum_comparator< char > c (_xsd_EnumTrueFalse_literals_);
  const Value* i (::std::lower_bound (
                    _xsd_EnumTrueFalse_indexes_,
                    _xsd_EnumTrueFalse_indexes_ + 2,
                    *this,
                    c));

  if (i == _xsd_EnumTrueFalse_indexes_ + 2 || _xsd_EnumTrueFalse_literals_[*i] != *this)
  {
    throw ::xsd::cxx::tree::unexpected_enumerator < char > (*this);
  }

  return *i;
}

const char* const EnumTrueFalse::
_xsd_EnumTrueFalse_literals_[2] =
{
  "0",
  "1"
};

const EnumTrueFalse::Value EnumTrueFalse::
_xsd_EnumTrueFalse_indexes_[2] =
{
  ::EnumTrueFalse::cxx_0,
  ::EnumTrueFalse::cxx_1
};

static
const ::xsd::cxx::tree::type_factory_initializer< 0, char, EnumTrueFalse >
_xsd_EnumTrueFalse_type_factory_init (
  "enumTrueFalse",
  "");

// EnumFilterOsClass
//

EnumFilterOsClass::
EnumFilterOsClass (const ::xercesc::DOMElement& e,
                   ::xml_schema::Flags f,
                   ::xml_schema::Container* c)
: ::xml_schema::String (e, f, c)
{
  _xsd_EnumFilterOsClass_convert ();
}

EnumFilterOsClass::
EnumFilterOsClass (const ::xercesc::DOMAttr& a,
                   ::xml_schema::Flags f,
                   ::xml_schema::Container* c)
: ::xml_schema::String (a, f, c)
{
  _xsd_EnumFilterOsClass_convert ();
}

EnumFilterOsClass::
EnumFilterOsClass (const ::std::string& s,
                   const ::xercesc::DOMElement* e,
                   ::xml_schema::Flags f,
                   ::xml_schema::Container* c)
: ::xml_schema::String (s, e, f, c)
{
  _xsd_EnumFilterOsClass_convert ();
}

EnumFilterOsClass* EnumFilterOsClass::
_clone (::xml_schema::Flags f,
        ::xml_schema::Container* c) const
{
  return new class EnumFilterOsClass (*this, f, c);
}

EnumFilterOsClass::Value EnumFilterOsClass::
_xsd_EnumFilterOsClass_convert () const
{
  ::xsd::cxx::tree::enum_comparator< char > c (_xsd_EnumFilterOsClass_literals_);
  const Value* i (::std::lower_bound (
                    _xsd_EnumFilterOsClass_indexes_,
                    _xsd_EnumFilterOsClass_indexes_ + 3,
                    *this,
                    c));

  if (i == _xsd_EnumFilterOsClass_indexes_ + 3 || _xsd_EnumFilterOsClass_literals_[*i] != *this)
  {
    throw ::xsd::cxx::tree::unexpected_enumerator < char > (*this);
  }

  return *i;
}

const char* const EnumFilterOsClass::
_xsd_EnumFilterOsClass_literals_[3] =
{
  "NE",
  "9X",
  "NT"
};

const EnumFilterOsClass::Value EnumFilterOsClass::
_xsd_EnumFilterOsClass_indexes_[3] =
{
  ::EnumFilterOsClass::cxx_9X,
  ::EnumFilterOsClass::NE,
  ::EnumFilterOsClass::NT
};

static
const ::xsd::cxx::tree::type_factory_initializer< 0, char, EnumFilterOsClass >
_xsd_EnumFilterOsClass_type_factory_init (
  "enumFilterOsClass",
  "");

// EnumFilterOsVersion
//

EnumFilterOsVersion::
EnumFilterOsVersion (const ::xercesc::DOMElement& e,
                     ::xml_schema::Flags f,
                     ::xml_schema::Container* c)
: ::xml_schema::String (e, f, c)
{
  _xsd_EnumFilterOsVersion_convert ();
}

EnumFilterOsVersion::
EnumFilterOsVersion (const ::xercesc::DOMAttr& a,
                     ::xml_schema::Flags f,
                     ::xml_schema::Container* c)
: ::xml_schema::String (a, f, c)
{
  _xsd_EnumFilterOsVersion_convert ();
}

EnumFilterOsVersion::
EnumFilterOsVersion (const ::std::string& s,
                     const ::xercesc::DOMElement* e,
                     ::xml_schema::Flags f,
                     ::xml_schema::Container* c)
: ::xml_schema::String (s, e, f, c)
{
  _xsd_EnumFilterOsVersion_convert ();
}

EnumFilterOsVersion* EnumFilterOsVersion::
_clone (::xml_schema::Flags f,
        ::xml_schema::Container* c) const
{
  return new class EnumFilterOsVersion (*this, f, c);
}

EnumFilterOsVersion::Value EnumFilterOsVersion::
_xsd_EnumFilterOsVersion_convert () const
{
  ::xsd::cxx::tree::enum_comparator< char > c (_xsd_EnumFilterOsVersion_literals_);
  const Value* i (::std::lower_bound (
                    _xsd_EnumFilterOsVersion_indexes_,
                    _xsd_EnumFilterOsVersion_indexes_ + 19,
                    *this,
                    c));

  if (i == _xsd_EnumFilterOsVersion_indexes_ + 19 || _xsd_EnumFilterOsVersion_literals_[*i] != *this)
  {
    throw ::xsd::cxx::tree::unexpected_enumerator < char > (*this);
  }

  return *i;
}

const char* const EnumFilterOsVersion::
_xsd_EnumFilterOsVersion_literals_[19] =
{
  "NE",
  "95",
  "98",
  "ME",
  "NT",
  "2K",
  "XP",
  "2K3",
  "2K3R2",
  "VISTA",
  "2K8",
  "WIN7",
  "2K8R2",
  "WIN8",
  "WIN8S",
  "WINBLUE",
  "WINBLUESRV",
  "WINTHRESHOLD",
  "WINTHRESHOLDSRV"
};

const EnumFilterOsVersion::Value EnumFilterOsVersion::
_xsd_EnumFilterOsVersion_indexes_[19] =
{
  ::EnumFilterOsVersion::cxx_2K,
  ::EnumFilterOsVersion::cxx_2K3,
  ::EnumFilterOsVersion::cxx_2K3R2,
  ::EnumFilterOsVersion::cxx_2K8,
  ::EnumFilterOsVersion::cxx_2K8R2,
  ::EnumFilterOsVersion::cxx_95,
  ::EnumFilterOsVersion::cxx_98,
  ::EnumFilterOsVersion::ME,
  ::EnumFilterOsVersion::NE,
  ::EnumFilterOsVersion::NT,
  ::EnumFilterOsVersion::VISTA,
  ::EnumFilterOsVersion::WIN7,
  ::EnumFilterOsVersion::WIN8,
  ::EnumFilterOsVersion::WIN8S,
  ::EnumFilterOsVersion::WINBLUE,
  ::EnumFilterOsVersion::WINBLUESRV,
  ::EnumFilterOsVersion::WINTHRESHOLD,
  ::EnumFilterOsVersion::WINTHRESHOLDSRV,
  ::EnumFilterOsVersion::XP
};

static
const ::xsd::cxx::tree::type_factory_initializer< 0, char, EnumFilterOsVersion >
_xsd_EnumFilterOsVersion_type_factory_init (
  "enumFilterOsVersion",
  "");

// EnumFilterOsType
//

EnumFilterOsType::
EnumFilterOsType (const ::xercesc::DOMElement& e,
                  ::xml_schema::Flags f,
                  ::xml_schema::Container* c)
: ::xml_schema::String (e, f, c)
{
  _xsd_EnumFilterOsType_convert ();
}

EnumFilterOsType::
EnumFilterOsType (const ::xercesc::DOMAttr& a,
                  ::xml_schema::Flags f,
                  ::xml_schema::Container* c)
: ::xml_schema::String (a, f, c)
{
  _xsd_EnumFilterOsType_convert ();
}

EnumFilterOsType::
EnumFilterOsType (const ::std::string& s,
                  const ::xercesc::DOMElement* e,
                  ::xml_schema::Flags f,
                  ::xml_schema::Container* c)
: ::xml_schema::String (s, e, f, c)
{
  _xsd_EnumFilterOsType_convert ();
}

EnumFilterOsType* EnumFilterOsType::
_clone (::xml_schema::Flags f,
        ::xml_schema::Container* c) const
{
  return new class EnumFilterOsType (*this, f, c);
}

EnumFilterOsType::Value EnumFilterOsType::
_xsd_EnumFilterOsType_convert () const
{
  ::xsd::cxx::tree::enum_comparator< char > c (_xsd_EnumFilterOsType_literals_);
  const Value* i (::std::lower_bound (
                    _xsd_EnumFilterOsType_indexes_,
                    _xsd_EnumFilterOsType_indexes_ + 8,
                    *this,
                    c));

  if (i == _xsd_EnumFilterOsType_indexes_ + 8 || _xsd_EnumFilterOsType_literals_[*i] != *this)
  {
    throw ::xsd::cxx::tree::unexpected_enumerator < char > (*this);
  }

  return *i;
}

const char* const EnumFilterOsType::
_xsd_EnumFilterOsType_literals_[8] =
{
  "NE",
  "R2",
  "SE",
  "WS",
  "SV",
  "DC",
  "PRO",
  "PR"
};

const EnumFilterOsType::Value EnumFilterOsType::
_xsd_EnumFilterOsType_indexes_[8] =
{
  ::EnumFilterOsType::DC,
  ::EnumFilterOsType::NE,
  ::EnumFilterOsType::PR,
  ::EnumFilterOsType::PRO,
  ::EnumFilterOsType::R2,
  ::EnumFilterOsType::SE,
  ::EnumFilterOsType::SV,
  ::EnumFilterOsType::WS
};

static
const ::xsd::cxx::tree::type_factory_initializer< 0, char, EnumFilterOsType >
_xsd_EnumFilterOsType_type_factory_init (
  "enumFilterOsType",
  "");

// EnumFilterOsEdition
//

EnumFilterOsEdition::
EnumFilterOsEdition (const ::xercesc::DOMElement& e,
                     ::xml_schema::Flags f,
                     ::xml_schema::Container* c)
: ::xml_schema::String (e, f, c)
{
  _xsd_EnumFilterOsEdition_convert ();
}

EnumFilterOsEdition::
EnumFilterOsEdition (const ::xercesc::DOMAttr& a,
                     ::xml_schema::Flags f,
                     ::xml_schema::Container* c)
: ::xml_schema::String (a, f, c)
{
  _xsd_EnumFilterOsEdition_convert ();
}

EnumFilterOsEdition::
EnumFilterOsEdition (const ::std::string& s,
                     const ::xercesc::DOMElement* e,
                     ::xml_schema::Flags f,
                     ::xml_schema::Container* c)
: ::xml_schema::String (s, e, f, c)
{
  _xsd_EnumFilterOsEdition_convert ();
}

EnumFilterOsEdition* EnumFilterOsEdition::
_clone (::xml_schema::Flags f,
        ::xml_schema::Container* c) const
{
  return new class EnumFilterOsEdition (*this, f, c);
}

EnumFilterOsEdition::Value EnumFilterOsEdition::
_xsd_EnumFilterOsEdition_convert () const
{
  ::xsd::cxx::tree::enum_comparator< char > c (_xsd_EnumFilterOsEdition_literals_);
  const Value* i (::std::lower_bound (
                    _xsd_EnumFilterOsEdition_indexes_,
                    _xsd_EnumFilterOsEdition_indexes_ + 16,
                    *this,
                    c));

  if (i == _xsd_EnumFilterOsEdition_indexes_ + 16 || _xsd_EnumFilterOsEdition_literals_[*i] != *this)
  {
    throw ::xsd::cxx::tree::unexpected_enumerator < char > (*this);
  }

  return *i;
}

const char* const EnumFilterOsEdition::
_xsd_EnumFilterOsEdition_literals_[16] =
{
  "NE",
  "64EP",
  "64DC",
  "AS",
  "DTC",
  "EP",
  "WEB",
  "64",
  "HM",
  "MC",
  "TPC",
  "SRV",
  "STD",
  "TSE",
  "SBS",
  "PRO"
};

const EnumFilterOsEdition::Value EnumFilterOsEdition::
_xsd_EnumFilterOsEdition_indexes_[16] =
{
  ::EnumFilterOsEdition::cxx_64,
  ::EnumFilterOsEdition::cxx_64DC,
  ::EnumFilterOsEdition::cxx_64EP,
  ::EnumFilterOsEdition::AS,
  ::EnumFilterOsEdition::DTC,
  ::EnumFilterOsEdition::EP,
  ::EnumFilterOsEdition::HM,
  ::EnumFilterOsEdition::MC,
  ::EnumFilterOsEdition::NE,
  ::EnumFilterOsEdition::PRO,
  ::EnumFilterOsEdition::SBS,
  ::EnumFilterOsEdition::SRV,
  ::EnumFilterOsEdition::STD,
  ::EnumFilterOsEdition::TPC,
  ::EnumFilterOsEdition::TSE,
  ::EnumFilterOsEdition::WEB
};

static
const ::xsd::cxx::tree::type_factory_initializer< 0, char, EnumFilterOsEdition >
_xsd_EnumFilterOsEdition_type_factory_init (
  "enumFilterOsEdition",
  "");

// EnumFilterOsSp
//

EnumFilterOsSp::
EnumFilterOsSp (const ::xercesc::DOMElement& e,
                ::xml_schema::Flags f,
                ::xml_schema::Container* c)
: ::xml_schema::String (e, f, c)
{
  _xsd_EnumFilterOsSp_convert ();
}

EnumFilterOsSp::
EnumFilterOsSp (const ::xercesc::DOMAttr& a,
                ::xml_schema::Flags f,
                ::xml_schema::Container* c)
: ::xml_schema::String (a, f, c)
{
  _xsd_EnumFilterOsSp_convert ();
}

EnumFilterOsSp::
EnumFilterOsSp (const ::std::string& s,
                const ::xercesc::DOMElement* e,
                ::xml_schema::Flags f,
                ::xml_schema::Container* c)
: ::xml_schema::String (s, e, f, c)
{
  _xsd_EnumFilterOsSp_convert ();
}

EnumFilterOsSp* EnumFilterOsSp::
_clone (::xml_schema::Flags f,
        ::xml_schema::Container* c) const
{
  return new class EnumFilterOsSp (*this, f, c);
}

EnumFilterOsSp::Value EnumFilterOsSp::
_xsd_EnumFilterOsSp_convert () const
{
  ::xsd::cxx::tree::enum_comparator< char > c (_xsd_EnumFilterOsSp_literals_);
  const Value* i (::std::lower_bound (
                    _xsd_EnumFilterOsSp_indexes_,
                    _xsd_EnumFilterOsSp_indexes_ + 8,
                    *this,
                    c));

  if (i == _xsd_EnumFilterOsSp_indexes_ + 8 || _xsd_EnumFilterOsSp_literals_[*i] != *this)
  {
    throw ::xsd::cxx::tree::unexpected_enumerator < char > (*this);
  }

  return *i;
}

const char* const EnumFilterOsSp::
_xsd_EnumFilterOsSp_literals_[8] =
{
  "NE",
  "Gold",
  "Service Pack 1",
  "Service Pack 2",
  "Service Pack 3",
  "Service Pack 4",
  "Service Pack 5",
  "Service Pack 6"
};

const EnumFilterOsSp::Value EnumFilterOsSp::
_xsd_EnumFilterOsSp_indexes_[8] =
{
  ::EnumFilterOsSp::Gold,
  ::EnumFilterOsSp::NE,
  ::EnumFilterOsSp::Service_Pack_1,
  ::EnumFilterOsSp::Service_Pack_2,
  ::EnumFilterOsSp::Service_Pack_3,
  ::EnumFilterOsSp::Service_Pack_4,
  ::EnumFilterOsSp::Service_Pack_5,
  ::EnumFilterOsSp::Service_Pack_6
};

static
const ::xsd::cxx::tree::type_factory_initializer< 0, char, EnumFilterOsSp >
_xsd_EnumFilterOsSp_type_factory_init (
  "enumFilterOsSp",
  "");

// IFilter
//

IFilter::
IFilter (const BoolType& bool_,
         const NotType& not_)
: ::xml_schema::Type (),
  bool__ (bool_, this),
  not__ (not_, this),
  hidden_ (this)
{
}

IFilter::
IFilter (const IFilter& x,
         ::xml_schema::Flags f,
         ::xml_schema::Container* c)
: ::xml_schema::Type (x, f, c),
  bool__ (x.bool__, f, this),
  not__ (x.not__, f, this),
  hidden_ (x.hidden_, f, this)
{
}

IFilter::
IFilter (const ::xercesc::DOMElement& e,
         ::xml_schema::Flags f,
         ::xml_schema::Container* c)
: ::xml_schema::Type (e, f | ::xml_schema::Flags::base, c),
  bool__ (this),
  not__ (this),
  hidden_ (this)
{
  if ((f & ::xml_schema::Flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, false, false, true);
    this->parse (p, f);
  }
}

void IFilter::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::Flags f)
{
  while (p.more_attributes ())
  {
    const ::xercesc::DOMAttr& i (p.next_attribute ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    if (n.name () == "bool" && n.namespace_ ().empty ())
    {
      this->bool__.set (BoolTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "not" && n.namespace_ ().empty ())
    {
      this->not__.set (NotTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "hidden" && n.namespace_ ().empty ())
    {
      this->hidden_.set (HiddenTraits::create (i, f, this));
      continue;
    }
  }

  if (!bool__.present ())
  {
    throw ::xsd::cxx::tree::expected_attribute< char > (
      "bool",
      "");
  }

  if (!not__.present ())
  {
    throw ::xsd::cxx::tree::expected_attribute< char > (
      "not",
      "");
  }
}

IFilter& IFilter::
operator= (const IFilter& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::Type& > (*this) = x;
    this->bool__ = x.bool__;
    this->not__ = x.not__;
    this->hidden_ = x.hidden_;
  }

  return *this;
}

IFilter::
~IFilter ()
{
}

// FilterOs
//

const FilterOs::ClassType FilterOs::class__default_value_ (
  "NE");

const FilterOs::VersionType FilterOs::version_default_value_ (
  "NE");

const FilterOs::TypeType FilterOs::type_default_value_ (
  "NE");

const FilterOs::EditionType FilterOs::edition_default_value_ (
  "NE");

const FilterOs::SpType FilterOs::sp_default_value_ (
  "NE");

FilterOs::
FilterOs (const BoolType& bool_,
          const NotType& not_)
: ::IFilter (bool_,
             not_),
  class__ (class_default_value (), this),
  version_ (version_default_value (), this),
  type_ (type_default_value (), this),
  edition_ (edition_default_value (), this),
  sp_ (sp_default_value (), this)
{
}

FilterOs::
FilterOs (const FilterOs& x,
          ::xml_schema::Flags f,
          ::xml_schema::Container* c)
: ::IFilter (x, f, c),
  class__ (x.class__, f, this),
  version_ (x.version_, f, this),
  type_ (x.type_, f, this),
  edition_ (x.edition_, f, this),
  sp_ (x.sp_, f, this)
{
}

FilterOs::
FilterOs (const ::xercesc::DOMElement& e,
          ::xml_schema::Flags f,
          ::xml_schema::Container* c)
: ::IFilter (e, f | ::xml_schema::Flags::base, c),
  class__ (this),
  version_ (this),
  type_ (this),
  edition_ (this),
  sp_ (this)
{
  if ((f & ::xml_schema::Flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, false, false, true);
    this->parse (p, f);
  }
}

void FilterOs::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::Flags f)
{
  this->::IFilter::parse (p, f);

  p.reset_attributes ();

  while (p.more_attributes ())
  {
    const ::xercesc::DOMAttr& i (p.next_attribute ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    if (n.name () == "class" && n.namespace_ ().empty ())
    {
      this->class__.set (ClassTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "version" && n.namespace_ ().empty ())
    {
      this->version_.set (VersionTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "type" && n.namespace_ ().empty ())
    {
      this->type_.set (TypeTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "edition" && n.namespace_ ().empty ())
    {
      this->edition_.set (EditionTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "sp" && n.namespace_ ().empty ())
    {
      this->sp_.set (SpTraits::create (i, f, this));
      continue;
    }
  }

  if (!class__.present ())
  {
    this->class__.set (class_default_value ());
  }

  if (!version_.present ())
  {
    this->version_.set (version_default_value ());
  }

  if (!type_.present ())
  {
    this->type_.set (type_default_value ());
  }

  if (!edition_.present ())
  {
    this->edition_.set (edition_default_value ());
  }

  if (!sp_.present ())
  {
    this->sp_.set (sp_default_value ());
  }
}

FilterOs* FilterOs::
_clone (::xml_schema::Flags f,
        ::xml_schema::Container* c) const
{
  return new class FilterOs (*this, f, c);
}

FilterOs& FilterOs::
operator= (const FilterOs& x)
{
  if (this != &x)
  {
    static_cast< ::IFilter& > (*this) = x;
    this->class__ = x.class__;
    this->version_ = x.version_;
    this->type_ = x.type_;
    this->edition_ = x.edition_;
    this->sp_ = x.sp_;
  }

  return *this;
}

FilterOs::
~FilterOs ()
{
}

#include <ostream>

#include <xsd/cxx/tree/std-ostream-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::std_ostream_plate< 0, char >
  std_ostream_plate_init;
}

::std::ostream&
operator<< (::std::ostream& o, EnumFilterBool::Value i)
{
  return o << EnumFilterBool::_xsd_EnumFilterBool_literals_[i];
}

::std::ostream&
operator<< (::std::ostream& o, const EnumFilterBool& i)
{
  return o << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::std_ostream_initializer< 0, char, EnumFilterBool >
_xsd_EnumFilterBool_std_ostream_init;

::std::ostream&
operator<< (::std::ostream& o, EnumTrueFalse::Value i)
{
  return o << EnumTrueFalse::_xsd_EnumTrueFalse_literals_[i];
}

::std::ostream&
operator<< (::std::ostream& o, const EnumTrueFalse& i)
{
  return o << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::std_ostream_initializer< 0, char, EnumTrueFalse >
_xsd_EnumTrueFalse_std_ostream_init;

::std::ostream&
operator<< (::std::ostream& o, EnumFilterOsClass::Value i)
{
  return o << EnumFilterOsClass::_xsd_EnumFilterOsClass_literals_[i];
}

::std::ostream&
operator<< (::std::ostream& o, const EnumFilterOsClass& i)
{
  return o << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::std_ostream_initializer< 0, char, EnumFilterOsClass >
_xsd_EnumFilterOsClass_std_ostream_init;

::std::ostream&
operator<< (::std::ostream& o, EnumFilterOsVersion::Value i)
{
  return o << EnumFilterOsVersion::_xsd_EnumFilterOsVersion_literals_[i];
}

::std::ostream&
operator<< (::std::ostream& o, const EnumFilterOsVersion& i)
{
  return o << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::std_ostream_initializer< 0, char, EnumFilterOsVersion >
_xsd_EnumFilterOsVersion_std_ostream_init;

::std::ostream&
operator<< (::std::ostream& o, EnumFilterOsType::Value i)
{
  return o << EnumFilterOsType::_xsd_EnumFilterOsType_literals_[i];
}

::std::ostream&
operator<< (::std::ostream& o, const EnumFilterOsType& i)
{
  return o << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::std_ostream_initializer< 0, char, EnumFilterOsType >
_xsd_EnumFilterOsType_std_ostream_init;

::std::ostream&
operator<< (::std::ostream& o, EnumFilterOsEdition::Value i)
{
  return o << EnumFilterOsEdition::_xsd_EnumFilterOsEdition_literals_[i];
}

::std::ostream&
operator<< (::std::ostream& o, const EnumFilterOsEdition& i)
{
  return o << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::std_ostream_initializer< 0, char, EnumFilterOsEdition >
_xsd_EnumFilterOsEdition_std_ostream_init;

::std::ostream&
operator<< (::std::ostream& o, EnumFilterOsSp::Value i)
{
  return o << EnumFilterOsSp::_xsd_EnumFilterOsSp_literals_[i];
}

::std::ostream&
operator<< (::std::ostream& o, const EnumFilterOsSp& i)
{
  return o << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::std_ostream_initializer< 0, char, EnumFilterOsSp >
_xsd_EnumFilterOsSp_std_ostream_init;

::std::ostream&
operator<< (::std::ostream& o, const IFilter& i)
{
  o << ::std::endl << "bool: " << i.bool_ ();
  o << ::std::endl << "not: " << i.not_ ();
  if (i.hidden ())
  {
    o << ::std::endl << "hidden: " << *i.hidden ();
  }

  return o;
}

::std::ostream&
operator<< (::std::ostream& o, const FilterOs& i)
{
  o << static_cast< const ::IFilter& > (i);

  o << ::std::endl << "class: " << i.class_ ();
  o << ::std::endl << "version: " << i.version ();
  o << ::std::endl << "type: " << i.type ();
  o << ::std::endl << "edition: " << i.edition ();
  o << ::std::endl << "sp: " << i.sp ();
  return o;
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

::std::unique_ptr< ::FilterOs >
FilterOs_ (const ::std::string& u,
           ::xml_schema::Flags f,
           const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  return ::std::unique_ptr< ::FilterOs > (
    ::FilterOs_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::FilterOs >
FilterOs_ (const ::std::string& u,
           ::xml_schema::ErrorHandler& h,
           ::xml_schema::Flags f,
           const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::FilterOs > (
    ::FilterOs_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::FilterOs >
FilterOs_ (const ::std::string& u,
           ::xercesc::DOMErrorHandler& h,
           ::xml_schema::Flags f,
           const ::xml_schema::Properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::FilterOs > (
    ::FilterOs_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::FilterOs >
FilterOs_ (::std::istream& is,
           ::xml_schema::Flags f,
           const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::FilterOs_ (isrc, f, p);
}

::std::unique_ptr< ::FilterOs >
FilterOs_ (::std::istream& is,
           ::xml_schema::ErrorHandler& h,
           ::xml_schema::Flags f,
           const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::FilterOs_ (isrc, h, f, p);
}

::std::unique_ptr< ::FilterOs >
FilterOs_ (::std::istream& is,
           ::xercesc::DOMErrorHandler& h,
           ::xml_schema::Flags f,
           const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::FilterOs_ (isrc, h, f, p);
}

::std::unique_ptr< ::FilterOs >
FilterOs_ (::std::istream& is,
           const ::std::string& sid,
           ::xml_schema::Flags f,
           const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::FilterOs_ (isrc, f, p);
}

::std::unique_ptr< ::FilterOs >
FilterOs_ (::std::istream& is,
           const ::std::string& sid,
           ::xml_schema::ErrorHandler& h,
           ::xml_schema::Flags f,
           const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::FilterOs_ (isrc, h, f, p);
}

::std::unique_ptr< ::FilterOs >
FilterOs_ (::std::istream& is,
           const ::std::string& sid,
           ::xercesc::DOMErrorHandler& h,
           ::xml_schema::Flags f,
           const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::FilterOs_ (isrc, h, f, p);
}

::std::unique_ptr< ::FilterOs >
FilterOs_ (::xercesc::InputSource& i,
           ::xml_schema::Flags f,
           const ::xml_schema::Properties& p)
{
  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  return ::std::unique_ptr< ::FilterOs > (
    ::FilterOs_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::FilterOs >
FilterOs_ (::xercesc::InputSource& i,
           ::xml_schema::ErrorHandler& h,
           ::xml_schema::Flags f,
           const ::xml_schema::Properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::FilterOs > (
    ::FilterOs_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::FilterOs >
FilterOs_ (::xercesc::InputSource& i,
           ::xercesc::DOMErrorHandler& h,
           ::xml_schema::Flags f,
           const ::xml_schema::Properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::FilterOs > (
    ::FilterOs_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::FilterOs >
FilterOs_ (const ::xercesc::DOMDocument& doc,
           ::xml_schema::Flags f,
           const ::xml_schema::Properties& p)
{
  if (f & ::xml_schema::Flags::keep_dom)
  {
    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      static_cast< ::xercesc::DOMDocument* > (doc.cloneNode (true)));

    return ::std::unique_ptr< ::FilterOs > (
      ::FilterOs_ (
        std::move (d), f | ::xml_schema::Flags::own_dom, p));
  }

  const ::xercesc::DOMElement& e (*doc.getDocumentElement ());
  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (n.name () == "FilterOs" &&
      n.namespace_ () == "")
  {
    ::std::unique_ptr< ::FilterOs > r (
      ::xsd::cxx::tree::traits< ::FilterOs, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "FilterOs",
    "");
}

::std::unique_ptr< ::FilterOs >
FilterOs_ (::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d,
           ::xml_schema::Flags f,
           const ::xml_schema::Properties&)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > c (
    ((f & ::xml_schema::Flags::keep_dom) &&
     !(f & ::xml_schema::Flags::own_dom))
    ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
    : 0);

  ::xercesc::DOMDocument& doc (c.get () ? *c : *d);
  const ::xercesc::DOMElement& e (*doc.getDocumentElement ());

  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (f & ::xml_schema::Flags::keep_dom)
    doc.setUserData (::xml_schema::dom::tree_node_key,
                     (c.get () ? &c : &d),
                     0);

  if (n.name () == "FilterOs" &&
      n.namespace_ () == "")
  {
    ::std::unique_ptr< ::FilterOs > r (
      ::xsd::cxx::tree::traits< ::FilterOs, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "FilterOs",
    "");
}

#include <ostream>
#include <xsd/cxx/tree/error-handler.hxx>
#include <xsd/cxx/xml/dom/serialization-source.hxx>

#include <xsd/cxx/tree/type-serializer-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_serializer_plate< 0, char >
  type_serializer_plate_init;
}

void
operator<< (::xercesc::DOMElement& e, const EnumFilterBool& i)
{
  e << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xercesc::DOMAttr& a, const EnumFilterBool& i)
{
  a << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xml_schema::ListStream& l,
            const EnumFilterBool& i)
{
  l << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::type_serializer_initializer< 0, char, EnumFilterBool >
_xsd_EnumFilterBool_type_serializer_init (
  "enumFilterBool",
  "");


void
operator<< (::xercesc::DOMElement& e, const EnumTrueFalse& i)
{
  e << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xercesc::DOMAttr& a, const EnumTrueFalse& i)
{
  a << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xml_schema::ListStream& l,
            const EnumTrueFalse& i)
{
  l << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::type_serializer_initializer< 0, char, EnumTrueFalse >
_xsd_EnumTrueFalse_type_serializer_init (
  "enumTrueFalse",
  "");


void
operator<< (::xercesc::DOMElement& e, const EnumFilterOsClass& i)
{
  e << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xercesc::DOMAttr& a, const EnumFilterOsClass& i)
{
  a << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xml_schema::ListStream& l,
            const EnumFilterOsClass& i)
{
  l << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::type_serializer_initializer< 0, char, EnumFilterOsClass >
_xsd_EnumFilterOsClass_type_serializer_init (
  "enumFilterOsClass",
  "");


void
operator<< (::xercesc::DOMElement& e, const EnumFilterOsVersion& i)
{
  e << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xercesc::DOMAttr& a, const EnumFilterOsVersion& i)
{
  a << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xml_schema::ListStream& l,
            const EnumFilterOsVersion& i)
{
  l << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::type_serializer_initializer< 0, char, EnumFilterOsVersion >
_xsd_EnumFilterOsVersion_type_serializer_init (
  "enumFilterOsVersion",
  "");


void
operator<< (::xercesc::DOMElement& e, const EnumFilterOsType& i)
{
  e << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xercesc::DOMAttr& a, const EnumFilterOsType& i)
{
  a << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xml_schema::ListStream& l,
            const EnumFilterOsType& i)
{
  l << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::type_serializer_initializer< 0, char, EnumFilterOsType >
_xsd_EnumFilterOsType_type_serializer_init (
  "enumFilterOsType",
  "");


void
operator<< (::xercesc::DOMElement& e, const EnumFilterOsEdition& i)
{
  e << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xercesc::DOMAttr& a, const EnumFilterOsEdition& i)
{
  a << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xml_schema::ListStream& l,
            const EnumFilterOsEdition& i)
{
  l << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::type_serializer_initializer< 0, char, EnumFilterOsEdition >
_xsd_EnumFilterOsEdition_type_serializer_init (
  "enumFilterOsEdition",
  "");


void
operator<< (::xercesc::DOMElement& e, const EnumFilterOsSp& i)
{
  e << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xercesc::DOMAttr& a, const EnumFilterOsSp& i)
{
  a << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xml_schema::ListStream& l,
            const EnumFilterOsSp& i)
{
  l << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::type_serializer_initializer< 0, char, EnumFilterOsSp >
_xsd_EnumFilterOsSp_type_serializer_init (
  "enumFilterOsSp",
  "");


void
operator<< (::xercesc::DOMElement& e, const IFilter& i)
{
  e << static_cast< const ::xml_schema::Type& > (i);

  // bool
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "bool",
        e));

    a << i.bool_ ();
  }

  // not
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "not",
        e));

    a << i.not_ ();
  }

  // hidden
  //
  if (i.hidden ())
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "hidden",
        e));

    a << *i.hidden ();
  }
}

void
FilterOs_ (::std::ostream& o,
           const ::FilterOs& s,
           const ::xml_schema::NamespaceInfomap& m,
           const ::std::string& e,
           ::xml_schema::Flags f)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0);

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::FilterOs_ (s, m, f));

  ::xsd::cxx::tree::error_handler< char > h;

  ::xsd::cxx::xml::dom::ostream_format_target t (o);
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
  }
}

void
FilterOs_ (::std::ostream& o,
           const ::FilterOs& s,
           ::xml_schema::ErrorHandler& h,
           const ::xml_schema::NamespaceInfomap& m,
           const ::std::string& e,
           ::xml_schema::Flags f)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0);

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::FilterOs_ (s, m, f));
  ::xsd::cxx::xml::dom::ostream_format_target t (o);
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
FilterOs_ (::std::ostream& o,
           const ::FilterOs& s,
           ::xercesc::DOMErrorHandler& h,
           const ::xml_schema::NamespaceInfomap& m,
           const ::std::string& e,
           ::xml_schema::Flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::FilterOs_ (s, m, f));
  ::xsd::cxx::xml::dom::ostream_format_target t (o);
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
FilterOs_ (::xercesc::XMLFormatTarget& t,
           const ::FilterOs& s,
           const ::xml_schema::NamespaceInfomap& m,
           const ::std::string& e,
           ::xml_schema::Flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::FilterOs_ (s, m, f));

  ::xsd::cxx::tree::error_handler< char > h;

  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
  }
}

void
FilterOs_ (::xercesc::XMLFormatTarget& t,
           const ::FilterOs& s,
           ::xml_schema::ErrorHandler& h,
           const ::xml_schema::NamespaceInfomap& m,
           const ::std::string& e,
           ::xml_schema::Flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::FilterOs_ (s, m, f));
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
FilterOs_ (::xercesc::XMLFormatTarget& t,
           const ::FilterOs& s,
           ::xercesc::DOMErrorHandler& h,
           const ::xml_schema::NamespaceInfomap& m,
           const ::std::string& e,
           ::xml_schema::Flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::FilterOs_ (s, m, f));
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
FilterOs_ (::xercesc::DOMDocument& d,
           const ::FilterOs& s,
           ::xml_schema::Flags)
{
  ::xercesc::DOMElement& e (*d.getDocumentElement ());
  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (n.name () == "FilterOs" &&
      n.namespace_ () == "")
  {
    e << s;
  }
  else
  {
    throw ::xsd::cxx::tree::unexpected_element < char > (
      n.name (),
      n.namespace_ (),
      "FilterOs",
      "");
  }
}

::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument >
FilterOs_ (const ::FilterOs& s,
           const ::xml_schema::NamespaceInfomap& m,
           ::xml_schema::Flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::serialize< char > (
      "FilterOs",
      "",
      m, f));

  ::FilterOs_ (*d, s, f);
  return d;
}

void
operator<< (::xercesc::DOMElement& e, const FilterOs& i)
{
  e << static_cast< const ::IFilter& > (i);

  // class
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "class",
        e));

    a << i.class_ ();
  }

  // version
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "version",
        e));

    a << i.version ();
  }

  // type
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "type",
        e));

    a << i.type ();
  }

  // edition
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "edition",
        e));

    a << i.edition ();
  }

  // sp
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "sp",
        e));

    a << i.sp ();
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

