// Copyright (c) 2005-2017 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "portableschema.h"

// EnumFilterBool
// 

EnumFilterBool::
EnumFilterBool (Value v)
: ::xml_schema::String (_xsd_EnumFilterBool_literals_[v])
{
}

EnumFilterBool::
EnumFilterBool (const char* v)
: ::xml_schema::String (v)
{
}

EnumFilterBool::
EnumFilterBool (const ::std::string& v)
: ::xml_schema::String (v)
{
}

EnumFilterBool::
EnumFilterBool (const ::xml_schema::String& v)
: ::xml_schema::String (v)
{
}

EnumFilterBool::
EnumFilterBool (const EnumFilterBool& v,
                ::xml_schema::Flags f,
                ::xml_schema::Container* c)
: ::xml_schema::String (v, f, c)
{
}

EnumFilterBool& EnumFilterBool::
operator= (Value v)
{
  static_cast< ::xml_schema::String& > (*this) = 
  ::xml_schema::String (_xsd_EnumFilterBool_literals_[v]);

  return *this;
}


// EnumTrueFalse
// 

EnumTrueFalse::
EnumTrueFalse (Value v)
: ::xml_schema::String (_xsd_EnumTrueFalse_literals_[v])
{
}

EnumTrueFalse::
EnumTrueFalse (const char* v)
: ::xml_schema::String (v)
{
}

EnumTrueFalse::
EnumTrueFalse (const ::std::string& v)
: ::xml_schema::String (v)
{
}

EnumTrueFalse::
EnumTrueFalse (const ::xml_schema::String& v)
: ::xml_schema::String (v)
{
}

EnumTrueFalse::
EnumTrueFalse (const EnumTrueFalse& v,
               ::xml_schema::Flags f,
               ::xml_schema::Container* c)
: ::xml_schema::String (v, f, c)
{
}

EnumTrueFalse& EnumTrueFalse::
operator= (Value v)
{
  static_cast< ::xml_schema::String& > (*this) = 
  ::xml_schema::String (_xsd_EnumTrueFalse_literals_[v]);

  return *this;
}


// IFilter
// 

const IFilter::BoolType& IFilter::
bool_ () const
{
  return this->bool__.get ();
}

IFilter::BoolType& IFilter::
bool_ ()
{
  return this->bool__.get ();
}

void IFilter::
bool_ (const BoolType& x)
{
  this->bool__.set (x);
}

void IFilter::
bool_ (::std::unique_ptr< BoolType > x)
{
  this->bool__.set (std::move (x));
}

const IFilter::NotType& IFilter::
not_ () const
{
  return this->not__.get ();
}

IFilter::NotType& IFilter::
not_ ()
{
  return this->not__.get ();
}

void IFilter::
not_ (const NotType& x)
{
  this->not__.set (x);
}

void IFilter::
not_ (::std::unique_ptr< NotType > x)
{
  this->not__.set (std::move (x));
}

const IFilter::HiddenOptional& IFilter::
hidden () const
{
  return this->hidden_;
}

IFilter::HiddenOptional& IFilter::
hidden ()
{
  return this->hidden_;
}

void IFilter::
hidden (const HiddenType& x)
{
  this->hidden_.set (x);
}

void IFilter::
hidden (const HiddenOptional& x)
{
  this->hidden_ = x;
}

void IFilter::
hidden (::std::unique_ptr< HiddenType > x)
{
  this->hidden_.set (std::move (x));
}


// FilterPortable
// 

const FilterPortable::UnknownType& FilterPortable::
unknown () const
{
  return this->unknown_.get ();
}

FilterPortable::UnknownType& FilterPortable::
unknown ()
{
  return this->unknown_.get ();
}

void FilterPortable::
unknown (const UnknownType& x)
{
  this->unknown_.set (x);
}

void FilterPortable::
unknown (::std::unique_ptr< UnknownType > x)
{
  this->unknown_.set (std::move (x));
}

const FilterPortable::UnknownType& FilterPortable::
unknown_default_value ()
{
  return unknown_default_value_;
}

const FilterPortable::DockedType& FilterPortable::
docked () const
{
  return this->docked_.get ();
}

FilterPortable::DockedType& FilterPortable::
docked ()
{
  return this->docked_.get ();
}

void FilterPortable::
docked (const DockedType& x)
{
  this->docked_.set (x);
}

void FilterPortable::
docked (::std::unique_ptr< DockedType > x)
{
  this->docked_.set (std::move (x));
}

const FilterPortable::DockedType& FilterPortable::
docked_default_value ()
{
  return docked_default_value_;
}

const FilterPortable::UndockedType& FilterPortable::
undocked () const
{
  return this->undocked_.get ();
}

FilterPortable::UndockedType& FilterPortable::
undocked ()
{
  return this->undocked_.get ();
}

void FilterPortable::
undocked (const UndockedType& x)
{
  this->undocked_.set (x);
}

void FilterPortable::
undocked (::std::unique_ptr< UndockedType > x)
{
  this->undocked_.set (std::move (x));
}

const FilterPortable::UndockedType& FilterPortable::
undocked_default_value ()
{
  return undocked_default_value_;
}


#include <xsd/cxx/xml/dom/wildcard-source.hxx>

#include <xsd/cxx/xml/dom/parsing-source.hxx>

#include <xsd/cxx/tree/type-factory-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_factory_plate< 0, char >
  type_factory_plate_init;
}

// EnumFilterBool
//

EnumFilterBool::
EnumFilterBool (const ::xercesc::DOMElement& e,
                ::xml_schema::Flags f,
                ::xml_schema::Container* c)
: ::xml_schema::String (e, f, c)
{
  _xsd_EnumFilterBool_convert ();
}

EnumFilterBool::
EnumFilterBool (const ::xercesc::DOMAttr& a,
                ::xml_schema::Flags f,
                ::xml_schema::Container* c)
: ::xml_schema::String (a, f, c)
{
  _xsd_EnumFilterBool_convert ();
}

EnumFilterBool::
EnumFilterBool (const ::std::string& s,
                const ::xercesc::DOMElement* e,
                ::xml_schema::Flags f,
                ::xml_schema::Container* c)
: ::xml_schema::String (s, e, f, c)
{
  _xsd_EnumFilterBool_convert ();
}

EnumFilterBool* EnumFilterBool::
_clone (::xml_schema::Flags f,
        ::xml_schema::Container* c) const
{
  return new class EnumFilterBool (*this, f, c);
}

EnumFilterBool::Value EnumFilterBool::
_xsd_EnumFilterBool_convert () const
{
  ::xsd::cxx::tree::enum_comparator< char > c (_xsd_EnumFilterBool_literals_);
  const Value* i (::std::lower_bound (
                    _xsd_EnumFilterBool_indexes_,
                    _xsd_EnumFilterBool_indexes_ + 2,
                    *this,
                    c));

  if (i == _xsd_EnumFilterBool_indexes_ + 2 || _xsd_EnumFilterBool_literals_[*i] != *this)
  {
    throw ::xsd::cxx::tree::unexpected_enumerator < char > (*this);
  }

  return *i;
}

const char* const EnumFilterBool::
_xsd_EnumFilterBool_literals_[2] =
{
  "AND",
  "OR"
};

const EnumFilterBool::Value EnumFilterBool::
_xsd_EnumFilterBool_indexes_[2] =
{
  ::EnumFilterBool::AND,
  ::EnumFilterBool::OR
};

static
const ::xsd::cxx::tree::type_factory_initializer< 0, char, EnumFilterBool >
_xsd_EnumFilterBool_type_factory_init (
  "enumFilterBool",
  "");

// EnumTrueFalse
//

EnumTrueFalse::
EnumTrueFalse (const ::xercesc::DOMElement& e,
               ::xml_schema::Flags f,
               ::xml_schema::Container* c)
: ::xml_schema::String (e, f, c)
{
  _xsd_EnumTrueFalse_convert ();
}

EnumTrueFalse::
EnumTrueFalse (const ::xercesc::DOMAttr& a,
               ::xml_schema::Flags f,
               ::xml_schema::Container* c)
: ::xml_schema::String (a, f, c)
{
  _xsd_EnumTrueFalse_convert ();
}

EnumTrueFalse::
EnumTrueFalse (const ::std::string& s,
               const ::xercesc::DOMElement* e,
               ::xml_schema::Flags f,
               ::xml_schema::Container* c)
: ::xml_schema::String (s, e, f, c)
{
  _xsd_EnumTrueFalse_convert ();
}

EnumTrueFalse* EnumTrueFalse::
_clone (::xml_schema::Flags f,
        ::xml_schema::Container* c) const
{
  return new class EnumTrueFalse (*this, f, c);
}

EnumTrueFalse::Value EnumTrueFalse::
_xsd_EnumTrueFalse_convert () const
{
  ::xsd::cxx::tree::enum_comparator< char > c (_xsd_EnumTrueFalse_literals_);
  const Value* i (::std::lower_bound (
                    _xsd_EnumTrueFalse_indexes_,
                    _xsd_EnumTrueFalse_indexes_ + 2,
                    *this,
                    c));

  if (i == _xsd_EnumTrueFalse_indexes_ + 2 || _xsd_EnumTrueFalse_literals_[*i] != *this)
  {
    throw ::xsd::cxx::tree::unexpected_enumerator < char > (*this);
  }

  return *i;
}

const char* const EnumTrueFalse::
_xsd_EnumTrueFalse_literals_[2] =
{
  "0",
  "1"
};

const EnumTrueFalse::Value EnumTrueFalse::
_xsd_EnumTrueFalse_indexes_[2] =
{
  ::EnumTrueFalse::cxx_0,
  ::EnumTrueFalse::cxx_1
};

static
const ::xsd::cxx::tree::type_factory_initializer< 0, char, EnumTrueFalse >
_xsd_EnumTrueFalse_type_factory_init (
  "enumTrueFalse",
  "");

// IFilter
//

IFilter::
IFilter (const BoolType& bool_,
         const NotType& not_)
: ::xml_schema::Type (),
  bool__ (bool_, this),
  not__ (not_, this),
  hidden_ (this)
{
}

IFilter::
IFilter (const IFilter& x,
         ::xml_schema::Flags f,
         ::xml_schema::Container* c)
: ::xml_schema::Type (x, f, c),
  bool__ (x.bool__, f, this),
  not__ (x.not__, f, this),
  hidden_ (x.hidden_, f, this)
{
}

IFilter::
IFilter (const ::xercesc::DOMElement& e,
         ::xml_schema::Flags f,
         ::xml_schema::Container* c)
: ::xml_schema::Type (e, f | ::xml_schema::Flags::base, c),
  bool__ (this),
  not__ (this),
  hidden_ (this)
{
  if ((f & ::xml_schema::Flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, false, false, true);
    this->parse (p, f);
  }
}

void IFilter::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::Flags f)
{
  while (p.more_attributes ())
  {
    const ::xercesc::DOMAttr& i (p.next_attribute ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    if (n.name () == "bool" && n.namespace_ ().empty ())
    {
      this->bool__.set (BoolTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "not" && n.namespace_ ().empty ())
    {
      this->not__.set (NotTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "hidden" && n.namespace_ ().empty ())
    {
      this->hidden_.set (HiddenTraits::create (i, f, this));
      continue;
    }
  }

  if (!bool__.present ())
  {
    throw ::xsd::cxx::tree::expected_attribute< char > (
      "bool",
      "");
  }

  if (!not__.present ())
  {
    throw ::xsd::cxx::tree::expected_attribute< char > (
      "not",
      "");
  }
}

IFilter& IFilter::
operator= (const IFilter& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::Type& > (*this) = x;
    this->bool__ = x.bool__;
    this->not__ = x.not__;
    this->hidden_ = x.hidden_;
  }

  return *this;
}

IFilter::
~IFilter ()
{
}

// FilterPortable
//

const FilterPortable::UnknownType FilterPortable::unknown_default_value_ (
  "0");

const FilterPortable::DockedType FilterPortable::docked_default_value_ (
  "0");

const FilterPortable::UndockedType FilterPortable::undocked_default_value_ (
  "0");

FilterPortable::
FilterPortable (const BoolType& bool_,
                const NotType& not_)
: ::IFilter (bool_,
             not_),
  unknown_ (unknown_default_value (), this),
  docked_ (docked_default_value (), this),
  undocked_ (undocked_default_value (), this)
{
}

FilterPortable::
FilterPortable (const FilterPortable& x,
                ::xml_schema::Flags f,
                ::xml_schema::Container* c)
: ::IFilter (x, f, c),
  unknown_ (x.unknown_, f, this),
  docked_ (x.docked_, f, this),
  undocked_ (x.undocked_, f, this)
{
}

FilterPortable::
FilterPortable (const ::xercesc::DOMElement& e,
                ::xml_schema::Flags f,
                ::xml_schema::Container* c)
: ::IFilter (e, f | ::xml_schema::Flags::base, c),
  unknown_ (this),
  docked_ (this),
  undocked_ (this)
{
  if ((f & ::xml_schema::Flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, false, false, true);
    this->parse (p, f);
  }
}

void FilterPortable::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::Flags f)
{
  this->::IFilter::parse (p, f);

  p.reset_attributes ();

  while (p.more_attributes ())
  {
    const ::xercesc::DOMAttr& i (p.next_attribute ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    if (n.name () == "unknown" && n.namespace_ ().empty ())
    {
      this->unknown_.set (UnknownTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "docked" && n.namespace_ ().empty ())
    {
      this->docked_.set (DockedTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "undocked" && n.namespace_ ().empty ())
    {
      this->undocked_.set (UndockedTraits::create (i, f, this));
      continue;
    }
  }

  if (!unknown_.present ())
  {
    this->unknown_.set (unknown_default_value ());
  }

  if (!docked_.present ())
  {
    this->docked_.set (docked_default_value ());
  }

  if (!undocked_.present ())
  {
    this->undocked_.set (undocked_default_value ());
  }
}

FilterPortable* FilterPortable::
_clone (::xml_schema::Flags f,
        ::xml_schema::Container* c) const
{
  return new class FilterPortable (*this, f, c);
}

FilterPortable& FilterPortable::
operator= (const FilterPortable& x)
{
  if (this != &x)
  {
    static_cast< ::IFilter& > (*this) = x;
    this->unknown_ = x.unknown_;
    this->docked_ = x.docked_;
    this->undocked_ = x.undocked_;
  }

  return *this;
}

FilterPortable::
~FilterPortable ()
{
}

#include <ostream>

#include <xsd/cxx/tree/std-ostream-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::std_ostream_plate< 0, char >
  std_ostream_plate_init;
}

::std::ostream&
operator<< (::std::ostream& o, EnumFilterBool::Value i)
{
  return o << EnumFilterBool::_xsd_EnumFilterBool_literals_[i];
}

::std::ostream&
operator<< (::std::ostream& o, const EnumFilterBool& i)
{
  return o << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::std_ostream_initializer< 0, char, EnumFilterBool >
_xsd_EnumFilterBool_std_ostream_init;

::std::ostream&
operator<< (::std::ostream& o, EnumTrueFalse::Value i)
{
  return o << EnumTrueFalse::_xsd_EnumTrueFalse_literals_[i];
}

::std::ostream&
operator<< (::std::ostream& o, const EnumTrueFalse& i)
{
  return o << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::std_ostream_initializer< 0, char, EnumTrueFalse >
_xsd_EnumTrueFalse_std_ostream_init;

::std::ostream&
operator<< (::std::ostream& o, const IFilter& i)
{
  o << ::std::endl << "bool: " << i.bool_ ();
  o << ::std::endl << "not: " << i.not_ ();
  if (i.hidden ())
  {
    o << ::std::endl << "hidden: " << *i.hidden ();
  }

  return o;
}

::std::ostream&
operator<< (::std::ostream& o, const FilterPortable& i)
{
  o << static_cast< const ::IFilter& > (i);

  o << ::std::endl << "unknown: " << i.unknown ();
  o << ::std::endl << "docked: " << i.docked ();
  o << ::std::endl << "undocked: " << i.undocked ();
  return o;
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

::std::unique_ptr< ::FilterPortable >
FilterPortable_ (const ::std::string& u,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  return ::std::unique_ptr< ::FilterPortable > (
    ::FilterPortable_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::FilterPortable >
FilterPortable_ (const ::std::string& u,
                 ::xml_schema::ErrorHandler& h,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::FilterPortable > (
    ::FilterPortable_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::FilterPortable >
FilterPortable_ (const ::std::string& u,
                 ::xercesc::DOMErrorHandler& h,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::FilterPortable > (
    ::FilterPortable_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::FilterPortable >
FilterPortable_ (::std::istream& is,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::FilterPortable_ (isrc, f, p);
}

::std::unique_ptr< ::FilterPortable >
FilterPortable_ (::std::istream& is,
                 ::xml_schema::ErrorHandler& h,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::FilterPortable_ (isrc, h, f, p);
}

::std::unique_ptr< ::FilterPortable >
FilterPortable_ (::std::istream& is,
                 ::xercesc::DOMErrorHandler& h,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::FilterPortable_ (isrc, h, f, p);
}

::std::unique_ptr< ::FilterPortable >
FilterPortable_ (::std::istream& is,
                 const ::std::string& sid,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::FilterPortable_ (isrc, f, p);
}

::std::unique_ptr< ::FilterPortable >
FilterPortable_ (::std::istream& is,
                 const ::std::string& sid,
                 ::xml_schema::ErrorHandler& h,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::FilterPortable_ (isrc, h, f, p);
}

::std::unique_ptr< ::FilterPortable >
FilterPortable_ (::std::istream& is,
                 const ::std::string& sid,
                 ::xercesc::DOMErrorHandler& h,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::FilterPortable_ (isrc, h, f, p);
}

::std::unique_ptr< ::FilterPortable >
FilterPortable_ (::xercesc::InputSource& i,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties& p)
{
  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  return ::std::unique_ptr< ::FilterPortable > (
    ::FilterPortable_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::FilterPortable >
FilterPortable_ (::xercesc::InputSource& i,
                 ::xml_schema::ErrorHandler& h,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::FilterPortable > (
    ::FilterPortable_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::FilterPortable >
FilterPortable_ (::xercesc::InputSource& i,
                 ::xercesc::DOMErrorHandler& h,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::FilterPortable > (
    ::FilterPortable_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::FilterPortable >
FilterPortable_ (const ::xercesc::DOMDocument& doc,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties& p)
{
  if (f & ::xml_schema::Flags::keep_dom)
  {
    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      static_cast< ::xercesc::DOMDocument* > (doc.cloneNode (true)));

    return ::std::unique_ptr< ::FilterPortable > (
      ::FilterPortable_ (
        std::move (d), f | ::xml_schema::Flags::own_dom, p));
  }

  const ::xercesc::DOMElement& e (*doc.getDocumentElement ());
  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (n.name () == "FilterPortable" &&
      n.namespace_ () == "")
  {
    ::std::unique_ptr< ::FilterPortable > r (
      ::xsd::cxx::tree::traits< ::FilterPortable, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "FilterPortable",
    "");
}

::std::unique_ptr< ::FilterPortable >
FilterPortable_ (::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties&)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > c (
    ((f & ::xml_schema::Flags::keep_dom) &&
     !(f & ::xml_schema::Flags::own_dom))
    ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
    : 0);

  ::xercesc::DOMDocument& doc (c.get () ? *c : *d);
  const ::xercesc::DOMElement& e (*doc.getDocumentElement ());

  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (f & ::xml_schema::Flags::keep_dom)
    doc.setUserData (::xml_schema::dom::tree_node_key,
                     (c.get () ? &c : &d),
                     0);

  if (n.name () == "FilterPortable" &&
      n.namespace_ () == "")
  {
    ::std::unique_ptr< ::FilterPortable > r (
      ::xsd::cxx::tree::traits< ::FilterPortable, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "FilterPortable",
    "");
}

#include <ostream>
#include <xsd/cxx/tree/error-handler.hxx>
#include <xsd/cxx/xml/dom/serialization-source.hxx>

#include <xsd/cxx/tree/type-serializer-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_serializer_plate< 0, char >
  type_serializer_plate_init;
}

void
operator<< (::xercesc::DOMElement& e, const EnumFilterBool& i)
{
  e << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xercesc::DOMAttr& a, const EnumFilterBool& i)
{
  a << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xml_schema::ListStream& l,
            const EnumFilterBool& i)
{
  l << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::type_serializer_initializer< 0, char, EnumFilterBool >
_xsd_EnumFilterBool_type_serializer_init (
  "enumFilterBool",
  "");


void
operator<< (::xercesc::DOMElement& e, const EnumTrueFalse& i)
{
  e << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xercesc::DOMAttr& a, const EnumTrueFalse& i)
{
  a << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xml_schema::ListStream& l,
            const EnumTrueFalse& i)
{
  l << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::type_serializer_initializer< 0, char, EnumTrueFalse >
_xsd_EnumTrueFalse_type_serializer_init (
  "enumTrueFalse",
  "");


void
operator<< (::xercesc::DOMElement& e, const IFilter& i)
{
  e << static_cast< const ::xml_schema::Type& > (i);

  // bool
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "bool",
        e));

    a << i.bool_ ();
  }

  // not
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "not",
        e));

    a << i.not_ ();
  }

  // hidden
  //
  if (i.hidden ())
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "hidden",
        e));

    a << *i.hidden ();
  }
}

void
FilterPortable_ (::std::ostream& o,
                 const ::FilterPortable& s,
                 const ::xml_schema::NamespaceInfomap& m,
                 const ::std::string& e,
                 ::xml_schema::Flags f)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0);

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::FilterPortable_ (s, m, f));

  ::xsd::cxx::tree::error_handler< char > h;

  ::xsd::cxx::xml::dom::ostream_format_target t (o);
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
  }
}

void
FilterPortable_ (::std::ostream& o,
                 const ::FilterPortable& s,
                 ::xml_schema::ErrorHandler& h,
                 const ::xml_schema::NamespaceInfomap& m,
                 const ::std::string& e,
                 ::xml_schema::Flags f)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0);

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::FilterPortable_ (s, m, f));
  ::xsd::cxx::xml::dom::ostream_format_target t (o);
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
FilterPortable_ (::std::ostream& o,
                 const ::FilterPortable& s,
                 ::xercesc::DOMErrorHandler& h,
                 const ::xml_schema::NamespaceInfomap& m,
                 const ::std::string& e,
                 ::xml_schema::Flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::FilterPortable_ (s, m, f));
  ::xsd::cxx::xml::dom::ostream_format_target t (o);
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
FilterPortable_ (::xercesc::XMLFormatTarget& t,
                 const ::FilterPortable& s,
                 const ::xml_schema::NamespaceInfomap& m,
                 const ::std::string& e,
                 ::xml_schema::Flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::FilterPortable_ (s, m, f));

  ::xsd::cxx::tree::error_handler< char > h;

  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
  }
}

void
FilterPortable_ (::xercesc::XMLFormatTarget& t,
                 const ::FilterPortable& s,
                 ::xml_schema::ErrorHandler& h,
                 const ::xml_schema::NamespaceInfomap& m,
                 const ::std::string& e,
                 ::xml_schema::Flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::FilterPortable_ (s, m, f));
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
FilterPortable_ (::xercesc::XMLFormatTarget& t,
                 const ::FilterPortable& s,
                 ::xercesc::DOMErrorHandler& h,
                 const ::xml_schema::NamespaceInfomap& m,
                 const ::std::string& e,
                 ::xml_schema::Flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::FilterPortable_ (s, m, f));
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
FilterPortable_ (::xercesc::DOMDocument& d,
                 const ::FilterPortable& s,
                 ::xml_schema::Flags)
{
  ::xercesc::DOMElement& e (*d.getDocumentElement ());
  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (n.name () == "FilterPortable" &&
      n.namespace_ () == "")
  {
    e << s;
  }
  else
  {
    throw ::xsd::cxx::tree::unexpected_element < char > (
      n.name (),
      n.namespace_ (),
      "FilterPortable",
      "");
  }
}

::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument >
FilterPortable_ (const ::FilterPortable& s,
                 const ::xml_schema::NamespaceInfomap& m,
                 ::xml_schema::Flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::serialize< char > (
      "FilterPortable",
      "",
      m, f));

  ::FilterPortable_ (*d, s, f);
  return d;
}

void
operator<< (::xercesc::DOMElement& e, const FilterPortable& i)
{
  e << static_cast< const ::IFilter& > (i);

  // unknown
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "unknown",
        e));

    a << i.unknown ();
  }

  // docked
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "docked",
        e));

    a << i.docked ();
  }

  // undocked
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "undocked",
        e));

    a << i.undocked ();
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

