// Copyright (c) 2005-2017 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "processingschema.h"

// EnumFilterBool
// 

EnumFilterBool::
EnumFilterBool (Value v)
: ::xml_schema::String (_xsd_EnumFilterBool_literals_[v])
{
}

EnumFilterBool::
EnumFilterBool (const char* v)
: ::xml_schema::String (v)
{
}

EnumFilterBool::
EnumFilterBool (const ::std::string& v)
: ::xml_schema::String (v)
{
}

EnumFilterBool::
EnumFilterBool (const ::xml_schema::String& v)
: ::xml_schema::String (v)
{
}

EnumFilterBool::
EnumFilterBool (const EnumFilterBool& v,
                ::xml_schema::Flags f,
                ::xml_schema::Container* c)
: ::xml_schema::String (v, f, c)
{
}

EnumFilterBool& EnumFilterBool::
operator= (Value v)
{
  static_cast< ::xml_schema::String& > (*this) = 
  ::xml_schema::String (_xsd_EnumFilterBool_literals_[v]);

  return *this;
}


// EnumTrueFalse
// 

EnumTrueFalse::
EnumTrueFalse (Value v)
: ::xml_schema::String (_xsd_EnumTrueFalse_literals_[v])
{
}

EnumTrueFalse::
EnumTrueFalse (const char* v)
: ::xml_schema::String (v)
{
}

EnumTrueFalse::
EnumTrueFalse (const ::std::string& v)
: ::xml_schema::String (v)
{
}

EnumTrueFalse::
EnumTrueFalse (const ::xml_schema::String& v)
: ::xml_schema::String (v)
{
}

EnumTrueFalse::
EnumTrueFalse (const EnumTrueFalse& v,
               ::xml_schema::Flags f,
               ::xml_schema::Container* c)
: ::xml_schema::String (v, f, c)
{
}

EnumTrueFalse& EnumTrueFalse::
operator= (Value v)
{
  static_cast< ::xml_schema::String& > (*this) = 
  ::xml_schema::String (_xsd_EnumTrueFalse_literals_[v]);

  return *this;
}


// IFilter
// 

const IFilter::BoolType& IFilter::
bool_ () const
{
  return this->bool__.get ();
}

IFilter::BoolType& IFilter::
bool_ ()
{
  return this->bool__.get ();
}

void IFilter::
bool_ (const BoolType& x)
{
  this->bool__.set (x);
}

void IFilter::
bool_ (::std::unique_ptr< BoolType > x)
{
  this->bool__.set (std::move (x));
}

const IFilter::NotType& IFilter::
not_ () const
{
  return this->not__.get ();
}

IFilter::NotType& IFilter::
not_ ()
{
  return this->not__.get ();
}

void IFilter::
not_ (const NotType& x)
{
  this->not__.set (x);
}

void IFilter::
not_ (::std::unique_ptr< NotType > x)
{
  this->not__.set (std::move (x));
}

const IFilter::HiddenOptional& IFilter::
hidden () const
{
  return this->hidden_;
}

IFilter::HiddenOptional& IFilter::
hidden ()
{
  return this->hidden_;
}

void IFilter::
hidden (const HiddenType& x)
{
  this->hidden_.set (x);
}

void IFilter::
hidden (const HiddenOptional& x)
{
  this->hidden_ = x;
}

void IFilter::
hidden (::std::unique_ptr< HiddenType > x)
{
  this->hidden_.set (std::move (x));
}


// FilterProcMode
// 

const FilterProcMode::SyncForeType& FilterProcMode::
syncFore () const
{
  return this->syncFore_.get ();
}

FilterProcMode::SyncForeType& FilterProcMode::
syncFore ()
{
  return this->syncFore_.get ();
}

void FilterProcMode::
syncFore (const SyncForeType& x)
{
  this->syncFore_.set (x);
}

void FilterProcMode::
syncFore (::std::unique_ptr< SyncForeType > x)
{
  this->syncFore_.set (std::move (x));
}

const FilterProcMode::SyncForeType& FilterProcMode::
syncFore_default_value ()
{
  return syncFore_default_value_;
}

const FilterProcMode::AsyncForeType& FilterProcMode::
asyncFore () const
{
  return this->asyncFore_.get ();
}

FilterProcMode::AsyncForeType& FilterProcMode::
asyncFore ()
{
  return this->asyncFore_.get ();
}

void FilterProcMode::
asyncFore (const AsyncForeType& x)
{
  this->asyncFore_.set (x);
}

void FilterProcMode::
asyncFore (::std::unique_ptr< AsyncForeType > x)
{
  this->asyncFore_.set (std::move (x));
}

const FilterProcMode::AsyncForeType& FilterProcMode::
asyncFore_default_value ()
{
  return asyncFore_default_value_;
}

const FilterProcMode::BackRefrType& FilterProcMode::
backRefr () const
{
  return this->backRefr_.get ();
}

FilterProcMode::BackRefrType& FilterProcMode::
backRefr ()
{
  return this->backRefr_.get ();
}

void FilterProcMode::
backRefr (const BackRefrType& x)
{
  this->backRefr_.set (x);
}

void FilterProcMode::
backRefr (::std::unique_ptr< BackRefrType > x)
{
  this->backRefr_.set (std::move (x));
}

const FilterProcMode::BackRefrType& FilterProcMode::
backRefr_default_value ()
{
  return backRefr_default_value_;
}

const FilterProcMode::ForceRefrType& FilterProcMode::
forceRefr () const
{
  return this->forceRefr_.get ();
}

FilterProcMode::ForceRefrType& FilterProcMode::
forceRefr ()
{
  return this->forceRefr_.get ();
}

void FilterProcMode::
forceRefr (const ForceRefrType& x)
{
  this->forceRefr_.set (x);
}

void FilterProcMode::
forceRefr (::std::unique_ptr< ForceRefrType > x)
{
  this->forceRefr_.set (std::move (x));
}

const FilterProcMode::ForceRefrType& FilterProcMode::
forceRefr_default_value ()
{
  return forceRefr_default_value_;
}

const FilterProcMode::LinkTrnsType& FilterProcMode::
linkTrns () const
{
  return this->linkTrns_.get ();
}

FilterProcMode::LinkTrnsType& FilterProcMode::
linkTrns ()
{
  return this->linkTrns_.get ();
}

void FilterProcMode::
linkTrns (const LinkTrnsType& x)
{
  this->linkTrns_.set (x);
}

void FilterProcMode::
linkTrns (::std::unique_ptr< LinkTrnsType > x)
{
  this->linkTrns_.set (std::move (x));
}

const FilterProcMode::LinkTrnsType& FilterProcMode::
linkTrns_default_value ()
{
  return linkTrns_default_value_;
}

const FilterProcMode::NoChgType& FilterProcMode::
noChg () const
{
  return this->noChg_.get ();
}

FilterProcMode::NoChgType& FilterProcMode::
noChg ()
{
  return this->noChg_.get ();
}

void FilterProcMode::
noChg (const NoChgType& x)
{
  this->noChg_.set (x);
}

void FilterProcMode::
noChg (::std::unique_ptr< NoChgType > x)
{
  this->noChg_.set (std::move (x));
}

const FilterProcMode::NoChgType& FilterProcMode::
noChg_default_value ()
{
  return noChg_default_value_;
}

const FilterProcMode::RsopTrnsType& FilterProcMode::
rsopTrns () const
{
  return this->rsopTrns_.get ();
}

FilterProcMode::RsopTrnsType& FilterProcMode::
rsopTrns ()
{
  return this->rsopTrns_.get ();
}

void FilterProcMode::
rsopTrns (const RsopTrnsType& x)
{
  this->rsopTrns_.set (x);
}

void FilterProcMode::
rsopTrns (::std::unique_ptr< RsopTrnsType > x)
{
  this->rsopTrns_.set (std::move (x));
}

const FilterProcMode::RsopTrnsType& FilterProcMode::
rsopTrns_default_value ()
{
  return rsopTrns_default_value_;
}

const FilterProcMode::SafeBootType& FilterProcMode::
safeBoot () const
{
  return this->safeBoot_.get ();
}

FilterProcMode::SafeBootType& FilterProcMode::
safeBoot ()
{
  return this->safeBoot_.get ();
}

void FilterProcMode::
safeBoot (const SafeBootType& x)
{
  this->safeBoot_.set (x);
}

void FilterProcMode::
safeBoot (::std::unique_ptr< SafeBootType > x)
{
  this->safeBoot_.set (std::move (x));
}

const FilterProcMode::SafeBootType& FilterProcMode::
safeBoot_default_value ()
{
  return safeBoot_default_value_;
}

const FilterProcMode::SlowLinkType& FilterProcMode::
slowLink () const
{
  return this->slowLink_.get ();
}

FilterProcMode::SlowLinkType& FilterProcMode::
slowLink ()
{
  return this->slowLink_.get ();
}

void FilterProcMode::
slowLink (const SlowLinkType& x)
{
  this->slowLink_.set (x);
}

void FilterProcMode::
slowLink (::std::unique_ptr< SlowLinkType > x)
{
  this->slowLink_.set (std::move (x));
}

const FilterProcMode::SlowLinkType& FilterProcMode::
slowLink_default_value ()
{
  return slowLink_default_value_;
}

const FilterProcMode::VerbLogType& FilterProcMode::
verbLog () const
{
  return this->verbLog_.get ();
}

FilterProcMode::VerbLogType& FilterProcMode::
verbLog ()
{
  return this->verbLog_.get ();
}

void FilterProcMode::
verbLog (const VerbLogType& x)
{
  this->verbLog_.set (x);
}

void FilterProcMode::
verbLog (::std::unique_ptr< VerbLogType > x)
{
  this->verbLog_.set (std::move (x));
}

const FilterProcMode::VerbLogType& FilterProcMode::
verbLog_default_value ()
{
  return verbLog_default_value_;
}

const FilterProcMode::RsopEnblType& FilterProcMode::
rsopEnbl () const
{
  return this->rsopEnbl_.get ();
}

FilterProcMode::RsopEnblType& FilterProcMode::
rsopEnbl ()
{
  return this->rsopEnbl_.get ();
}

void FilterProcMode::
rsopEnbl (const RsopEnblType& x)
{
  this->rsopEnbl_.set (x);
}

void FilterProcMode::
rsopEnbl (::std::unique_ptr< RsopEnblType > x)
{
  this->rsopEnbl_.set (std::move (x));
}

const FilterProcMode::RsopEnblType& FilterProcMode::
rsopEnbl_default_value ()
{
  return rsopEnbl_default_value_;
}


#include <xsd/cxx/xml/dom/wildcard-source.hxx>

#include <xsd/cxx/xml/dom/parsing-source.hxx>

#include <xsd/cxx/tree/type-factory-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_factory_plate< 0, char >
  type_factory_plate_init;
}

// EnumFilterBool
//

EnumFilterBool::
EnumFilterBool (const ::xercesc::DOMElement& e,
                ::xml_schema::Flags f,
                ::xml_schema::Container* c)
: ::xml_schema::String (e, f, c)
{
  _xsd_EnumFilterBool_convert ();
}

EnumFilterBool::
EnumFilterBool (const ::xercesc::DOMAttr& a,
                ::xml_schema::Flags f,
                ::xml_schema::Container* c)
: ::xml_schema::String (a, f, c)
{
  _xsd_EnumFilterBool_convert ();
}

EnumFilterBool::
EnumFilterBool (const ::std::string& s,
                const ::xercesc::DOMElement* e,
                ::xml_schema::Flags f,
                ::xml_schema::Container* c)
: ::xml_schema::String (s, e, f, c)
{
  _xsd_EnumFilterBool_convert ();
}

EnumFilterBool* EnumFilterBool::
_clone (::xml_schema::Flags f,
        ::xml_schema::Container* c) const
{
  return new class EnumFilterBool (*this, f, c);
}

EnumFilterBool::Value EnumFilterBool::
_xsd_EnumFilterBool_convert () const
{
  ::xsd::cxx::tree::enum_comparator< char > c (_xsd_EnumFilterBool_literals_);
  const Value* i (::std::lower_bound (
                    _xsd_EnumFilterBool_indexes_,
                    _xsd_EnumFilterBool_indexes_ + 2,
                    *this,
                    c));

  if (i == _xsd_EnumFilterBool_indexes_ + 2 || _xsd_EnumFilterBool_literals_[*i] != *this)
  {
    throw ::xsd::cxx::tree::unexpected_enumerator < char > (*this);
  }

  return *i;
}

const char* const EnumFilterBool::
_xsd_EnumFilterBool_literals_[2] =
{
  "AND",
  "OR"
};

const EnumFilterBool::Value EnumFilterBool::
_xsd_EnumFilterBool_indexes_[2] =
{
  ::EnumFilterBool::AND,
  ::EnumFilterBool::OR
};

static
const ::xsd::cxx::tree::type_factory_initializer< 0, char, EnumFilterBool >
_xsd_EnumFilterBool_type_factory_init (
  "enumFilterBool",
  "");

// EnumTrueFalse
//

EnumTrueFalse::
EnumTrueFalse (const ::xercesc::DOMElement& e,
               ::xml_schema::Flags f,
               ::xml_schema::Container* c)
: ::xml_schema::String (e, f, c)
{
  _xsd_EnumTrueFalse_convert ();
}

EnumTrueFalse::
EnumTrueFalse (const ::xercesc::DOMAttr& a,
               ::xml_schema::Flags f,
               ::xml_schema::Container* c)
: ::xml_schema::String (a, f, c)
{
  _xsd_EnumTrueFalse_convert ();
}

EnumTrueFalse::
EnumTrueFalse (const ::std::string& s,
               const ::xercesc::DOMElement* e,
               ::xml_schema::Flags f,
               ::xml_schema::Container* c)
: ::xml_schema::String (s, e, f, c)
{
  _xsd_EnumTrueFalse_convert ();
}

EnumTrueFalse* EnumTrueFalse::
_clone (::xml_schema::Flags f,
        ::xml_schema::Container* c) const
{
  return new class EnumTrueFalse (*this, f, c);
}

EnumTrueFalse::Value EnumTrueFalse::
_xsd_EnumTrueFalse_convert () const
{
  ::xsd::cxx::tree::enum_comparator< char > c (_xsd_EnumTrueFalse_literals_);
  const Value* i (::std::lower_bound (
                    _xsd_EnumTrueFalse_indexes_,
                    _xsd_EnumTrueFalse_indexes_ + 2,
                    *this,
                    c));

  if (i == _xsd_EnumTrueFalse_indexes_ + 2 || _xsd_EnumTrueFalse_literals_[*i] != *this)
  {
    throw ::xsd::cxx::tree::unexpected_enumerator < char > (*this);
  }

  return *i;
}

const char* const EnumTrueFalse::
_xsd_EnumTrueFalse_literals_[2] =
{
  "0",
  "1"
};

const EnumTrueFalse::Value EnumTrueFalse::
_xsd_EnumTrueFalse_indexes_[2] =
{
  ::EnumTrueFalse::cxx_0,
  ::EnumTrueFalse::cxx_1
};

static
const ::xsd::cxx::tree::type_factory_initializer< 0, char, EnumTrueFalse >
_xsd_EnumTrueFalse_type_factory_init (
  "enumTrueFalse",
  "");

// IFilter
//

IFilter::
IFilter (const BoolType& bool_,
         const NotType& not_)
: ::xml_schema::Type (),
  bool__ (bool_, this),
  not__ (not_, this),
  hidden_ (this)
{
}

IFilter::
IFilter (const IFilter& x,
         ::xml_schema::Flags f,
         ::xml_schema::Container* c)
: ::xml_schema::Type (x, f, c),
  bool__ (x.bool__, f, this),
  not__ (x.not__, f, this),
  hidden_ (x.hidden_, f, this)
{
}

IFilter::
IFilter (const ::xercesc::DOMElement& e,
         ::xml_schema::Flags f,
         ::xml_schema::Container* c)
: ::xml_schema::Type (e, f | ::xml_schema::Flags::base, c),
  bool__ (this),
  not__ (this),
  hidden_ (this)
{
  if ((f & ::xml_schema::Flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, false, false, true);
    this->parse (p, f);
  }
}

void IFilter::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::Flags f)
{
  while (p.more_attributes ())
  {
    const ::xercesc::DOMAttr& i (p.next_attribute ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    if (n.name () == "bool" && n.namespace_ ().empty ())
    {
      this->bool__.set (BoolTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "not" && n.namespace_ ().empty ())
    {
      this->not__.set (NotTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "hidden" && n.namespace_ ().empty ())
    {
      this->hidden_.set (HiddenTraits::create (i, f, this));
      continue;
    }
  }

  if (!bool__.present ())
  {
    throw ::xsd::cxx::tree::expected_attribute< char > (
      "bool",
      "");
  }

  if (!not__.present ())
  {
    throw ::xsd::cxx::tree::expected_attribute< char > (
      "not",
      "");
  }
}

IFilter& IFilter::
operator= (const IFilter& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::Type& > (*this) = x;
    this->bool__ = x.bool__;
    this->not__ = x.not__;
    this->hidden_ = x.hidden_;
  }

  return *this;
}

IFilter::
~IFilter ()
{
}

// FilterProcMode
//

const FilterProcMode::SyncForeType FilterProcMode::syncFore_default_value_ (
  "0");

const FilterProcMode::AsyncForeType FilterProcMode::asyncFore_default_value_ (
  "0");

const FilterProcMode::BackRefrType FilterProcMode::backRefr_default_value_ (
  "0");

const FilterProcMode::ForceRefrType FilterProcMode::forceRefr_default_value_ (
  "0");

const FilterProcMode::LinkTrnsType FilterProcMode::linkTrns_default_value_ (
  "0");

const FilterProcMode::NoChgType FilterProcMode::noChg_default_value_ (
  "0");

const FilterProcMode::RsopTrnsType FilterProcMode::rsopTrns_default_value_ (
  "0");

const FilterProcMode::SafeBootType FilterProcMode::safeBoot_default_value_ (
  "0");

const FilterProcMode::SlowLinkType FilterProcMode::slowLink_default_value_ (
  "0");

const FilterProcMode::VerbLogType FilterProcMode::verbLog_default_value_ (
  "0");

const FilterProcMode::RsopEnblType FilterProcMode::rsopEnbl_default_value_ (
  "0");

FilterProcMode::
FilterProcMode (const BoolType& bool_,
                const NotType& not_)
: ::IFilter (bool_,
             not_),
  syncFore_ (syncFore_default_value (), this),
  asyncFore_ (asyncFore_default_value (), this),
  backRefr_ (backRefr_default_value (), this),
  forceRefr_ (forceRefr_default_value (), this),
  linkTrns_ (linkTrns_default_value (), this),
  noChg_ (noChg_default_value (), this),
  rsopTrns_ (rsopTrns_default_value (), this),
  safeBoot_ (safeBoot_default_value (), this),
  slowLink_ (slowLink_default_value (), this),
  verbLog_ (verbLog_default_value (), this),
  rsopEnbl_ (rsopEnbl_default_value (), this)
{
}

FilterProcMode::
FilterProcMode (const FilterProcMode& x,
                ::xml_schema::Flags f,
                ::xml_schema::Container* c)
: ::IFilter (x, f, c),
  syncFore_ (x.syncFore_, f, this),
  asyncFore_ (x.asyncFore_, f, this),
  backRefr_ (x.backRefr_, f, this),
  forceRefr_ (x.forceRefr_, f, this),
  linkTrns_ (x.linkTrns_, f, this),
  noChg_ (x.noChg_, f, this),
  rsopTrns_ (x.rsopTrns_, f, this),
  safeBoot_ (x.safeBoot_, f, this),
  slowLink_ (x.slowLink_, f, this),
  verbLog_ (x.verbLog_, f, this),
  rsopEnbl_ (x.rsopEnbl_, f, this)
{
}

FilterProcMode::
FilterProcMode (const ::xercesc::DOMElement& e,
                ::xml_schema::Flags f,
                ::xml_schema::Container* c)
: ::IFilter (e, f | ::xml_schema::Flags::base, c),
  syncFore_ (this),
  asyncFore_ (this),
  backRefr_ (this),
  forceRefr_ (this),
  linkTrns_ (this),
  noChg_ (this),
  rsopTrns_ (this),
  safeBoot_ (this),
  slowLink_ (this),
  verbLog_ (this),
  rsopEnbl_ (this)
{
  if ((f & ::xml_schema::Flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, false, false, true);
    this->parse (p, f);
  }
}

void FilterProcMode::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::Flags f)
{
  this->::IFilter::parse (p, f);

  p.reset_attributes ();

  while (p.more_attributes ())
  {
    const ::xercesc::DOMAttr& i (p.next_attribute ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    if (n.name () == "syncFore" && n.namespace_ ().empty ())
    {
      this->syncFore_.set (SyncForeTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "asyncFore" && n.namespace_ ().empty ())
    {
      this->asyncFore_.set (AsyncForeTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "backRefr" && n.namespace_ ().empty ())
    {
      this->backRefr_.set (BackRefrTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "forceRefr" && n.namespace_ ().empty ())
    {
      this->forceRefr_.set (ForceRefrTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "linkTrns" && n.namespace_ ().empty ())
    {
      this->linkTrns_.set (LinkTrnsTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "noChg" && n.namespace_ ().empty ())
    {
      this->noChg_.set (NoChgTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "rsopTrns" && n.namespace_ ().empty ())
    {
      this->rsopTrns_.set (RsopTrnsTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "safeBoot" && n.namespace_ ().empty ())
    {
      this->safeBoot_.set (SafeBootTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "slowLink" && n.namespace_ ().empty ())
    {
      this->slowLink_.set (SlowLinkTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "verbLog" && n.namespace_ ().empty ())
    {
      this->verbLog_.set (VerbLogTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "rsopEnbl" && n.namespace_ ().empty ())
    {
      this->rsopEnbl_.set (RsopEnblTraits::create (i, f, this));
      continue;
    }
  }

  if (!syncFore_.present ())
  {
    this->syncFore_.set (syncFore_default_value ());
  }

  if (!asyncFore_.present ())
  {
    this->asyncFore_.set (asyncFore_default_value ());
  }

  if (!backRefr_.present ())
  {
    this->backRefr_.set (backRefr_default_value ());
  }

  if (!forceRefr_.present ())
  {
    this->forceRefr_.set (forceRefr_default_value ());
  }

  if (!linkTrns_.present ())
  {
    this->linkTrns_.set (linkTrns_default_value ());
  }

  if (!noChg_.present ())
  {
    this->noChg_.set (noChg_default_value ());
  }

  if (!rsopTrns_.present ())
  {
    this->rsopTrns_.set (rsopTrns_default_value ());
  }

  if (!safeBoot_.present ())
  {
    this->safeBoot_.set (safeBoot_default_value ());
  }

  if (!slowLink_.present ())
  {
    this->slowLink_.set (slowLink_default_value ());
  }

  if (!verbLog_.present ())
  {
    this->verbLog_.set (verbLog_default_value ());
  }

  if (!rsopEnbl_.present ())
  {
    this->rsopEnbl_.set (rsopEnbl_default_value ());
  }
}

FilterProcMode* FilterProcMode::
_clone (::xml_schema::Flags f,
        ::xml_schema::Container* c) const
{
  return new class FilterProcMode (*this, f, c);
}

FilterProcMode& FilterProcMode::
operator= (const FilterProcMode& x)
{
  if (this != &x)
  {
    static_cast< ::IFilter& > (*this) = x;
    this->syncFore_ = x.syncFore_;
    this->asyncFore_ = x.asyncFore_;
    this->backRefr_ = x.backRefr_;
    this->forceRefr_ = x.forceRefr_;
    this->linkTrns_ = x.linkTrns_;
    this->noChg_ = x.noChg_;
    this->rsopTrns_ = x.rsopTrns_;
    this->safeBoot_ = x.safeBoot_;
    this->slowLink_ = x.slowLink_;
    this->verbLog_ = x.verbLog_;
    this->rsopEnbl_ = x.rsopEnbl_;
  }

  return *this;
}

FilterProcMode::
~FilterProcMode ()
{
}

#include <ostream>

#include <xsd/cxx/tree/std-ostream-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::std_ostream_plate< 0, char >
  std_ostream_plate_init;
}

::std::ostream&
operator<< (::std::ostream& o, EnumFilterBool::Value i)
{
  return o << EnumFilterBool::_xsd_EnumFilterBool_literals_[i];
}

::std::ostream&
operator<< (::std::ostream& o, const EnumFilterBool& i)
{
  return o << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::std_ostream_initializer< 0, char, EnumFilterBool >
_xsd_EnumFilterBool_std_ostream_init;

::std::ostream&
operator<< (::std::ostream& o, EnumTrueFalse::Value i)
{
  return o << EnumTrueFalse::_xsd_EnumTrueFalse_literals_[i];
}

::std::ostream&
operator<< (::std::ostream& o, const EnumTrueFalse& i)
{
  return o << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::std_ostream_initializer< 0, char, EnumTrueFalse >
_xsd_EnumTrueFalse_std_ostream_init;

::std::ostream&
operator<< (::std::ostream& o, const IFilter& i)
{
  o << ::std::endl << "bool: " << i.bool_ ();
  o << ::std::endl << "not: " << i.not_ ();
  if (i.hidden ())
  {
    o << ::std::endl << "hidden: " << *i.hidden ();
  }

  return o;
}

::std::ostream&
operator<< (::std::ostream& o, const FilterProcMode& i)
{
  o << static_cast< const ::IFilter& > (i);

  o << ::std::endl << "syncFore: " << i.syncFore ();
  o << ::std::endl << "asyncFore: " << i.asyncFore ();
  o << ::std::endl << "backRefr: " << i.backRefr ();
  o << ::std::endl << "forceRefr: " << i.forceRefr ();
  o << ::std::endl << "linkTrns: " << i.linkTrns ();
  o << ::std::endl << "noChg: " << i.noChg ();
  o << ::std::endl << "rsopTrns: " << i.rsopTrns ();
  o << ::std::endl << "safeBoot: " << i.safeBoot ();
  o << ::std::endl << "slowLink: " << i.slowLink ();
  o << ::std::endl << "verbLog: " << i.verbLog ();
  o << ::std::endl << "rsopEnbl: " << i.rsopEnbl ();
  return o;
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

::std::unique_ptr< ::FilterProcMode >
FilterProcMode_ (const ::std::string& u,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  return ::std::unique_ptr< ::FilterProcMode > (
    ::FilterProcMode_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::FilterProcMode >
FilterProcMode_ (const ::std::string& u,
                 ::xml_schema::ErrorHandler& h,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::FilterProcMode > (
    ::FilterProcMode_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::FilterProcMode >
FilterProcMode_ (const ::std::string& u,
                 ::xercesc::DOMErrorHandler& h,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::FilterProcMode > (
    ::FilterProcMode_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::FilterProcMode >
FilterProcMode_ (::std::istream& is,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::FilterProcMode_ (isrc, f, p);
}

::std::unique_ptr< ::FilterProcMode >
FilterProcMode_ (::std::istream& is,
                 ::xml_schema::ErrorHandler& h,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::FilterProcMode_ (isrc, h, f, p);
}

::std::unique_ptr< ::FilterProcMode >
FilterProcMode_ (::std::istream& is,
                 ::xercesc::DOMErrorHandler& h,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::FilterProcMode_ (isrc, h, f, p);
}

::std::unique_ptr< ::FilterProcMode >
FilterProcMode_ (::std::istream& is,
                 const ::std::string& sid,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::FilterProcMode_ (isrc, f, p);
}

::std::unique_ptr< ::FilterProcMode >
FilterProcMode_ (::std::istream& is,
                 const ::std::string& sid,
                 ::xml_schema::ErrorHandler& h,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::FilterProcMode_ (isrc, h, f, p);
}

::std::unique_ptr< ::FilterProcMode >
FilterProcMode_ (::std::istream& is,
                 const ::std::string& sid,
                 ::xercesc::DOMErrorHandler& h,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::FilterProcMode_ (isrc, h, f, p);
}

::std::unique_ptr< ::FilterProcMode >
FilterProcMode_ (::xercesc::InputSource& i,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties& p)
{
  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  return ::std::unique_ptr< ::FilterProcMode > (
    ::FilterProcMode_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::FilterProcMode >
FilterProcMode_ (::xercesc::InputSource& i,
                 ::xml_schema::ErrorHandler& h,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::FilterProcMode > (
    ::FilterProcMode_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::FilterProcMode >
FilterProcMode_ (::xercesc::InputSource& i,
                 ::xercesc::DOMErrorHandler& h,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::FilterProcMode > (
    ::FilterProcMode_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::FilterProcMode >
FilterProcMode_ (const ::xercesc::DOMDocument& doc,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties& p)
{
  if (f & ::xml_schema::Flags::keep_dom)
  {
    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      static_cast< ::xercesc::DOMDocument* > (doc.cloneNode (true)));

    return ::std::unique_ptr< ::FilterProcMode > (
      ::FilterProcMode_ (
        std::move (d), f | ::xml_schema::Flags::own_dom, p));
  }

  const ::xercesc::DOMElement& e (*doc.getDocumentElement ());
  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (n.name () == "FilterProcMode" &&
      n.namespace_ () == "")
  {
    ::std::unique_ptr< ::FilterProcMode > r (
      ::xsd::cxx::tree::traits< ::FilterProcMode, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "FilterProcMode",
    "");
}

::std::unique_ptr< ::FilterProcMode >
FilterProcMode_ (::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties&)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > c (
    ((f & ::xml_schema::Flags::keep_dom) &&
     !(f & ::xml_schema::Flags::own_dom))
    ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
    : 0);

  ::xercesc::DOMDocument& doc (c.get () ? *c : *d);
  const ::xercesc::DOMElement& e (*doc.getDocumentElement ());

  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (f & ::xml_schema::Flags::keep_dom)
    doc.setUserData (::xml_schema::dom::tree_node_key,
                     (c.get () ? &c : &d),
                     0);

  if (n.name () == "FilterProcMode" &&
      n.namespace_ () == "")
  {
    ::std::unique_ptr< ::FilterProcMode > r (
      ::xsd::cxx::tree::traits< ::FilterProcMode, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "FilterProcMode",
    "");
}

#include <ostream>
#include <xsd/cxx/tree/error-handler.hxx>
#include <xsd/cxx/xml/dom/serialization-source.hxx>

#include <xsd/cxx/tree/type-serializer-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_serializer_plate< 0, char >
  type_serializer_plate_init;
}

void
operator<< (::xercesc::DOMElement& e, const EnumFilterBool& i)
{
  e << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xercesc::DOMAttr& a, const EnumFilterBool& i)
{
  a << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xml_schema::ListStream& l,
            const EnumFilterBool& i)
{
  l << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::type_serializer_initializer< 0, char, EnumFilterBool >
_xsd_EnumFilterBool_type_serializer_init (
  "enumFilterBool",
  "");


void
operator<< (::xercesc::DOMElement& e, const EnumTrueFalse& i)
{
  e << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xercesc::DOMAttr& a, const EnumTrueFalse& i)
{
  a << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xml_schema::ListStream& l,
            const EnumTrueFalse& i)
{
  l << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::type_serializer_initializer< 0, char, EnumTrueFalse >
_xsd_EnumTrueFalse_type_serializer_init (
  "enumTrueFalse",
  "");


void
operator<< (::xercesc::DOMElement& e, const IFilter& i)
{
  e << static_cast< const ::xml_schema::Type& > (i);

  // bool
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "bool",
        e));

    a << i.bool_ ();
  }

  // not
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "not",
        e));

    a << i.not_ ();
  }

  // hidden
  //
  if (i.hidden ())
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "hidden",
        e));

    a << *i.hidden ();
  }
}

void
FilterProcMode_ (::std::ostream& o,
                 const ::FilterProcMode& s,
                 const ::xml_schema::NamespaceInfomap& m,
                 const ::std::string& e,
                 ::xml_schema::Flags f)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0);

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::FilterProcMode_ (s, m, f));

  ::xsd::cxx::tree::error_handler< char > h;

  ::xsd::cxx::xml::dom::ostream_format_target t (o);
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
  }
}

void
FilterProcMode_ (::std::ostream& o,
                 const ::FilterProcMode& s,
                 ::xml_schema::ErrorHandler& h,
                 const ::xml_schema::NamespaceInfomap& m,
                 const ::std::string& e,
                 ::xml_schema::Flags f)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0);

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::FilterProcMode_ (s, m, f));
  ::xsd::cxx::xml::dom::ostream_format_target t (o);
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
FilterProcMode_ (::std::ostream& o,
                 const ::FilterProcMode& s,
                 ::xercesc::DOMErrorHandler& h,
                 const ::xml_schema::NamespaceInfomap& m,
                 const ::std::string& e,
                 ::xml_schema::Flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::FilterProcMode_ (s, m, f));
  ::xsd::cxx::xml::dom::ostream_format_target t (o);
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
FilterProcMode_ (::xercesc::XMLFormatTarget& t,
                 const ::FilterProcMode& s,
                 const ::xml_schema::NamespaceInfomap& m,
                 const ::std::string& e,
                 ::xml_schema::Flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::FilterProcMode_ (s, m, f));

  ::xsd::cxx::tree::error_handler< char > h;

  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
  }
}

void
FilterProcMode_ (::xercesc::XMLFormatTarget& t,
                 const ::FilterProcMode& s,
                 ::xml_schema::ErrorHandler& h,
                 const ::xml_schema::NamespaceInfomap& m,
                 const ::std::string& e,
                 ::xml_schema::Flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::FilterProcMode_ (s, m, f));
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
FilterProcMode_ (::xercesc::XMLFormatTarget& t,
                 const ::FilterProcMode& s,
                 ::xercesc::DOMErrorHandler& h,
                 const ::xml_schema::NamespaceInfomap& m,
                 const ::std::string& e,
                 ::xml_schema::Flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::FilterProcMode_ (s, m, f));
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
FilterProcMode_ (::xercesc::DOMDocument& d,
                 const ::FilterProcMode& s,
                 ::xml_schema::Flags)
{
  ::xercesc::DOMElement& e (*d.getDocumentElement ());
  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (n.name () == "FilterProcMode" &&
      n.namespace_ () == "")
  {
    e << s;
  }
  else
  {
    throw ::xsd::cxx::tree::unexpected_element < char > (
      n.name (),
      n.namespace_ (),
      "FilterProcMode",
      "");
  }
}

::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument >
FilterProcMode_ (const ::FilterProcMode& s,
                 const ::xml_schema::NamespaceInfomap& m,
                 ::xml_schema::Flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::serialize< char > (
      "FilterProcMode",
      "",
      m, f));

  ::FilterProcMode_ (*d, s, f);
  return d;
}

void
operator<< (::xercesc::DOMElement& e, const FilterProcMode& i)
{
  e << static_cast< const ::IFilter& > (i);

  // syncFore
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "syncFore",
        e));

    a << i.syncFore ();
  }

  // asyncFore
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "asyncFore",
        e));

    a << i.asyncFore ();
  }

  // backRefr
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "backRefr",
        e));

    a << i.backRefr ();
  }

  // forceRefr
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "forceRefr",
        e));

    a << i.forceRefr ();
  }

  // linkTrns
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "linkTrns",
        e));

    a << i.linkTrns ();
  }

  // noChg
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "noChg",
        e));

    a << i.noChg ();
  }

  // rsopTrns
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "rsopTrns",
        e));

    a << i.rsopTrns ();
  }

  // safeBoot
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "safeBoot",
        e));

    a << i.safeBoot ();
  }

  // slowLink
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "slowLink",
        e));

    a << i.slowLink ();
  }

  // verbLog
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "verbLog",
        e));

    a << i.verbLog ();
  }

  // rsopEnbl
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "rsopEnbl",
        e));

    a << i.rsopEnbl ();
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

