// Copyright (c) 2005-2017 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "registryschema.h"

// EnumFilterBool
// 

EnumFilterBool::
EnumFilterBool (Value v)
: ::xml_schema::String (_xsd_EnumFilterBool_literals_[v])
{
}

EnumFilterBool::
EnumFilterBool (const char* v)
: ::xml_schema::String (v)
{
}

EnumFilterBool::
EnumFilterBool (const ::std::string& v)
: ::xml_schema::String (v)
{
}

EnumFilterBool::
EnumFilterBool (const ::xml_schema::String& v)
: ::xml_schema::String (v)
{
}

EnumFilterBool::
EnumFilterBool (const EnumFilterBool& v,
                ::xml_schema::Flags f,
                ::xml_schema::Container* c)
: ::xml_schema::String (v, f, c)
{
}

EnumFilterBool& EnumFilterBool::
operator= (Value v)
{
  static_cast< ::xml_schema::String& > (*this) = 
  ::xml_schema::String (_xsd_EnumFilterBool_literals_[v]);

  return *this;
}


// EnumTrueFalse
// 

EnumTrueFalse::
EnumTrueFalse (Value v)
: ::xml_schema::String (_xsd_EnumTrueFalse_literals_[v])
{
}

EnumTrueFalse::
EnumTrueFalse (const char* v)
: ::xml_schema::String (v)
{
}

EnumTrueFalse::
EnumTrueFalse (const ::std::string& v)
: ::xml_schema::String (v)
{
}

EnumTrueFalse::
EnumTrueFalse (const ::xml_schema::String& v)
: ::xml_schema::String (v)
{
}

EnumTrueFalse::
EnumTrueFalse (const EnumTrueFalse& v,
               ::xml_schema::Flags f,
               ::xml_schema::Container* c)
: ::xml_schema::String (v, f, c)
{
}

EnumTrueFalse& EnumTrueFalse::
operator= (Value v)
{
  static_cast< ::xml_schema::String& > (*this) = 
  ::xml_schema::String (_xsd_EnumTrueFalse_literals_[v]);

  return *this;
}


// EnumFilterRegistryHive
// 

EnumFilterRegistryHive::
EnumFilterRegistryHive (Value v)
: ::xml_schema::String (_xsd_EnumFilterRegistryHive_literals_[v])
{
}

EnumFilterRegistryHive::
EnumFilterRegistryHive (const char* v)
: ::xml_schema::String (v)
{
}

EnumFilterRegistryHive::
EnumFilterRegistryHive (const ::std::string& v)
: ::xml_schema::String (v)
{
}

EnumFilterRegistryHive::
EnumFilterRegistryHive (const ::xml_schema::String& v)
: ::xml_schema::String (v)
{
}

EnumFilterRegistryHive::
EnumFilterRegistryHive (const EnumFilterRegistryHive& v,
                        ::xml_schema::Flags f,
                        ::xml_schema::Container* c)
: ::xml_schema::String (v, f, c)
{
}

EnumFilterRegistryHive& EnumFilterRegistryHive::
operator= (Value v)
{
  static_cast< ::xml_schema::String& > (*this) = 
  ::xml_schema::String (_xsd_EnumFilterRegistryHive_literals_[v]);

  return *this;
}


// EnumFilterRegistryValueType
// 

EnumFilterRegistryValueType::
EnumFilterRegistryValueType (Value v)
: ::xml_schema::String (_xsd_EnumFilterRegistryValueType_literals_[v])
{
}

EnumFilterRegistryValueType::
EnumFilterRegistryValueType (const char* v)
: ::xml_schema::String (v)
{
}

EnumFilterRegistryValueType::
EnumFilterRegistryValueType (const ::std::string& v)
: ::xml_schema::String (v)
{
}

EnumFilterRegistryValueType::
EnumFilterRegistryValueType (const ::xml_schema::String& v)
: ::xml_schema::String (v)
{
}

EnumFilterRegistryValueType::
EnumFilterRegistryValueType (const EnumFilterRegistryValueType& v,
                             ::xml_schema::Flags f,
                             ::xml_schema::Container* c)
: ::xml_schema::String (v, f, c)
{
}

EnumFilterRegistryValueType& EnumFilterRegistryValueType::
operator= (Value v)
{
  static_cast< ::xml_schema::String& > (*this) = 
  ::xml_schema::String (_xsd_EnumFilterRegistryValueType_literals_[v]);

  return *this;
}


// EnumFilterRegistrySubType
// 

EnumFilterRegistrySubType::
EnumFilterRegistrySubType (Value v)
: ::xml_schema::String (_xsd_EnumFilterRegistrySubType_literals_[v])
{
}

EnumFilterRegistrySubType::
EnumFilterRegistrySubType (const char* v)
: ::xml_schema::String (v)
{
}

EnumFilterRegistrySubType::
EnumFilterRegistrySubType (const ::std::string& v)
: ::xml_schema::String (v)
{
}

EnumFilterRegistrySubType::
EnumFilterRegistrySubType (const ::xml_schema::String& v)
: ::xml_schema::String (v)
{
}

EnumFilterRegistrySubType::
EnumFilterRegistrySubType (const EnumFilterRegistrySubType& v,
                           ::xml_schema::Flags f,
                           ::xml_schema::Container* c)
: ::xml_schema::String (v, f, c)
{
}

EnumFilterRegistrySubType& EnumFilterRegistrySubType::
operator= (Value v)
{
  static_cast< ::xml_schema::String& > (*this) = 
  ::xml_schema::String (_xsd_EnumFilterRegistrySubType_literals_[v]);

  return *this;
}


// EnumFilterRegistryType
// 

EnumFilterRegistryType::
EnumFilterRegistryType (Value v)
: ::xml_schema::String (_xsd_EnumFilterRegistryType_literals_[v])
{
}

EnumFilterRegistryType::
EnumFilterRegistryType (const char* v)
: ::xml_schema::String (v)
{
}

EnumFilterRegistryType::
EnumFilterRegistryType (const ::std::string& v)
: ::xml_schema::String (v)
{
}

EnumFilterRegistryType::
EnumFilterRegistryType (const ::xml_schema::String& v)
: ::xml_schema::String (v)
{
}

EnumFilterRegistryType::
EnumFilterRegistryType (const EnumFilterRegistryType& v,
                        ::xml_schema::Flags f,
                        ::xml_schema::Container* c)
: ::xml_schema::String (v, f, c)
{
}

EnumFilterRegistryType& EnumFilterRegistryType::
operator= (Value v)
{
  static_cast< ::xml_schema::String& > (*this) = 
  ::xml_schema::String (_xsd_EnumFilterRegistryType_literals_[v]);

  return *this;
}


// IFilter
// 

const IFilter::BoolType& IFilter::
bool_ () const
{
  return this->bool__.get ();
}

IFilter::BoolType& IFilter::
bool_ ()
{
  return this->bool__.get ();
}

void IFilter::
bool_ (const BoolType& x)
{
  this->bool__.set (x);
}

void IFilter::
bool_ (::std::unique_ptr< BoolType > x)
{
  this->bool__.set (std::move (x));
}

const IFilter::NotType& IFilter::
not_ () const
{
  return this->not__.get ();
}

IFilter::NotType& IFilter::
not_ ()
{
  return this->not__.get ();
}

void IFilter::
not_ (const NotType& x)
{
  this->not__.set (x);
}

void IFilter::
not_ (::std::unique_ptr< NotType > x)
{
  this->not__.set (std::move (x));
}

const IFilter::HiddenOptional& IFilter::
hidden () const
{
  return this->hidden_;
}

IFilter::HiddenOptional& IFilter::
hidden ()
{
  return this->hidden_;
}

void IFilter::
hidden (const HiddenType& x)
{
  this->hidden_.set (x);
}

void IFilter::
hidden (const HiddenOptional& x)
{
  this->hidden_ = x;
}

void IFilter::
hidden (::std::unique_ptr< HiddenType > x)
{
  this->hidden_.set (std::move (x));
}


// FilterRegistry
// 

const FilterRegistry::TypeType& FilterRegistry::
type () const
{
  return this->type_.get ();
}

FilterRegistry::TypeType& FilterRegistry::
type ()
{
  return this->type_.get ();
}

void FilterRegistry::
type (const TypeType& x)
{
  this->type_.set (x);
}

void FilterRegistry::
type (::std::unique_ptr< TypeType > x)
{
  this->type_.set (std::move (x));
}

const FilterRegistry::TypeType& FilterRegistry::
type_default_value ()
{
  return type_default_value_;
}

const FilterRegistry::SubtypeType& FilterRegistry::
subtype () const
{
  return this->subtype_.get ();
}

FilterRegistry::SubtypeType& FilterRegistry::
subtype ()
{
  return this->subtype_.get ();
}

void FilterRegistry::
subtype (const SubtypeType& x)
{
  this->subtype_.set (x);
}

void FilterRegistry::
subtype (::std::unique_ptr< SubtypeType > x)
{
  this->subtype_.set (std::move (x));
}

const FilterRegistry::SubtypeType& FilterRegistry::
subtype_default_value ()
{
  return subtype_default_value_;
}

const FilterRegistry::ValueNameOptional& FilterRegistry::
valueName () const
{
  return this->valueName_;
}

FilterRegistry::ValueNameOptional& FilterRegistry::
valueName ()
{
  return this->valueName_;
}

void FilterRegistry::
valueName (const ValueNameType& x)
{
  this->valueName_.set (x);
}

void FilterRegistry::
valueName (const ValueNameOptional& x)
{
  this->valueName_ = x;
}

void FilterRegistry::
valueName (::std::unique_ptr< ValueNameType > x)
{
  this->valueName_.set (std::move (x));
}

const FilterRegistry::ValueTypeType& FilterRegistry::
valueType () const
{
  return this->valueType_.get ();
}

FilterRegistry::ValueTypeType& FilterRegistry::
valueType ()
{
  return this->valueType_.get ();
}

void FilterRegistry::
valueType (const ValueTypeType& x)
{
  this->valueType_.set (x);
}

void FilterRegistry::
valueType (::std::unique_ptr< ValueTypeType > x)
{
  this->valueType_.set (std::move (x));
}

const FilterRegistry::ValueTypeType& FilterRegistry::
valueType_default_value ()
{
  return valueType_default_value_;
}

const FilterRegistry::ValueDataOptional& FilterRegistry::
valueData () const
{
  return this->valueData_;
}

FilterRegistry::ValueDataOptional& FilterRegistry::
valueData ()
{
  return this->valueData_;
}

void FilterRegistry::
valueData (const ValueDataType& x)
{
  this->valueData_.set (x);
}

void FilterRegistry::
valueData (const ValueDataOptional& x)
{
  this->valueData_ = x;
}

void FilterRegistry::
valueData (::std::unique_ptr< ValueDataType > x)
{
  this->valueData_.set (std::move (x));
}

const FilterRegistry::VariableNameOptional& FilterRegistry::
variableName () const
{
  return this->variableName_;
}

FilterRegistry::VariableNameOptional& FilterRegistry::
variableName ()
{
  return this->variableName_;
}

void FilterRegistry::
variableName (const VariableNameType& x)
{
  this->variableName_.set (x);
}

void FilterRegistry::
variableName (const VariableNameOptional& x)
{
  this->variableName_ = x;
}

void FilterRegistry::
variableName (::std::unique_ptr< VariableNameType > x)
{
  this->variableName_.set (std::move (x));
}

const FilterRegistry::KeyType& FilterRegistry::
key () const
{
  return this->key_.get ();
}

FilterRegistry::KeyType& FilterRegistry::
key ()
{
  return this->key_.get ();
}

void FilterRegistry::
key (const KeyType& x)
{
  this->key_.set (x);
}

void FilterRegistry::
key (::std::unique_ptr< KeyType > x)
{
  this->key_.set (std::move (x));
}

const FilterRegistry::HiveType& FilterRegistry::
hive () const
{
  return this->hive_.get ();
}

FilterRegistry::HiveType& FilterRegistry::
hive ()
{
  return this->hive_.get ();
}

void FilterRegistry::
hive (const HiveType& x)
{
  this->hive_.set (x);
}

void FilterRegistry::
hive (::std::unique_ptr< HiveType > x)
{
  this->hive_.set (std::move (x));
}

const FilterRegistry::HiveType& FilterRegistry::
hive_default_value ()
{
  return hive_default_value_;
}

const FilterRegistry::MinOptional& FilterRegistry::
min () const
{
  return this->min_;
}

FilterRegistry::MinOptional& FilterRegistry::
min ()
{
  return this->min_;
}

void FilterRegistry::
min (const MinType& x)
{
  this->min_.set (x);
}

void FilterRegistry::
min (const MinOptional& x)
{
  this->min_ = x;
}

void FilterRegistry::
min (::std::unique_ptr< MinType > x)
{
  this->min_.set (std::move (x));
}

const FilterRegistry::MaxOptional& FilterRegistry::
max () const
{
  return this->max_;
}

FilterRegistry::MaxOptional& FilterRegistry::
max ()
{
  return this->max_;
}

void FilterRegistry::
max (const MaxType& x)
{
  this->max_.set (x);
}

void FilterRegistry::
max (const MaxOptional& x)
{
  this->max_ = x;
}

void FilterRegistry::
max (::std::unique_ptr< MaxType > x)
{
  this->max_.set (std::move (x));
}

const FilterRegistry::GteType& FilterRegistry::
gte () const
{
  return this->gte_.get ();
}

FilterRegistry::GteType& FilterRegistry::
gte ()
{
  return this->gte_.get ();
}

void FilterRegistry::
gte (const GteType& x)
{
  this->gte_.set (x);
}

void FilterRegistry::
gte (::std::unique_ptr< GteType > x)
{
  this->gte_.set (std::move (x));
}

const FilterRegistry::GteType& FilterRegistry::
gte_default_value ()
{
  return gte_default_value_;
}

const FilterRegistry::LteType& FilterRegistry::
lte () const
{
  return this->lte_.get ();
}

FilterRegistry::LteType& FilterRegistry::
lte ()
{
  return this->lte_.get ();
}

void FilterRegistry::
lte (const LteType& x)
{
  this->lte_.set (x);
}

void FilterRegistry::
lte (::std::unique_ptr< LteType > x)
{
  this->lte_.set (std::move (x));
}

const FilterRegistry::LteType& FilterRegistry::
lte_default_value ()
{
  return lte_default_value_;
}

const FilterRegistry::VersionOptional& FilterRegistry::
version () const
{
  return this->version_;
}

FilterRegistry::VersionOptional& FilterRegistry::
version ()
{
  return this->version_;
}

void FilterRegistry::
version (const VersionType& x)
{
  this->version_.set (x);
}

void FilterRegistry::
version (const VersionOptional& x)
{
  this->version_ = x;
}

void FilterRegistry::
version (::std::unique_ptr< VersionType > x)
{
  this->version_.set (std::move (x));
}


#include <xsd/cxx/xml/dom/wildcard-source.hxx>

#include <xsd/cxx/xml/dom/parsing-source.hxx>

#include <xsd/cxx/tree/type-factory-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_factory_plate< 0, char >
  type_factory_plate_init;
}

// EnumFilterBool
//

EnumFilterBool::
EnumFilterBool (const ::xercesc::DOMElement& e,
                ::xml_schema::Flags f,
                ::xml_schema::Container* c)
: ::xml_schema::String (e, f, c)
{
  _xsd_EnumFilterBool_convert ();
}

EnumFilterBool::
EnumFilterBool (const ::xercesc::DOMAttr& a,
                ::xml_schema::Flags f,
                ::xml_schema::Container* c)
: ::xml_schema::String (a, f, c)
{
  _xsd_EnumFilterBool_convert ();
}

EnumFilterBool::
EnumFilterBool (const ::std::string& s,
                const ::xercesc::DOMElement* e,
                ::xml_schema::Flags f,
                ::xml_schema::Container* c)
: ::xml_schema::String (s, e, f, c)
{
  _xsd_EnumFilterBool_convert ();
}

EnumFilterBool* EnumFilterBool::
_clone (::xml_schema::Flags f,
        ::xml_schema::Container* c) const
{
  return new class EnumFilterBool (*this, f, c);
}

EnumFilterBool::Value EnumFilterBool::
_xsd_EnumFilterBool_convert () const
{
  ::xsd::cxx::tree::enum_comparator< char > c (_xsd_EnumFilterBool_literals_);
  const Value* i (::std::lower_bound (
                    _xsd_EnumFilterBool_indexes_,
                    _xsd_EnumFilterBool_indexes_ + 2,
                    *this,
                    c));

  if (i == _xsd_EnumFilterBool_indexes_ + 2 || _xsd_EnumFilterBool_literals_[*i] != *this)
  {
    throw ::xsd::cxx::tree::unexpected_enumerator < char > (*this);
  }

  return *i;
}

const char* const EnumFilterBool::
_xsd_EnumFilterBool_literals_[2] =
{
  "AND",
  "OR"
};

const EnumFilterBool::Value EnumFilterBool::
_xsd_EnumFilterBool_indexes_[2] =
{
  ::EnumFilterBool::AND,
  ::EnumFilterBool::OR
};

static
const ::xsd::cxx::tree::type_factory_initializer< 0, char, EnumFilterBool >
_xsd_EnumFilterBool_type_factory_init (
  "enumFilterBool",
  "");

// EnumTrueFalse
//

EnumTrueFalse::
EnumTrueFalse (const ::xercesc::DOMElement& e,
               ::xml_schema::Flags f,
               ::xml_schema::Container* c)
: ::xml_schema::String (e, f, c)
{
  _xsd_EnumTrueFalse_convert ();
}

EnumTrueFalse::
EnumTrueFalse (const ::xercesc::DOMAttr& a,
               ::xml_schema::Flags f,
               ::xml_schema::Container* c)
: ::xml_schema::String (a, f, c)
{
  _xsd_EnumTrueFalse_convert ();
}

EnumTrueFalse::
EnumTrueFalse (const ::std::string& s,
               const ::xercesc::DOMElement* e,
               ::xml_schema::Flags f,
               ::xml_schema::Container* c)
: ::xml_schema::String (s, e, f, c)
{
  _xsd_EnumTrueFalse_convert ();
}

EnumTrueFalse* EnumTrueFalse::
_clone (::xml_schema::Flags f,
        ::xml_schema::Container* c) const
{
  return new class EnumTrueFalse (*this, f, c);
}

EnumTrueFalse::Value EnumTrueFalse::
_xsd_EnumTrueFalse_convert () const
{
  ::xsd::cxx::tree::enum_comparator< char > c (_xsd_EnumTrueFalse_literals_);
  const Value* i (::std::lower_bound (
                    _xsd_EnumTrueFalse_indexes_,
                    _xsd_EnumTrueFalse_indexes_ + 2,
                    *this,
                    c));

  if (i == _xsd_EnumTrueFalse_indexes_ + 2 || _xsd_EnumTrueFalse_literals_[*i] != *this)
  {
    throw ::xsd::cxx::tree::unexpected_enumerator < char > (*this);
  }

  return *i;
}

const char* const EnumTrueFalse::
_xsd_EnumTrueFalse_literals_[2] =
{
  "0",
  "1"
};

const EnumTrueFalse::Value EnumTrueFalse::
_xsd_EnumTrueFalse_indexes_[2] =
{
  ::EnumTrueFalse::cxx_0,
  ::EnumTrueFalse::cxx_1
};

static
const ::xsd::cxx::tree::type_factory_initializer< 0, char, EnumTrueFalse >
_xsd_EnumTrueFalse_type_factory_init (
  "enumTrueFalse",
  "");

// EnumFilterRegistryHive
//

EnumFilterRegistryHive::
EnumFilterRegistryHive (const ::xercesc::DOMElement& e,
                        ::xml_schema::Flags f,
                        ::xml_schema::Container* c)
: ::xml_schema::String (e, f, c)
{
  _xsd_EnumFilterRegistryHive_convert ();
}

EnumFilterRegistryHive::
EnumFilterRegistryHive (const ::xercesc::DOMAttr& a,
                        ::xml_schema::Flags f,
                        ::xml_schema::Container* c)
: ::xml_schema::String (a, f, c)
{
  _xsd_EnumFilterRegistryHive_convert ();
}

EnumFilterRegistryHive::
EnumFilterRegistryHive (const ::std::string& s,
                        const ::xercesc::DOMElement* e,
                        ::xml_schema::Flags f,
                        ::xml_schema::Container* c)
: ::xml_schema::String (s, e, f, c)
{
  _xsd_EnumFilterRegistryHive_convert ();
}

EnumFilterRegistryHive* EnumFilterRegistryHive::
_clone (::xml_schema::Flags f,
        ::xml_schema::Container* c) const
{
  return new class EnumFilterRegistryHive (*this, f, c);
}

EnumFilterRegistryHive::Value EnumFilterRegistryHive::
_xsd_EnumFilterRegistryHive_convert () const
{
  ::xsd::cxx::tree::enum_comparator< char > c (_xsd_EnumFilterRegistryHive_literals_);
  const Value* i (::std::lower_bound (
                    _xsd_EnumFilterRegistryHive_indexes_,
                    _xsd_EnumFilterRegistryHive_indexes_ + 5,
                    *this,
                    c));

  if (i == _xsd_EnumFilterRegistryHive_indexes_ + 5 || _xsd_EnumFilterRegistryHive_literals_[*i] != *this)
  {
    throw ::xsd::cxx::tree::unexpected_enumerator < char > (*this);
  }

  return *i;
}

const char* const EnumFilterRegistryHive::
_xsd_EnumFilterRegistryHive_literals_[5] =
{
  "HKEY_LOCAL_MACHINE",
  "HKEY_CLASSES_ROOT",
  "HKEY_CURRENT_USER",
  "HKEY_CURRENT_CONFIG",
  "HKEY_USERS"
};

const EnumFilterRegistryHive::Value EnumFilterRegistryHive::
_xsd_EnumFilterRegistryHive_indexes_[5] =
{
  ::EnumFilterRegistryHive::HKEY_CLASSES_ROOT,
  ::EnumFilterRegistryHive::HKEY_CURRENT_CONFIG,
  ::EnumFilterRegistryHive::HKEY_CURRENT_USER,
  ::EnumFilterRegistryHive::HKEY_LOCAL_MACHINE,
  ::EnumFilterRegistryHive::HKEY_USERS
};

static
const ::xsd::cxx::tree::type_factory_initializer< 0, char, EnumFilterRegistryHive >
_xsd_EnumFilterRegistryHive_type_factory_init (
  "enumFilterRegistryHive",
  "");

// EnumFilterRegistryValueType
//

EnumFilterRegistryValueType::
EnumFilterRegistryValueType (const ::xercesc::DOMElement& e,
                             ::xml_schema::Flags f,
                             ::xml_schema::Container* c)
: ::xml_schema::String (e, f, c)
{
  _xsd_EnumFilterRegistryValueType_convert ();
}

EnumFilterRegistryValueType::
EnumFilterRegistryValueType (const ::xercesc::DOMAttr& a,
                             ::xml_schema::Flags f,
                             ::xml_schema::Container* c)
: ::xml_schema::String (a, f, c)
{
  _xsd_EnumFilterRegistryValueType_convert ();
}

EnumFilterRegistryValueType::
EnumFilterRegistryValueType (const ::std::string& s,
                             const ::xercesc::DOMElement* e,
                             ::xml_schema::Flags f,
                             ::xml_schema::Container* c)
: ::xml_schema::String (s, e, f, c)
{
  _xsd_EnumFilterRegistryValueType_convert ();
}

EnumFilterRegistryValueType* EnumFilterRegistryValueType::
_clone (::xml_schema::Flags f,
        ::xml_schema::Container* c) const
{
  return new class EnumFilterRegistryValueType (*this, f, c);
}

EnumFilterRegistryValueType::Value EnumFilterRegistryValueType::
_xsd_EnumFilterRegistryValueType_convert () const
{
  ::xsd::cxx::tree::enum_comparator< char > c (_xsd_EnumFilterRegistryValueType_literals_);
  const Value* i (::std::lower_bound (
                    _xsd_EnumFilterRegistryValueType_indexes_,
                    _xsd_EnumFilterRegistryValueType_indexes_ + 6,
                    *this,
                    c));

  if (i == _xsd_EnumFilterRegistryValueType_indexes_ + 6 || _xsd_EnumFilterRegistryValueType_literals_[*i] != *this)
  {
    throw ::xsd::cxx::tree::unexpected_enumerator < char > (*this);
  }

  return *i;
}

const char* const EnumFilterRegistryValueType::
_xsd_EnumFilterRegistryValueType_literals_[6] =
{
  "REG_SZ",
  "REG_EXPAND_SZ",
  "REG_MULTI_SZ",
  "REG_DWORD",
  "REG_BINARY",
  ""
};

const EnumFilterRegistryValueType::Value EnumFilterRegistryValueType::
_xsd_EnumFilterRegistryValueType_indexes_[6] =
{
  ::EnumFilterRegistryValueType::empty,
  ::EnumFilterRegistryValueType::REG_BINARY,
  ::EnumFilterRegistryValueType::REG_DWORD,
  ::EnumFilterRegistryValueType::REG_EXPAND_SZ,
  ::EnumFilterRegistryValueType::REG_MULTI_SZ,
  ::EnumFilterRegistryValueType::REG_SZ
};

static
const ::xsd::cxx::tree::type_factory_initializer< 0, char, EnumFilterRegistryValueType >
_xsd_EnumFilterRegistryValueType_type_factory_init (
  "enumFilterRegistryValueType",
  "");

// EnumFilterRegistrySubType
//

EnumFilterRegistrySubType::
EnumFilterRegistrySubType (const ::xercesc::DOMElement& e,
                           ::xml_schema::Flags f,
                           ::xml_schema::Container* c)
: ::xml_schema::String (e, f, c)
{
  _xsd_EnumFilterRegistrySubType_convert ();
}

EnumFilterRegistrySubType::
EnumFilterRegistrySubType (const ::xercesc::DOMAttr& a,
                           ::xml_schema::Flags f,
                           ::xml_schema::Container* c)
: ::xml_schema::String (a, f, c)
{
  _xsd_EnumFilterRegistrySubType_convert ();
}

EnumFilterRegistrySubType::
EnumFilterRegistrySubType (const ::std::string& s,
                           const ::xercesc::DOMElement* e,
                           ::xml_schema::Flags f,
                           ::xml_schema::Container* c)
: ::xml_schema::String (s, e, f, c)
{
  _xsd_EnumFilterRegistrySubType_convert ();
}

EnumFilterRegistrySubType* EnumFilterRegistrySubType::
_clone (::xml_schema::Flags f,
        ::xml_schema::Container* c) const
{
  return new class EnumFilterRegistrySubType (*this, f, c);
}

EnumFilterRegistrySubType::Value EnumFilterRegistrySubType::
_xsd_EnumFilterRegistrySubType_convert () const
{
  ::xsd::cxx::tree::enum_comparator< char > c (_xsd_EnumFilterRegistrySubType_literals_);
  const Value* i (::std::lower_bound (
                    _xsd_EnumFilterRegistrySubType_indexes_,
                    _xsd_EnumFilterRegistrySubType_indexes_ + 4,
                    *this,
                    c));

  if (i == _xsd_EnumFilterRegistrySubType_indexes_ + 4 || _xsd_EnumFilterRegistrySubType_literals_[*i] != *this)
  {
    throw ::xsd::cxx::tree::unexpected_enumerator < char > (*this);
  }

  return *i;
}

const char* const EnumFilterRegistrySubType::
_xsd_EnumFilterRegistrySubType_literals_[4] =
{
  "EQUALHEX",
  "EQUALDEC",
  "SUBSTRING",
  "VERSION"
};

const EnumFilterRegistrySubType::Value EnumFilterRegistrySubType::
_xsd_EnumFilterRegistrySubType_indexes_[4] =
{
  ::EnumFilterRegistrySubType::EQUALDEC,
  ::EnumFilterRegistrySubType::EQUALHEX,
  ::EnumFilterRegistrySubType::SUBSTRING,
  ::EnumFilterRegistrySubType::VERSION
};

static
const ::xsd::cxx::tree::type_factory_initializer< 0, char, EnumFilterRegistrySubType >
_xsd_EnumFilterRegistrySubType_type_factory_init (
  "enumFilterRegistrySubType",
  "");

// EnumFilterRegistryType
//

EnumFilterRegistryType::
EnumFilterRegistryType (const ::xercesc::DOMElement& e,
                        ::xml_schema::Flags f,
                        ::xml_schema::Container* c)
: ::xml_schema::String (e, f, c)
{
  _xsd_EnumFilterRegistryType_convert ();
}

EnumFilterRegistryType::
EnumFilterRegistryType (const ::xercesc::DOMAttr& a,
                        ::xml_schema::Flags f,
                        ::xml_schema::Container* c)
: ::xml_schema::String (a, f, c)
{
  _xsd_EnumFilterRegistryType_convert ();
}

EnumFilterRegistryType::
EnumFilterRegistryType (const ::std::string& s,
                        const ::xercesc::DOMElement* e,
                        ::xml_schema::Flags f,
                        ::xml_schema::Container* c)
: ::xml_schema::String (s, e, f, c)
{
  _xsd_EnumFilterRegistryType_convert ();
}

EnumFilterRegistryType* EnumFilterRegistryType::
_clone (::xml_schema::Flags f,
        ::xml_schema::Container* c) const
{
  return new class EnumFilterRegistryType (*this, f, c);
}

EnumFilterRegistryType::Value EnumFilterRegistryType::
_xsd_EnumFilterRegistryType_convert () const
{
  ::xsd::cxx::tree::enum_comparator< char > c (_xsd_EnumFilterRegistryType_literals_);
  const Value* i (::std::lower_bound (
                    _xsd_EnumFilterRegistryType_indexes_,
                    _xsd_EnumFilterRegistryType_indexes_ + 4,
                    *this,
                    c));

  if (i == _xsd_EnumFilterRegistryType_indexes_ + 4 || _xsd_EnumFilterRegistryType_literals_[*i] != *this)
  {
    throw ::xsd::cxx::tree::unexpected_enumerator < char > (*this);
  }

  return *i;
}

const char* const EnumFilterRegistryType::
_xsd_EnumFilterRegistryType_literals_[4] =
{
  "VALUEEXISTS",
  "KEYEXISTS",
  "MATCHVALUE",
  "GETVALUE"
};

const EnumFilterRegistryType::Value EnumFilterRegistryType::
_xsd_EnumFilterRegistryType_indexes_[4] =
{
  ::EnumFilterRegistryType::GETVALUE,
  ::EnumFilterRegistryType::KEYEXISTS,
  ::EnumFilterRegistryType::MATCHVALUE,
  ::EnumFilterRegistryType::VALUEEXISTS
};

static
const ::xsd::cxx::tree::type_factory_initializer< 0, char, EnumFilterRegistryType >
_xsd_EnumFilterRegistryType_type_factory_init (
  "enumFilterRegistryType",
  "");

// IFilter
//

IFilter::
IFilter (const BoolType& bool_,
         const NotType& not_)
: ::xml_schema::Type (),
  bool__ (bool_, this),
  not__ (not_, this),
  hidden_ (this)
{
}

IFilter::
IFilter (const IFilter& x,
         ::xml_schema::Flags f,
         ::xml_schema::Container* c)
: ::xml_schema::Type (x, f, c),
  bool__ (x.bool__, f, this),
  not__ (x.not__, f, this),
  hidden_ (x.hidden_, f, this)
{
}

IFilter::
IFilter (const ::xercesc::DOMElement& e,
         ::xml_schema::Flags f,
         ::xml_schema::Container* c)
: ::xml_schema::Type (e, f | ::xml_schema::Flags::base, c),
  bool__ (this),
  not__ (this),
  hidden_ (this)
{
  if ((f & ::xml_schema::Flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, false, false, true);
    this->parse (p, f);
  }
}

void IFilter::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::Flags f)
{
  while (p.more_attributes ())
  {
    const ::xercesc::DOMAttr& i (p.next_attribute ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    if (n.name () == "bool" && n.namespace_ ().empty ())
    {
      this->bool__.set (BoolTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "not" && n.namespace_ ().empty ())
    {
      this->not__.set (NotTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "hidden" && n.namespace_ ().empty ())
    {
      this->hidden_.set (HiddenTraits::create (i, f, this));
      continue;
    }
  }

  if (!bool__.present ())
  {
    throw ::xsd::cxx::tree::expected_attribute< char > (
      "bool",
      "");
  }

  if (!not__.present ())
  {
    throw ::xsd::cxx::tree::expected_attribute< char > (
      "not",
      "");
  }
}

IFilter& IFilter::
operator= (const IFilter& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::Type& > (*this) = x;
    this->bool__ = x.bool__;
    this->not__ = x.not__;
    this->hidden_ = x.hidden_;
  }

  return *this;
}

IFilter::
~IFilter ()
{
}

// FilterRegistry
//

const FilterRegistry::TypeType FilterRegistry::type_default_value_ (
  "KEYEXISTS");

const FilterRegistry::SubtypeType FilterRegistry::subtype_default_value_ (
  "EQUALHEX");

const FilterRegistry::ValueTypeType FilterRegistry::valueType_default_value_ (
  "");

const FilterRegistry::HiveType FilterRegistry::hive_default_value_ (
  "HKEY_LOCAL_MACHINE");

const FilterRegistry::GteType FilterRegistry::gte_default_value_ (
  "0");

const FilterRegistry::LteType FilterRegistry::lte_default_value_ (
  "0");

FilterRegistry::
FilterRegistry (const BoolType& bool_,
                const NotType& not_,
                const KeyType& key)
: ::IFilter (bool_,
             not_),
  type_ (type_default_value (), this),
  subtype_ (subtype_default_value (), this),
  valueName_ (this),
  valueType_ (valueType_default_value (), this),
  valueData_ (this),
  variableName_ (this),
  key_ (key, this),
  hive_ (hive_default_value (), this),
  min_ (this),
  max_ (this),
  gte_ (gte_default_value (), this),
  lte_ (lte_default_value (), this),
  version_ (this)
{
}

FilterRegistry::
FilterRegistry (const FilterRegistry& x,
                ::xml_schema::Flags f,
                ::xml_schema::Container* c)
: ::IFilter (x, f, c),
  type_ (x.type_, f, this),
  subtype_ (x.subtype_, f, this),
  valueName_ (x.valueName_, f, this),
  valueType_ (x.valueType_, f, this),
  valueData_ (x.valueData_, f, this),
  variableName_ (x.variableName_, f, this),
  key_ (x.key_, f, this),
  hive_ (x.hive_, f, this),
  min_ (x.min_, f, this),
  max_ (x.max_, f, this),
  gte_ (x.gte_, f, this),
  lte_ (x.lte_, f, this),
  version_ (x.version_, f, this)
{
}

FilterRegistry::
FilterRegistry (const ::xercesc::DOMElement& e,
                ::xml_schema::Flags f,
                ::xml_schema::Container* c)
: ::IFilter (e, f | ::xml_schema::Flags::base, c),
  type_ (this),
  subtype_ (this),
  valueName_ (this),
  valueType_ (this),
  valueData_ (this),
  variableName_ (this),
  key_ (this),
  hive_ (this),
  min_ (this),
  max_ (this),
  gte_ (this),
  lte_ (this),
  version_ (this)
{
  if ((f & ::xml_schema::Flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, false, false, true);
    this->parse (p, f);
  }
}

void FilterRegistry::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::Flags f)
{
  this->::IFilter::parse (p, f);

  p.reset_attributes ();

  while (p.more_attributes ())
  {
    const ::xercesc::DOMAttr& i (p.next_attribute ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    if (n.name () == "type" && n.namespace_ ().empty ())
    {
      this->type_.set (TypeTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "subtype" && n.namespace_ ().empty ())
    {
      this->subtype_.set (SubtypeTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "valueName" && n.namespace_ ().empty ())
    {
      this->valueName_.set (ValueNameTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "valueType" && n.namespace_ ().empty ())
    {
      this->valueType_.set (ValueTypeTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "valueData" && n.namespace_ ().empty ())
    {
      this->valueData_.set (ValueDataTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "variableName" && n.namespace_ ().empty ())
    {
      this->variableName_.set (VariableNameTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "key" && n.namespace_ ().empty ())
    {
      this->key_.set (KeyTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "hive" && n.namespace_ ().empty ())
    {
      this->hive_.set (HiveTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "min" && n.namespace_ ().empty ())
    {
      this->min_.set (MinTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "max" && n.namespace_ ().empty ())
    {
      this->max_.set (MaxTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "gte" && n.namespace_ ().empty ())
    {
      this->gte_.set (GteTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "lte" && n.namespace_ ().empty ())
    {
      this->lte_.set (LteTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "version" && n.namespace_ ().empty ())
    {
      this->version_.set (VersionTraits::create (i, f, this));
      continue;
    }
  }

  if (!type_.present ())
  {
    this->type_.set (type_default_value ());
  }

  if (!subtype_.present ())
  {
    this->subtype_.set (subtype_default_value ());
  }

  if (!valueType_.present ())
  {
    this->valueType_.set (valueType_default_value ());
  }

  if (!key_.present ())
  {
    throw ::xsd::cxx::tree::expected_attribute< char > (
      "key",
      "");
  }

  if (!hive_.present ())
  {
    this->hive_.set (hive_default_value ());
  }

  if (!gte_.present ())
  {
    this->gte_.set (gte_default_value ());
  }

  if (!lte_.present ())
  {
    this->lte_.set (lte_default_value ());
  }
}

FilterRegistry* FilterRegistry::
_clone (::xml_schema::Flags f,
        ::xml_schema::Container* c) const
{
  return new class FilterRegistry (*this, f, c);
}

FilterRegistry& FilterRegistry::
operator= (const FilterRegistry& x)
{
  if (this != &x)
  {
    static_cast< ::IFilter& > (*this) = x;
    this->type_ = x.type_;
    this->subtype_ = x.subtype_;
    this->valueName_ = x.valueName_;
    this->valueType_ = x.valueType_;
    this->valueData_ = x.valueData_;
    this->variableName_ = x.variableName_;
    this->key_ = x.key_;
    this->hive_ = x.hive_;
    this->min_ = x.min_;
    this->max_ = x.max_;
    this->gte_ = x.gte_;
    this->lte_ = x.lte_;
    this->version_ = x.version_;
  }

  return *this;
}

FilterRegistry::
~FilterRegistry ()
{
}

#include <ostream>

#include <xsd/cxx/tree/std-ostream-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::std_ostream_plate< 0, char >
  std_ostream_plate_init;
}

::std::ostream&
operator<< (::std::ostream& o, EnumFilterBool::Value i)
{
  return o << EnumFilterBool::_xsd_EnumFilterBool_literals_[i];
}

::std::ostream&
operator<< (::std::ostream& o, const EnumFilterBool& i)
{
  return o << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::std_ostream_initializer< 0, char, EnumFilterBool >
_xsd_EnumFilterBool_std_ostream_init;

::std::ostream&
operator<< (::std::ostream& o, EnumTrueFalse::Value i)
{
  return o << EnumTrueFalse::_xsd_EnumTrueFalse_literals_[i];
}

::std::ostream&
operator<< (::std::ostream& o, const EnumTrueFalse& i)
{
  return o << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::std_ostream_initializer< 0, char, EnumTrueFalse >
_xsd_EnumTrueFalse_std_ostream_init;

::std::ostream&
operator<< (::std::ostream& o, EnumFilterRegistryHive::Value i)
{
  return o << EnumFilterRegistryHive::_xsd_EnumFilterRegistryHive_literals_[i];
}

::std::ostream&
operator<< (::std::ostream& o, const EnumFilterRegistryHive& i)
{
  return o << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::std_ostream_initializer< 0, char, EnumFilterRegistryHive >
_xsd_EnumFilterRegistryHive_std_ostream_init;

::std::ostream&
operator<< (::std::ostream& o, EnumFilterRegistryValueType::Value i)
{
  return o << EnumFilterRegistryValueType::_xsd_EnumFilterRegistryValueType_literals_[i];
}

::std::ostream&
operator<< (::std::ostream& o, const EnumFilterRegistryValueType& i)
{
  return o << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::std_ostream_initializer< 0, char, EnumFilterRegistryValueType >
_xsd_EnumFilterRegistryValueType_std_ostream_init;

::std::ostream&
operator<< (::std::ostream& o, EnumFilterRegistrySubType::Value i)
{
  return o << EnumFilterRegistrySubType::_xsd_EnumFilterRegistrySubType_literals_[i];
}

::std::ostream&
operator<< (::std::ostream& o, const EnumFilterRegistrySubType& i)
{
  return o << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::std_ostream_initializer< 0, char, EnumFilterRegistrySubType >
_xsd_EnumFilterRegistrySubType_std_ostream_init;

::std::ostream&
operator<< (::std::ostream& o, EnumFilterRegistryType::Value i)
{
  return o << EnumFilterRegistryType::_xsd_EnumFilterRegistryType_literals_[i];
}

::std::ostream&
operator<< (::std::ostream& o, const EnumFilterRegistryType& i)
{
  return o << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::std_ostream_initializer< 0, char, EnumFilterRegistryType >
_xsd_EnumFilterRegistryType_std_ostream_init;

::std::ostream&
operator<< (::std::ostream& o, const IFilter& i)
{
  o << ::std::endl << "bool: " << i.bool_ ();
  o << ::std::endl << "not: " << i.not_ ();
  if (i.hidden ())
  {
    o << ::std::endl << "hidden: " << *i.hidden ();
  }

  return o;
}

::std::ostream&
operator<< (::std::ostream& o, const FilterRegistry& i)
{
  o << static_cast< const ::IFilter& > (i);

  o << ::std::endl << "type: " << i.type ();
  o << ::std::endl << "subtype: " << i.subtype ();
  if (i.valueName ())
  {
    o << ::std::endl << "valueName: " << *i.valueName ();
  }

  o << ::std::endl << "valueType: " << i.valueType ();
  if (i.valueData ())
  {
    o << ::std::endl << "valueData: " << *i.valueData ();
  }

  if (i.variableName ())
  {
    o << ::std::endl << "variableName: " << *i.variableName ();
  }

  o << ::std::endl << "key: " << i.key ();
  o << ::std::endl << "hive: " << i.hive ();
  if (i.min ())
  {
    o << ::std::endl << "min: " << *i.min ();
  }

  if (i.max ())
  {
    o << ::std::endl << "max: " << *i.max ();
  }

  o << ::std::endl << "gte: " << i.gte ();
  o << ::std::endl << "lte: " << i.lte ();
  if (i.version ())
  {
    o << ::std::endl << "version: " << *i.version ();
  }

  return o;
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

::std::unique_ptr< ::FilterRegistry >
FilterRegistry_ (const ::std::string& u,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  return ::std::unique_ptr< ::FilterRegistry > (
    ::FilterRegistry_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::FilterRegistry >
FilterRegistry_ (const ::std::string& u,
                 ::xml_schema::ErrorHandler& h,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::FilterRegistry > (
    ::FilterRegistry_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::FilterRegistry >
FilterRegistry_ (const ::std::string& u,
                 ::xercesc::DOMErrorHandler& h,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::FilterRegistry > (
    ::FilterRegistry_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::FilterRegistry >
FilterRegistry_ (::std::istream& is,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::FilterRegistry_ (isrc, f, p);
}

::std::unique_ptr< ::FilterRegistry >
FilterRegistry_ (::std::istream& is,
                 ::xml_schema::ErrorHandler& h,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::FilterRegistry_ (isrc, h, f, p);
}

::std::unique_ptr< ::FilterRegistry >
FilterRegistry_ (::std::istream& is,
                 ::xercesc::DOMErrorHandler& h,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::FilterRegistry_ (isrc, h, f, p);
}

::std::unique_ptr< ::FilterRegistry >
FilterRegistry_ (::std::istream& is,
                 const ::std::string& sid,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::FilterRegistry_ (isrc, f, p);
}

::std::unique_ptr< ::FilterRegistry >
FilterRegistry_ (::std::istream& is,
                 const ::std::string& sid,
                 ::xml_schema::ErrorHandler& h,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::FilterRegistry_ (isrc, h, f, p);
}

::std::unique_ptr< ::FilterRegistry >
FilterRegistry_ (::std::istream& is,
                 const ::std::string& sid,
                 ::xercesc::DOMErrorHandler& h,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::FilterRegistry_ (isrc, h, f, p);
}

::std::unique_ptr< ::FilterRegistry >
FilterRegistry_ (::xercesc::InputSource& i,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties& p)
{
  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  return ::std::unique_ptr< ::FilterRegistry > (
    ::FilterRegistry_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::FilterRegistry >
FilterRegistry_ (::xercesc::InputSource& i,
                 ::xml_schema::ErrorHandler& h,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::FilterRegistry > (
    ::FilterRegistry_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::FilterRegistry >
FilterRegistry_ (::xercesc::InputSource& i,
                 ::xercesc::DOMErrorHandler& h,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::FilterRegistry > (
    ::FilterRegistry_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::FilterRegistry >
FilterRegistry_ (const ::xercesc::DOMDocument& doc,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties& p)
{
  if (f & ::xml_schema::Flags::keep_dom)
  {
    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      static_cast< ::xercesc::DOMDocument* > (doc.cloneNode (true)));

    return ::std::unique_ptr< ::FilterRegistry > (
      ::FilterRegistry_ (
        std::move (d), f | ::xml_schema::Flags::own_dom, p));
  }

  const ::xercesc::DOMElement& e (*doc.getDocumentElement ());
  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (n.name () == "FilterRegistry" &&
      n.namespace_ () == "")
  {
    ::std::unique_ptr< ::FilterRegistry > r (
      ::xsd::cxx::tree::traits< ::FilterRegistry, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "FilterRegistry",
    "");
}

::std::unique_ptr< ::FilterRegistry >
FilterRegistry_ (::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d,
                 ::xml_schema::Flags f,
                 const ::xml_schema::Properties&)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > c (
    ((f & ::xml_schema::Flags::keep_dom) &&
     !(f & ::xml_schema::Flags::own_dom))
    ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
    : 0);

  ::xercesc::DOMDocument& doc (c.get () ? *c : *d);
  const ::xercesc::DOMElement& e (*doc.getDocumentElement ());

  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (f & ::xml_schema::Flags::keep_dom)
    doc.setUserData (::xml_schema::dom::tree_node_key,
                     (c.get () ? &c : &d),
                     0);

  if (n.name () == "FilterRegistry" &&
      n.namespace_ () == "")
  {
    ::std::unique_ptr< ::FilterRegistry > r (
      ::xsd::cxx::tree::traits< ::FilterRegistry, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "FilterRegistry",
    "");
}

#include <ostream>
#include <xsd/cxx/tree/error-handler.hxx>
#include <xsd/cxx/xml/dom/serialization-source.hxx>

#include <xsd/cxx/tree/type-serializer-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_serializer_plate< 0, char >
  type_serializer_plate_init;
}

void
operator<< (::xercesc::DOMElement& e, const EnumFilterBool& i)
{
  e << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xercesc::DOMAttr& a, const EnumFilterBool& i)
{
  a << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xml_schema::ListStream& l,
            const EnumFilterBool& i)
{
  l << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::type_serializer_initializer< 0, char, EnumFilterBool >
_xsd_EnumFilterBool_type_serializer_init (
  "enumFilterBool",
  "");


void
operator<< (::xercesc::DOMElement& e, const EnumTrueFalse& i)
{
  e << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xercesc::DOMAttr& a, const EnumTrueFalse& i)
{
  a << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xml_schema::ListStream& l,
            const EnumTrueFalse& i)
{
  l << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::type_serializer_initializer< 0, char, EnumTrueFalse >
_xsd_EnumTrueFalse_type_serializer_init (
  "enumTrueFalse",
  "");


void
operator<< (::xercesc::DOMElement& e, const EnumFilterRegistryHive& i)
{
  e << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xercesc::DOMAttr& a, const EnumFilterRegistryHive& i)
{
  a << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xml_schema::ListStream& l,
            const EnumFilterRegistryHive& i)
{
  l << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::type_serializer_initializer< 0, char, EnumFilterRegistryHive >
_xsd_EnumFilterRegistryHive_type_serializer_init (
  "enumFilterRegistryHive",
  "");


void
operator<< (::xercesc::DOMElement& e, const EnumFilterRegistryValueType& i)
{
  e << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xercesc::DOMAttr& a, const EnumFilterRegistryValueType& i)
{
  a << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xml_schema::ListStream& l,
            const EnumFilterRegistryValueType& i)
{
  l << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::type_serializer_initializer< 0, char, EnumFilterRegistryValueType >
_xsd_EnumFilterRegistryValueType_type_serializer_init (
  "enumFilterRegistryValueType",
  "");


void
operator<< (::xercesc::DOMElement& e, const EnumFilterRegistrySubType& i)
{
  e << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xercesc::DOMAttr& a, const EnumFilterRegistrySubType& i)
{
  a << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xml_schema::ListStream& l,
            const EnumFilterRegistrySubType& i)
{
  l << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::type_serializer_initializer< 0, char, EnumFilterRegistrySubType >
_xsd_EnumFilterRegistrySubType_type_serializer_init (
  "enumFilterRegistrySubType",
  "");


void
operator<< (::xercesc::DOMElement& e, const EnumFilterRegistryType& i)
{
  e << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xercesc::DOMAttr& a, const EnumFilterRegistryType& i)
{
  a << static_cast< const ::xml_schema::String& > (i);
}

void
operator<< (::xml_schema::ListStream& l,
            const EnumFilterRegistryType& i)
{
  l << static_cast< const ::xml_schema::String& > (i);
}

static
const ::xsd::cxx::tree::type_serializer_initializer< 0, char, EnumFilterRegistryType >
_xsd_EnumFilterRegistryType_type_serializer_init (
  "enumFilterRegistryType",
  "");


void
operator<< (::xercesc::DOMElement& e, const IFilter& i)
{
  e << static_cast< const ::xml_schema::Type& > (i);

  // bool
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "bool",
        e));

    a << i.bool_ ();
  }

  // not
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "not",
        e));

    a << i.not_ ();
  }

  // hidden
  //
  if (i.hidden ())
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "hidden",
        e));

    a << *i.hidden ();
  }
}

void
FilterRegistry_ (::std::ostream& o,
                 const ::FilterRegistry& s,
                 const ::xml_schema::NamespaceInfomap& m,
                 const ::std::string& e,
                 ::xml_schema::Flags f)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0);

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::FilterRegistry_ (s, m, f));

  ::xsd::cxx::tree::error_handler< char > h;

  ::xsd::cxx::xml::dom::ostream_format_target t (o);
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
  }
}

void
FilterRegistry_ (::std::ostream& o,
                 const ::FilterRegistry& s,
                 ::xml_schema::ErrorHandler& h,
                 const ::xml_schema::NamespaceInfomap& m,
                 const ::std::string& e,
                 ::xml_schema::Flags f)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0);

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::FilterRegistry_ (s, m, f));
  ::xsd::cxx::xml::dom::ostream_format_target t (o);
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
FilterRegistry_ (::std::ostream& o,
                 const ::FilterRegistry& s,
                 ::xercesc::DOMErrorHandler& h,
                 const ::xml_schema::NamespaceInfomap& m,
                 const ::std::string& e,
                 ::xml_schema::Flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::FilterRegistry_ (s, m, f));
  ::xsd::cxx::xml::dom::ostream_format_target t (o);
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
FilterRegistry_ (::xercesc::XMLFormatTarget& t,
                 const ::FilterRegistry& s,
                 const ::xml_schema::NamespaceInfomap& m,
                 const ::std::string& e,
                 ::xml_schema::Flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::FilterRegistry_ (s, m, f));

  ::xsd::cxx::tree::error_handler< char > h;

  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
  }
}

void
FilterRegistry_ (::xercesc::XMLFormatTarget& t,
                 const ::FilterRegistry& s,
                 ::xml_schema::ErrorHandler& h,
                 const ::xml_schema::NamespaceInfomap& m,
                 const ::std::string& e,
                 ::xml_schema::Flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::FilterRegistry_ (s, m, f));
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
FilterRegistry_ (::xercesc::XMLFormatTarget& t,
                 const ::FilterRegistry& s,
                 ::xercesc::DOMErrorHandler& h,
                 const ::xml_schema::NamespaceInfomap& m,
                 const ::std::string& e,
                 ::xml_schema::Flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::FilterRegistry_ (s, m, f));
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
FilterRegistry_ (::xercesc::DOMDocument& d,
                 const ::FilterRegistry& s,
                 ::xml_schema::Flags)
{
  ::xercesc::DOMElement& e (*d.getDocumentElement ());
  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (n.name () == "FilterRegistry" &&
      n.namespace_ () == "")
  {
    e << s;
  }
  else
  {
    throw ::xsd::cxx::tree::unexpected_element < char > (
      n.name (),
      n.namespace_ (),
      "FilterRegistry",
      "");
  }
}

::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument >
FilterRegistry_ (const ::FilterRegistry& s,
                 const ::xml_schema::NamespaceInfomap& m,
                 ::xml_schema::Flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::serialize< char > (
      "FilterRegistry",
      "",
      m, f));

  ::FilterRegistry_ (*d, s, f);
  return d;
}

void
operator<< (::xercesc::DOMElement& e, const FilterRegistry& i)
{
  e << static_cast< const ::IFilter& > (i);

  // type
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "type",
        e));

    a << i.type ();
  }

  // subtype
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "subtype",
        e));

    a << i.subtype ();
  }

  // valueName
  //
  if (i.valueName ())
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "valueName",
        e));

    a << *i.valueName ();
  }

  // valueType
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "valueType",
        e));

    a << i.valueType ();
  }

  // valueData
  //
  if (i.valueData ())
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "valueData",
        e));

    a << *i.valueData ();
  }

  // variableName
  //
  if (i.variableName ())
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "variableName",
        e));

    a << *i.variableName ();
  }

  // key
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "key",
        e));

    a << i.key ();
  }

  // hive
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "hive",
        e));

    a << i.hive ();
  }

  // min
  //
  if (i.min ())
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "min",
        e));

    a << *i.min ();
  }

  // max
  //
  if (i.max ())
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "max",
        e));

    a << *i.max ();
  }

  // gte
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "gte",
        e));

    a << i.gte ();
  }

  // lte
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "lte",
        e));

    a << i.lte ();
  }

  // version
  //
  if (i.version ())
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "version",
        e));

    a << *i.version ();
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

