<?xml version="1.0" encoding="utf-8"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified"
    attributeFormDefault="unqualified">

    <xs:simpleType name="UnitState_t">
        <xs:restriction base="xs:string">
            <xs:enumeration value="as_is"/>
            <xs:enumeration value="enable"/>
            <xs:enumeration value="disable"/>
            <xs:enumeration value="mask"/>
            <xs:enumeration value="unmask"/>
            <xs:enumeration value="preset"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="UnitApplyMode_t">
        <xs:restriction base="xs:string">
            <xs:enumeration value="always"/>
            <xs:enumeration value="if_exists"/>
            <xs:enumeration value="if_missing"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="UnitPolicyTarget_t">
        <xs:restriction base="xs:string">
            <xs:enumeration value="machine"/>
            <xs:enumeration value="user"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="UnitFileMode_t">
        <xs:restriction base="xs:string">
            <xs:enumeration value="table"/>
            <xs:enumeration value="text"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="FileDependencyMode_t">
        <xs:restriction base="xs:string">
            <xs:enumeration value="changed"/>
            <xs:enumeration value="presence_changed"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="FileDependence_t">
        <xs:attribute name="mode" type="FileDependencyMode_t" use="required"/>
        <xs:attribute name="path" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="FileDependencies_t">
        <xs:sequence>
            <xs:element name="Dependency"
                        type="FileDependence_t"
                        minOccurs="0"
                        maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="UnitFile_t">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="mode" type="UnitFileMode_t" use="optional" default="table"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="BaseUnitProperties_t">
        <xs:attribute name="unit" type="xs:string" use="required"/>
        <xs:attribute name="state" type="UnitState_t" use="required"/>

        <xs:attribute name="now" type="xs:boolean" use="optional" default="false"/>

        <xs:attribute name="applyMode" type="UnitApplyMode_t"
                      use="optional" default="always"/>

        <xs:attribute name="policyTarget" type="UnitPolicyTarget_t"
                      use="optional" default="machine"/>

        <xs:attribute name="dropInName" type="xs:string" use="optional"/>
    </xs:complexType>

    <xs:complexType name="UnitWithEdits_t">
        <xs:complexContent>
            <xs:extension base="BaseUnitProperties_t">
                <xs:sequence>
                    <xs:element name="UnitFile"
                                type="UnitFile_t"
                                minOccurs="0"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="UnitWithEditsAndFileDeps_t">
        <xs:complexContent>
            <xs:extension base="BaseUnitProperties_t">
                <xs:sequence>
                    <xs:element name="UnitFile"
                                type="UnitFile_t"
                                minOccurs="0"/>
                    <xs:element name="FileDependencies"
                                type="FileDependencies_t"
                                minOccurs="0"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="BasePolicyItem_t">
        <xs:attribute name="clsid" type="xs:string" use="required"/>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="status" type="xs:string" use="optional"/>
        <xs:attribute name="image" type="xs:unsignedByte" use="optional"/>
        <xs:attribute name="changed" type="xs:string" use="optional"/>
        <xs:attribute name="uid" type="xs:string" use="required"/>
        <xs:attribute name="desc" type="xs:string" use="optional"/>
        <xs:attribute name="bypassErrors" type="xs:integer" use="optional"/>
        <xs:attribute name="userContext" type="xs:integer" use="optional"/>
        <xs:attribute name="removePolicy" type="xs:integer" use="optional"/>
    </xs:complexType>

    <xs:complexType name="PolicyWithFileDeps_t">
        <xs:complexContent>
            <xs:extension base="BasePolicyItem_t">
                <xs:sequence>
                    <xs:element name="Properties"
                                type="UnitWithEditsAndFileDeps_t"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="PolicyEditsOnly_t">
        <xs:complexContent>
            <xs:extension base="BasePolicyItem_t">
                <xs:sequence>
                    <xs:element name="Properties"
                                type="UnitWithEdits_t"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="Systemds">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Service" type="PolicyWithFileDeps_t" maxOccurs="unbounded"/>
                <xs:element name="Socket" type="PolicyWithFileDeps_t" maxOccurs="unbounded"/>
                <xs:element name="Timer" type="PolicyWithFileDeps_t" maxOccurs="unbounded"/>
                <xs:element name="Path" type="PolicyWithFileDeps_t" maxOccurs="unbounded"/>
                <xs:element name="Mount" type="PolicyWithFileDeps_t" maxOccurs="unbounded"/>
                <xs:element name="Automount" type="PolicyWithFileDeps_t" maxOccurs="unbounded"/>
                <xs:element name="Swap" type="PolicyWithFileDeps_t" maxOccurs="unbounded"/>

                <xs:element name="Target" type="PolicyEditsOnly_t" maxOccurs="unbounded"/>
                <xs:element name="Device" type="PolicyEditsOnly_t" maxOccurs="unbounded"/>
                <xs:element name="Slice" type="PolicyEditsOnly_t" maxOccurs="unbounded"/>
                <xs:element name="Scope" type="PolicyEditsOnly_t" maxOccurs="unbounded"/>
            </xs:sequence>

            <xs:attribute name="clsid" type="xs:string" use="required"/>
            <xs:attribute name="disabled" type="xs:unsignedByte" use="optional"/>
        </xs:complexType>
    </xs:element>

</xs:schema>
